package com.genoma.plus.dao.impl.laboratorio;

import Acceso.Principal;
import Utilidades.Metodos;
import com.genoma.plus.dao.laboratorio.RecepcionStikerDAO;
import java.util.List;
import javax.sql.DataSource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;

/* JADX INFO: loaded from: GenomaP.jar:com/genoma/plus/dao/impl/laboratorio/RecepcionStikerDAOImpl.class */
public class RecepcionStikerDAOImpl implements RecepcionStikerDAO {
    public Metodos xmt = new Metodos();
    private JdbcTemplate jdbcTemplate;

    public void setDataSource(DataSource dataSource) {
        this.jdbcTemplate = new JdbcTemplate(dataSource);
    }

    @Override // com.genoma.plus.dao.laboratorio.RecepcionStikerDAO
    public List<Object[]> ListRecepcionStikers(String xFechaI, String xFechaF, String xIdMunicipio, String xBuscar, int opc) {
        RowMapper mapper = (rs, rowNum) -> {
            Object[] fila = {Long.valueOf(rs.getLong(1)), rs.getString(2), rs.getString(3), rs.getString(4), true, rs.getString(5)};
            return fila;
        };
        String sql = "";
        if (Principal.informacionIps.getNombreIps().equals("LABORATORIO CLINICO VIVIAN RAMIREZ I.P.S. S.A.")) {
            if (opc == 0) {
                sql = "SELECT l_recepcion.`Id` IdRecepcion, g_usuario.NoHistoria, CONCAT(g_persona.`Apellido1`,' ',g_persona.`Apellido2`,' ',g_persona.`Nombre1`,' ',g_persona.`Nombre2`) AS NUsuario, `g_municipio`.`Nbre` AS Municipio, l_recepcion.ImpresionStiker \nFROM f_itemordenesproced \nINNER JOIN l_codigoprouni ON (f_itemordenesproced.Id_Procedimiento = l_codigoprouni.Id_Procedimiento) \nINNER JOIN f_ordenes ON (f_itemordenesproced.Id_Ordenes = f_ordenes.Id) \nINNER JOIN g_procedimiento ON (f_itemordenesproced.Id_Procedimiento = g_procedimiento.Id)     \nINNER JOIN ingreso  ON (f_ordenes.Id_Ingreso = ingreso.Id) \nINNER JOIN `f_empresacontxconvenio`  ON (f_empresacontxconvenio.`Id` = ingreso.`Id_EmpresaContxConv`) \nINNER JOIN `g_usuario`  ON (`ingreso`.`Id_Usuario` = `g_usuario`.`Id_persona`) \nINNER JOIN `g_persona`  ON (`g_usuario`.`Id_persona` = `g_persona`.`Id`)\nINNER JOIN `g_municipio`  ON (`g_municipio`.`Id` = `g_persona`.`Id_Municipio`)    \nINNER JOIN `g_tipoedad`  ON (`g_persona`.`Id_TipoEdad` = `g_tipoedad`.`Id`)  \nINNER JOIN `g_tipoatencion`  ON (g_tipoatencion.`Id` = ingreso.`Id_TipoAtencion`)  \nLEFT JOIN `f_camas`  ON (f_camas.`Id` = ingreso.`Cama`) \nLEFT JOIN `f_unidadcama`  ON (f_camas.`Id_UnidadCamas` = f_unidadcama.`Id`) INNER JOIN  `l_recepcion` ON (l_recepcion.`Id_OrdenFacturac`=f_ordenes.`Id` AND f_ordenes.`Estado`=0) \nWHERE ( g_procedimiento.EsOdontologico=0 \nAND f_ordenes.EstadoRecep IN (1,2) AND f_ordenes.Estado =0 AND f_ordenes.FechaOrden >='" + xFechaI + "' AND f_ordenes.FechaOrden <='" + xFechaF + "' AND (l_recepcion.`Id` LIKE '" + xBuscar + "%' OR CONCAT(g_persona.`Apellido1`,' ',g_persona.`Apellido2`,' ',g_persona.`Nombre1`,' ',g_persona.`Nombre2`) LIKE '" + xBuscar + "%'))\nGROUP BY f_ordenes.Id ORDER BY l_recepcion.`Id` asc";
            } else if (opc == 1) {
                sql = "SELECT l_recepcion.`Id` IdRecepcion, g_usuario.NoHistoria, CONCAT(g_persona.`Apellido1`,' ',g_persona.`Apellido2`,' ',g_persona.`Nombre1`,' ',g_persona.`Nombre2`) AS NUsuario, `g_municipio`.`Nbre` AS Municipio, l_recepcion.ImpresionStiker \nFROM f_itemordenesproced \nINNER JOIN l_codigoprouni ON (f_itemordenesproced.Id_Procedimiento = l_codigoprouni.Id_Procedimiento) \nINNER JOIN f_ordenes ON (f_itemordenesproced.Id_Ordenes = f_ordenes.Id) \nINNER JOIN g_procedimiento ON (f_itemordenesproced.Id_Procedimiento = g_procedimiento.Id)     \nINNER JOIN ingreso  ON (f_ordenes.Id_Ingreso = ingreso.Id) \nINNER JOIN `f_empresacontxconvenio`  ON (f_empresacontxconvenio.`Id` = ingreso.`Id_EmpresaContxConv`) \nINNER JOIN `g_usuario`  ON (`ingreso`.`Id_Usuario` = `g_usuario`.`Id_persona`) \nINNER JOIN `g_persona`  ON (`g_usuario`.`Id_persona` = `g_persona`.`Id`)\nINNER JOIN `g_municipio`  ON (`g_municipio`.`Id` = `g_persona`.`Id_Municipio`)    \nINNER JOIN `g_tipoedad`  ON (`g_persona`.`Id_TipoEdad` = `g_tipoedad`.`Id`)  \nINNER JOIN `g_tipoatencion`  ON (g_tipoatencion.`Id` = ingreso.`Id_TipoAtencion`)  \nLEFT JOIN `f_camas`  ON (f_camas.`Id` = ingreso.`Cama`) \nLEFT JOIN `f_unidadcama`  ON (f_camas.`Id_UnidadCamas` = f_unidadcama.`Id`) INNER JOIN  `l_recepcion` ON (l_recepcion.`Id_OrdenFacturac`=f_ordenes.`Id` AND f_ordenes.`Estado`=0) \nWHERE ( g_procedimiento.EsOdontologico=0 \nAND f_ordenes.EstadoRecep IN (1,2) AND f_ordenes.Estado =0 AND f_ordenes.FechaOrden >='" + xFechaI + "' AND f_ordenes.FechaOrden <='" + xFechaF + "' AND `g_municipio`.`Id`='" + xIdMunicipio + "' AND (l_recepcion.`Id` LIKE '" + xBuscar + "%' OR CONCAT(g_persona.`Apellido1`,' ',g_persona.`Apellido2`,' ',g_persona.`Nombre1`,' ',g_persona.`Nombre2`) LIKE '" + xBuscar + "%'))\nGROUP BY f_ordenes.Id ORDER BY l_recepcion.`Id` asc";
            }
        } else if (opc == 0) {
            sql = "SELECT l_recepcion.`Id` IdRecepcion, g_usuario.NoHistoria, CONCAT(g_persona.`Apellido1`,' ',g_persona.`Apellido2`,' ',g_persona.`Nombre1`,' ',g_persona.`Nombre2`) AS NUsuario, `g_municipio`.`Nbre` AS Municipio, l_recepcion.ImpresionStiker \nFROM f_itemordenesproced \nINNER JOIN l_codigoprouni ON (f_itemordenesproced.Id_Procedimiento = l_codigoprouni.Id_Procedimiento) \nINNER JOIN f_ordenes ON (f_itemordenesproced.Id_Ordenes = f_ordenes.Id) \nINNER JOIN g_procedimiento ON (f_itemordenesproced.Id_Procedimiento = g_procedimiento.Id)     \nINNER JOIN ingreso  ON (f_ordenes.Id_Ingreso = ingreso.Id) \nINNER JOIN `f_empresacontxconvenio`  ON (f_empresacontxconvenio.`Id` = ingreso.`Id_EmpresaContxConv`) \nINNER JOIN `g_usuario`  ON (`ingreso`.`Id_Usuario` = `g_usuario`.`Id_persona`) \nINNER JOIN `g_persona`  ON (`g_usuario`.`Id_persona` = `g_persona`.`Id`)\nINNER JOIN `g_municipio`  ON (`g_municipio`.`Id` = `g_persona`.`Id_Municipio`)    \nINNER JOIN `g_tipoedad`  ON (`g_persona`.`Id_TipoEdad` = `g_tipoedad`.`Id`)  \nINNER JOIN `g_tipoatencion`  ON (g_tipoatencion.`Id` = ingreso.`Id_TipoAtencion`)  \nLEFT JOIN `f_camas`  ON (f_camas.`Id` = ingreso.`Cama`) \nLEFT JOIN `f_unidadcama`  ON (f_camas.`Id_UnidadCamas` = f_unidadcama.`Id`) INNER JOIN  `l_recepcion` ON (l_recepcion.`Id_OrdenFacturac`=f_ordenes.`Id` AND f_ordenes.`Estado`=0) \nWHERE ( g_procedimiento.EsOdontologico=0 \nAND f_ordenes.EstadoRecep IN (1,2) AND f_ordenes.Estado =0 AND f_ordenes.FechaOrden >='" + xFechaI + "' AND f_ordenes.FechaOrden <='" + xFechaF + "' AND (l_recepcion.`Id` LIKE '" + xBuscar + "%' OR CONCAT(g_persona.`Apellido1`,' ',g_persona.`Apellido2`,' ',g_persona.`Nombre1`,' ',g_persona.`Nombre2`) LIKE '" + xBuscar + "%'))\nGROUP BY f_ordenes.Id ORDER BY ingreso.HoraIngreso ASC, ingreso.FechaIngreso ASC";
        } else if (opc == 1) {
            sql = "SELECT l_recepcion.`Id` IdRecepcion, g_usuario.NoHistoria, CONCAT(g_persona.`Apellido1`,' ',g_persona.`Apellido2`,' ',g_persona.`Nombre1`,' ',g_persona.`Nombre2`) AS NUsuario, `g_municipio`.`Nbre` AS Municipio, l_recepcion.ImpresionStiker \nFROM f_itemordenesproced \nINNER JOIN l_codigoprouni ON (f_itemordenesproced.Id_Procedimiento = l_codigoprouni.Id_Procedimiento) \nINNER JOIN f_ordenes ON (f_itemordenesproced.Id_Ordenes = f_ordenes.Id) \nINNER JOIN g_procedimiento ON (f_itemordenesproced.Id_Procedimiento = g_procedimiento.Id)     \nINNER JOIN ingreso  ON (f_ordenes.Id_Ingreso = ingreso.Id) \nINNER JOIN `f_empresacontxconvenio`  ON (f_empresacontxconvenio.`Id` = ingreso.`Id_EmpresaContxConv`) \nINNER JOIN `g_usuario`  ON (`ingreso`.`Id_Usuario` = `g_usuario`.`Id_persona`) \nINNER JOIN `g_persona`  ON (`g_usuario`.`Id_persona` = `g_persona`.`Id`)\nINNER JOIN `g_municipio`  ON (`g_municipio`.`Id` = `g_persona`.`Id_Municipio`)    \nINNER JOIN `g_tipoedad`  ON (`g_persona`.`Id_TipoEdad` = `g_tipoedad`.`Id`)  \nINNER JOIN `g_tipoatencion`  ON (g_tipoatencion.`Id` = ingreso.`Id_TipoAtencion`)  \nLEFT JOIN `f_camas`  ON (f_camas.`Id` = ingreso.`Cama`) \nLEFT JOIN `f_unidadcama`  ON (f_camas.`Id_UnidadCamas` = f_unidadcama.`Id`) INNER JOIN  `l_recepcion` ON (l_recepcion.`Id_OrdenFacturac`=f_ordenes.`Id` AND f_ordenes.`Estado`=0) \nWHERE ( g_procedimiento.EsOdontologico=0 \nAND f_ordenes.EstadoRecep IN (1,2) AND f_ordenes.Estado =0 AND f_ordenes.FechaOrden >='" + xFechaI + "' AND f_ordenes.FechaOrden <='" + xFechaF + "' AND `g_municipio`.`Id`='" + xIdMunicipio + "' AND (l_recepcion.`Id` LIKE '" + xBuscar + "%' OR CONCAT(g_persona.`Apellido1`,' ',g_persona.`Apellido2`,' ',g_persona.`Nombre1`,' ',g_persona.`Nombre2`) LIKE '" + xBuscar + "%'))\nGROUP BY f_ordenes.Id ORDER BY ingreso.HoraIngreso ASC, ingreso.FechaIngreso ASC";
        }
        List<Object[]> list = this.jdbcTemplate.query(sql, mapper);
        return list;
    }

    @Override // com.genoma.plus.dao.laboratorio.RecepcionStikerDAO
    public List<Object[]> ListMunicipiosRecepcion(String xFechaI, String xFechaF) {
        RowMapper mapper = (rs, rowNum) -> {
            Object[] fila = {rs.getString(1), rs.getString(2)};
            return fila;
        };
        String xsql = "SELECT  `g_municipio`.`Id`, `g_municipio`.`Nbre`\nFROM f_itemordenesproced \nINNER JOIN l_codigoprouni ON (f_itemordenesproced.Id_Procedimiento = l_codigoprouni.Id_Procedimiento) \nINNER JOIN f_ordenes ON (f_itemordenesproced.Id_Ordenes = f_ordenes.Id) \nINNER JOIN g_procedimiento ON (f_itemordenesproced.Id_Procedimiento = g_procedimiento.Id)     \nINNER JOIN ingreso  ON (f_ordenes.Id_Ingreso = ingreso.Id) \nINNER JOIN `f_empresacontxconvenio`  ON (f_empresacontxconvenio.`Id` = ingreso.`Id_EmpresaContxConv`) \nINNER JOIN `g_usuario`  ON (`ingreso`.`Id_Usuario` = `g_usuario`.`Id_persona`) \nINNER JOIN `g_persona`  ON (`g_usuario`.`Id_persona` = `g_persona`.`Id`)\nINNER JOIN `g_municipio`  ON (`g_municipio`.`Id` = `g_persona`.`Id_Municipio`)    \nINNER JOIN `g_tipoedad`  ON (`g_persona`.`Id_TipoEdad` = `g_tipoedad`.`Id`)  \nINNER JOIN `g_tipoatencion`  ON (g_tipoatencion.`Id` = ingreso.`Id_TipoAtencion`)  \nLEFT JOIN `f_camas`  ON (f_camas.`Id` = ingreso.`Cama`) \nLEFT JOIN `f_unidadcama`  ON (f_camas.`Id_UnidadCamas` = f_unidadcama.`Id`) INNER JOIN  `l_recepcion` ON (l_recepcion.`Id_OrdenFacturac`=f_ordenes.`Id` AND f_ordenes.`Estado`=0) \nWHERE ( g_procedimiento.EsOdontologico=0 \nAND f_ordenes.EstadoRecep IN (1,2) AND f_ordenes.Estado =0 AND f_ordenes.FechaOrden >='" + xFechaI + "' AND f_ordenes.FechaOrden <='" + xFechaF + "')\nGROUP BY `g_municipio`.`Nbre` ASC";
        List<Object[]> list = this.jdbcTemplate.query(xsql, mapper);
        return list;
    }

    @Override // com.genoma.plus.dao.laboratorio.RecepcionStikerDAO
    public List<Object[]> ListMunicipiosRecepcionMunicipio(String xFechaF) {
        RowMapper mapper = (rs, rowNum) -> {
            Object[] fila = {rs.getString(1), rs.getString(2)};
            return fila;
        };
        String xsql = "SELECT  `g_municipio`.`Id`, `g_municipio`.`Nbre`\nFROM f_itemordenesproced \nINNER JOIN l_codigoprouni ON (f_itemordenesproced.Id_Procedimiento = l_codigoprouni.Id_Procedimiento) \nINNER JOIN f_ordenes ON (f_itemordenesproced.Id_Ordenes = f_ordenes.Id) \nINNER JOIN g_procedimiento ON (f_itemordenesproced.Id_Procedimiento = g_procedimiento.Id)     \nINNER JOIN ingreso  ON (f_ordenes.Id_Ingreso = ingreso.Id) \nINNER JOIN `f_empresacontxconvenio`  ON (f_empresacontxconvenio.`Id` = ingreso.`Id_EmpresaContxConv`) \nINNER JOIN `g_usuario`  ON (`ingreso`.`Id_Usuario` = `g_usuario`.`Id_persona`) \nINNER JOIN `g_persona`  ON (`g_usuario`.`Id_persona` = `g_persona`.`Id`)\nINNER JOIN `g_municipio`  ON (`g_municipio`.`Id` = `g_persona`.`Id_Municipio`)    \nINNER JOIN `g_tipoedad`  ON (`g_persona`.`Id_TipoEdad` = `g_tipoedad`.`Id`)  \nINNER JOIN `g_tipoatencion`  ON (g_tipoatencion.`Id` = ingreso.`Id_TipoAtencion`)  \nLEFT JOIN `f_camas`  ON (f_camas.`Id` = ingreso.`Cama`) \nLEFT JOIN `f_unidadcama`  ON (f_camas.`Id_UnidadCamas` = f_unidadcama.`Id`) INNER JOIN  `l_recepcion` ON (l_recepcion.`Id_OrdenFacturac`=f_ordenes.`Id` AND f_ordenes.`Estado`=0) \nWHERE ( g_procedimiento.EsOdontologico=0 \nAND f_ordenes.EstadoRecep IN (1,2) AND f_ordenes.Estado =0  AND f_ordenes.FechaOrden ='" + xFechaF + "')\nGROUP BY `g_municipio`.`Nbre` ASC";
        List<Object[]> list = this.jdbcTemplate.query(xsql, mapper);
        return list;
    }

    @Override // com.genoma.plus.dao.laboratorio.RecepcionStikerDAO
    public List<Object[]> ListRecepcionStikersBySedes(String xFechaI, String xFechaF, String sedes, String xBuscar, int opc) {
        RowMapper mapper = (rs, rowNum) -> {
            Object[] fila = {Long.valueOf(rs.getLong("IdRecepcion")), rs.getString("documento"), rs.getString("NUsuario"), rs.getString("sede"), true, rs.getString(5), Long.valueOf(rs.getLong("idRecepcion"))};
            return fila;
        };
        String sql = "";
        if (opc == 0) {
            sql = "SELECT l_recepcion.`Id` IdRecepcion, concat(g_persona.Id_TipoIdentificacion, '_', g_persona.NoDocumento) documento, CONCAT(g_persona.`Apellido1`,' ',g_persona.`Apellido2`,' ',g_persona.`Nombre1`,' ',g_persona.`Nombre2`) AS NUsuario, `gs`.`Nbre` AS sede, l_recepcion.ImpresionStiker, f_ordenes.Id idRecepcion \nFROM f_itemordenesproced \nINNER JOIN l_codigoprouni ON (f_itemordenesproced.Id_Procedimiento = l_codigoprouni.Id_Procedimiento) \nINNER JOIN f_ordenes ON (f_itemordenesproced.Id_Ordenes = f_ordenes.Id) \nINNER JOIN g_procedimiento ON (f_itemordenesproced.Id_Procedimiento = g_procedimiento.Id)     \nINNER JOIN ingreso  ON (f_ordenes.Id_Ingreso = ingreso.Id) \nINNER JOIN `f_empresacontxconvenio`  ON (f_empresacontxconvenio.`Id` = ingreso.`Id_EmpresaContxConv`) \nINNER JOIN `g_usuario`  ON (`ingreso`.`Id_Usuario` = `g_usuario`.`Id_persona`) \nINNER JOIN `g_persona`  ON (`g_usuario`.`Id_persona` = `g_persona`.`Id`)\nINNER JOIN g_sedes gs   ON (`gs`.`Id` = ingreso.Id_Sede )    \nINNER JOIN `g_tipoedad`  ON (`g_persona`.`Id_TipoEdad` = `g_tipoedad`.`Id`)  \nINNER JOIN `g_tipoatencion`  ON (g_tipoatencion.`Id` = ingreso.`Id_TipoAtencion`)  \nLEFT JOIN `f_camas`  ON (f_camas.`Id` = ingreso.`Cama`) \nLEFT JOIN `f_unidadcama`  ON (f_camas.`Id_UnidadCamas` = f_unidadcama.`Id`) INNER JOIN  `l_recepcion` ON (l_recepcion.`Id_OrdenFacturac`=f_ordenes.`Id` AND f_ordenes.`Estado`=0) \nWHERE ( g_procedimiento.EsOdontologico=0 \nAND f_ordenes.EstadoRecep IN (1,2) AND f_ordenes.Estado =0 AND (l_recepcion.`Id` LIKE '" + xBuscar + "%' OR CONCAT(g_persona.`Apellido1`,' ',g_persona.`Apellido2`,' ',g_persona.`Nombre1`,' ',g_persona.`Nombre2`) LIKE '" + xBuscar + "%') )\nGROUP BY f_ordenes.Id ORDER BY ingreso.HoraIngreso ASC, ingreso.FechaIngreso ASC";
        } else if (opc == 1) {
            String[] sedesArray = sedes.split(",");
            String sedesList = String.join(",", sedesArray);
            sql = "SELECT l_recepcion.`Id` IdRecepcion, concat(g_persona.Id_TipoIdentificacion, '_', g_persona.NoDocumento) documento, CONCAT(g_persona.`Apellido1`,' ',g_persona.`Apellido2`,' ',g_persona.`Nombre1`,' ',g_persona.`Nombre2`) AS NUsuario, `gs`.`Nbre` AS sede, l_recepcion.ImpresionStiker, f_ordenes.Id idRecepcion \nFROM f_itemordenesproced \nINNER JOIN l_codigoprouni ON (f_itemordenesproced.Id_Procedimiento = l_codigoprouni.Id_Procedimiento) \nINNER JOIN f_ordenes ON (f_itemordenesproced.Id_Ordenes = f_ordenes.Id) \nINNER JOIN g_procedimiento ON (f_itemordenesproced.Id_Procedimiento = g_procedimiento.Id)     \nINNER JOIN ingreso  ON (f_ordenes.Id_Ingreso = ingreso.Id) \nINNER JOIN `f_empresacontxconvenio`  ON (f_empresacontxconvenio.`Id` = ingreso.`Id_EmpresaContxConv`) \nINNER JOIN `g_usuario`  ON (`ingreso`.`Id_Usuario` = `g_usuario`.`Id_persona`) \nINNER JOIN `g_persona`  ON (`g_usuario`.`Id_persona` = `g_persona`.`Id`)\nINNER JOIN g_sedes gs   ON (`gs`.`Id` = ingreso.Id_Sede )    \nINNER JOIN `g_tipoedad`  ON (`g_persona`.`Id_TipoEdad` = `g_tipoedad`.`Id`)  \nINNER JOIN `g_tipoatencion`  ON (g_tipoatencion.`Id` = ingreso.`Id_TipoAtencion`)  \nLEFT JOIN `f_camas`  ON (f_camas.`Id` = ingreso.`Cama`) \nLEFT JOIN `f_unidadcama`  ON (f_camas.`Id_UnidadCamas` = f_unidadcama.`Id`) INNER JOIN  `l_recepcion` ON (l_recepcion.`Id_OrdenFacturac`=f_ordenes.`Id` AND f_ordenes.`Estado`=0) \nWHERE ( g_procedimiento.EsOdontologico=0 \nAND f_ordenes.EstadoRecep IN (1,2) AND f_ordenes.Estado =0 AND f_ordenes.FechaOrden >='" + xFechaI + "' AND f_ordenes.FechaOrden <='" + xFechaF + "' AND l_recepcion.Id_Sede  IN(" + sedesList + ") )\nGROUP BY f_ordenes.Id ORDER BY ingreso.HoraIngreso ASC, ingreso.FechaIngreso ASC";
        }
        List<Object[]> list = this.jdbcTemplate.query(sql, mapper);
        return list;
    }

    @Override // com.genoma.plus.dao.laboratorio.RecepcionStikerDAO
    public List<Object[]> ListRecepcionByRangos(Integer desde, Integer hasta) {
        RowMapper mapper = (rs, rowNum) -> {
            Object[] fila = {Long.valueOf(rs.getLong("IdRecepcion")), rs.getString("documento"), rs.getString("NUsuario"), rs.getString("sede"), true, rs.getString(5), Long.valueOf(rs.getLong("idRecepcion"))};
            return fila;
        };
        String sql = "SELECT l_recepcion.`Id` IdRecepcion, concat(g_persona.Id_TipoIdentificacion, '_', g_persona.NoDocumento) documento, CONCAT(g_persona.`Apellido1`,' ',g_persona.`Apellido2`,' ',g_persona.`Nombre1`,' ',g_persona.`Nombre2`) AS NUsuario, `gs`.`Nbre` AS sede, l_recepcion.ImpresionStiker, f_ordenes.Id idRecepcion \nFROM f_itemordenesproced \nINNER JOIN l_codigoprouni ON (f_itemordenesproced.Id_Procedimiento = l_codigoprouni.Id_Procedimiento) \nINNER JOIN f_ordenes ON (f_itemordenesproced.Id_Ordenes = f_ordenes.Id) \nINNER JOIN g_procedimiento ON (f_itemordenesproced.Id_Procedimiento = g_procedimiento.Id)     \nINNER JOIN ingreso  ON (f_ordenes.Id_Ingreso = ingreso.Id) \nINNER JOIN `f_empresacontxconvenio`  ON (f_empresacontxconvenio.`Id` = ingreso.`Id_EmpresaContxConv`) \nINNER JOIN `g_usuario`  ON (`ingreso`.`Id_Usuario` = `g_usuario`.`Id_persona`) \nINNER JOIN `g_persona`  ON (`g_usuario`.`Id_persona` = `g_persona`.`Id`)\nINNER JOIN g_sedes gs   ON (`gs`.`Id` = ingreso.Id_Sede )      \nINNER JOIN `g_tipoedad`  ON (`g_persona`.`Id_TipoEdad` = `g_tipoedad`.`Id`)  \nINNER JOIN `g_tipoatencion`  ON (g_tipoatencion.`Id` = ingreso.`Id_TipoAtencion`)  \nLEFT JOIN `f_camas`  ON (f_camas.`Id` = ingreso.`Cama`) \nLEFT JOIN `f_unidadcama`  ON (f_camas.`Id_UnidadCamas` = f_unidadcama.`Id`) INNER JOIN  `l_recepcion` ON (l_recepcion.`Id_OrdenFacturac`=f_ordenes.`Id` AND f_ordenes.`Estado`=0) \nWHERE ( g_procedimiento.EsOdontologico=0 \nAND f_ordenes.EstadoRecep IN (1,2) AND f_ordenes.Estado =0 AND l_recepcion.Id BETWEEN '" + desde + "' and '" + hasta + "')\nGROUP BY f_ordenes.Id ORDER BY ingreso.HoraIngreso ASC, ingreso.FechaIngreso ASC";
        List<Object[]> list = this.jdbcTemplate.query(sql, mapper);
        return list;
    }

    @Override // com.genoma.plus.dao.laboratorio.RecepcionStikerDAO
    public List<Object[]> ListRecepcionStikersBySedesAndArea(String xFechaI, String xFechaF, String sedes, String xBuscar, int opc, String xidarea) {
        RowMapper mapper = (rs, rowNum) -> {
            Object[] fila = {Long.valueOf(rs.getLong("IdRecepcion")), rs.getString("documento"), rs.getString("NUsuario"), rs.getString("sede"), true, rs.getString(5), Long.valueOf(rs.getLong("idOrdenF")), rs.getString("nombreArea")};
            return fila;
        };
        StringBuilder sql = new StringBuilder();
        if (opc == 0) {
            sql.append("SELECT l_recepcion.`Id` IdRecepcion, concat(g_persona.Id_TipoIdentificacion, '_', g_persona.NoDocumento) documento, CONCAT(g_persona.`Apellido1`,' ',g_persona.`Apellido2`,' ',g_persona.`Nombre1`,' ',g_persona.`Nombre2`) AS NUsuario, `gs`.`Nbre` AS sede, l_recepcion.ImpresionStiker, f_ordenes.Id idOrdenF  , l_areas.`Nbre` AS nombreArea \nFROM f_itemordenesproced \nINNER JOIN l_codigoprouni ON (f_itemordenesproced.Id_Procedimiento = l_codigoprouni.Id_Procedimiento) \nINNER JOIN f_ordenes ON (f_itemordenesproced.Id_Ordenes = f_ordenes.Id) \nINNER JOIN g_procedimiento ON (f_itemordenesproced.Id_Procedimiento = g_procedimiento.Id)   INNER JOIN `l_areas` ON    g_procedimiento.`Id_Area`=l_areas.`Id`  \nINNER JOIN ingreso  ON (f_ordenes.Id_Ingreso = ingreso.Id) \nINNER JOIN `f_empresacontxconvenio`  ON (f_empresacontxconvenio.`Id` = ingreso.`Id_EmpresaContxConv`) \nINNER JOIN `g_usuario`  ON (`ingreso`.`Id_Usuario` = `g_usuario`.`Id_persona`) \nINNER JOIN `g_persona`  ON (`g_usuario`.`Id_persona` = `g_persona`.`Id`)\nINNER JOIN g_sedes gs   ON (`gs`.`Id` = ingreso.Id_Sede )    \nINNER JOIN `g_tipoedad`  ON (`g_persona`.`Id_TipoEdad` = `g_tipoedad`.`Id`)  \nINNER JOIN `g_tipoatencion`  ON (g_tipoatencion.`Id` = ingreso.`Id_TipoAtencion`)  \nLEFT JOIN `f_camas`  ON (f_camas.`Id` = ingreso.`Cama`) \nLEFT JOIN `f_unidadcama`  ON (f_camas.`Id_UnidadCamas` = f_unidadcama.`Id`) INNER JOIN  `l_recepcion` ON (l_recepcion.`Id_OrdenFacturac`=f_ordenes.`Id` AND f_ordenes.`Estado`=0) \nWHERE ( g_procedimiento.EsOdontologico=0 \nAND f_ordenes.EstadoRecep IN (1,2)  AND f_ordenes.Estado =0 AND (l_recepcion.`Id` LIKE '" + xBuscar + "%' OR CONCAT(g_persona.`Apellido1`,' ',g_persona.`Apellido2`,' ',g_persona.`Nombre1`,' ',g_persona.`Nombre2`) LIKE '" + xBuscar + "%') )\nGROUP BY f_ordenes.Id ORDER BY ingreso.HoraIngreso ASC, ingreso.FechaIngreso ASC");
        } else if (opc == 1) {
            sql.append("SELECT l_recepcion.`Id` IdRecepcion, concat(g_persona.Id_TipoIdentificacion, '_', g_persona.NoDocumento) documento, CONCAT(g_persona.`Apellido1`,' ',g_persona.`Apellido2`,' ',g_persona.`Nombre1`,' ',g_persona.`Nombre2`) AS NUsuario, `gs`.`Nbre` AS sede, l_recepcion.ImpresionStiker, f_ordenes.Id idOrdenF , l_areas.`Nbre` AS nombreArea \nFROM f_itemordenesproced \nINNER JOIN l_codigoprouni ON (f_itemordenesproced.Id_Procedimiento = l_codigoprouni.Id_Procedimiento) \nINNER JOIN f_ordenes ON (f_itemordenesproced.Id_Ordenes = f_ordenes.Id) \nINNER JOIN g_procedimiento ON (f_itemordenesproced.Id_Procedimiento = g_procedimiento.Id)    INNER JOIN `l_areas` ON    g_procedimiento.`Id_Area`=l_areas.`Id`  \nINNER JOIN ingreso  ON (f_ordenes.Id_Ingreso = ingreso.Id) \nINNER JOIN `f_empresacontxconvenio`  ON (f_empresacontxconvenio.`Id` = ingreso.`Id_EmpresaContxConv`) \nINNER JOIN `g_usuario`  ON (`ingreso`.`Id_Usuario` = `g_usuario`.`Id_persona`) \nINNER JOIN `g_persona`  ON (`g_usuario`.`Id_persona` = `g_persona`.`Id`)\nINNER JOIN g_sedes gs   ON (`gs`.`Id` = ingreso.Id_Sede )    \nINNER JOIN `g_tipoedad`  ON (`g_persona`.`Id_TipoEdad` = `g_tipoedad`.`Id`)  \nINNER JOIN `g_tipoatencion`  ON (g_tipoatencion.`Id` = ingreso.`Id_TipoAtencion`)  \nLEFT JOIN `f_camas`  ON (f_camas.`Id` = ingreso.`Cama`) \nLEFT JOIN `f_unidadcama`  ON (f_camas.`Id_UnidadCamas` = f_unidadcama.`Id`) INNER JOIN  `l_recepcion` ON (l_recepcion.`Id_OrdenFacturac`=f_ordenes.`Id` AND f_ordenes.`Estado`=0) \nWHERE ( g_procedimiento.EsOdontologico=0 \nAND f_ordenes.EstadoRecep IN (1,2) AND l_areas.Id ='" + xidarea + "' AND f_ordenes.Estado =0 AND f_ordenes.FechaOrden >='" + xFechaI + "' AND f_ordenes.FechaOrden <='" + xFechaF + "'");
            if (sedes != null && !sedes.isEmpty()) {
                String[] sedesArray = sedes.split(",");
                String sedesList = String.join(",", sedesArray);
                sql.append("AND l_recepcion.Id_Sede  IN(" + sedesList + ")\n");
            }
            sql.append(")\nGROUP BY f_ordenes.Id ORDER BY ingreso.HoraIngreso ASC, ingreso.FechaIngreso ASC");
        }
        List<Object[]> list = this.jdbcTemplate.query(sql.toString(), mapper);
        return list;
    }

    @Override // com.genoma.plus.dao.laboratorio.RecepcionStikerDAO
    public List<Object[]> ListRecepcionStikersCitologiaBySedes(String xFechaI, String xFechaF, String sedes, String xBuscar, int opc) {
        RowMapper mapper = (rs, rowNum) -> {
            Object[] fila = {Long.valueOf(rs.getLong("idCosecutivo")), rs.getString("documento"), rs.getString("NUsuario"), rs.getString("sede"), true, rs.getString(5), Long.valueOf(rs.getLong("idRecepcion")), Long.valueOf(rs.getLong("idOrden"))};
            return fila;
        };
        StringBuilder sql = new StringBuilder();
        if (opc == 0) {
            sql.append("SELECT CONCAT(rc.Ano,rc.Id_Consecutivo) idCosecutivo, concat(g_persona.Id_TipoIdentificacion, '_', g_persona.NoDocumento) documento, CONCAT(g_persona.`Apellido1`,' ',g_persona.`Apellido2`,' ',g_persona.`Nombre1`,' ',g_persona.`Nombre2`) AS NUsuario, `gs`.`Nbre` AS sede, l_recepcion.ImpresionStiker, l_recepcion.Id idRecepcion, f_ordenes.Id idOrden\nFROM f_itemordenesproced \nINNER JOIN l_codigoprouni ON (f_itemordenesproced.Id_Procedimiento = l_codigoprouni.Id_Procedimiento) \nINNER JOIN f_ordenes ON (f_itemordenesproced.Id_Ordenes = f_ordenes.Id) \nINNER JOIN g_procedimiento ON (f_itemordenesproced.Id_Procedimiento = g_procedimiento.Id)     \nINNER JOIN ingreso  ON (f_ordenes.Id_Ingreso = ingreso.Id) \nINNER JOIN `f_empresacontxconvenio`  ON (f_empresacontxconvenio.`Id` = ingreso.`Id_EmpresaContxConv`) \nINNER JOIN `g_usuario`  ON (`ingreso`.`Id_Usuario` = `g_usuario`.`Id_persona`) \nINNER JOIN `g_persona`  ON (`g_usuario`.`Id_persona` = `g_persona`.`Id`)\nINNER JOIN g_sedes gs   ON (`gs`.`Id` = ingreso.Id_Sede )    \nINNER JOIN `g_tipoedad`  ON (`g_persona`.`Id_TipoEdad` = `g_tipoedad`.`Id`)  \nINNER JOIN `g_tipoatencion`  ON (g_tipoatencion.`Id` = ingreso.`Id_TipoAtencion`)  \nLEFT JOIN `f_camas`  ON (f_camas.`Id` = ingreso.`Cama`) \nLEFT JOIN `f_unidadcama`  ON (f_camas.`Id_UnidadCamas` = f_unidadcama.`Id`)\nINNER JOIN  `l_recepcion` ON (l_recepcion.`Id_OrdenFacturac`=f_ordenes.`Id` AND f_ordenes.`Estado`=0) \nINNER JOIN  `l_recepcion_citologia` rc ON (rc.Id_Recepcion = l_recepcion.Id)\nWHERE ( g_procedimiento.EsOdontologico=0 \nAND f_ordenes.EstadoRecep IN (1,2) AND f_ordenes.Estado =0 AND (rc.Id_Consecutivo LIKE '" + xBuscar + "%' OR CONCAT(g_persona.`Apellido1`,' ',g_persona.`Apellido2`,' ',g_persona.`Nombre1`,' ',g_persona.`Nombre2`) LIKE '" + xBuscar + "%')  )\nGROUP BY f_ordenes.Id ORDER BY ingreso.HoraIngreso ASC, ingreso.FechaIngreso ASC");
        } else if (opc == 1) {
            sql.append("SELECT CONCAT(rc.Ano,rc.Id_Consecutivo) idCosecutivo, concat(g_persona.Id_TipoIdentificacion, '_', g_persona.NoDocumento) documento, CONCAT(g_persona.`Apellido1`,' ',g_persona.`Apellido2`,' ',g_persona.`Nombre1`,' ',g_persona.`Nombre2`) AS NUsuario, `gs`.`Nbre` AS sede, l_recepcion.ImpresionStiker, l_recepcion.Id idRecepcion, f_ordenes.Id idOrden\nFROM f_itemordenesproced \nINNER JOIN l_codigoprouni ON (f_itemordenesproced.Id_Procedimiento = l_codigoprouni.Id_Procedimiento) \nINNER JOIN f_ordenes ON (f_itemordenesproced.Id_Ordenes = f_ordenes.Id) \nINNER JOIN g_procedimiento ON (f_itemordenesproced.Id_Procedimiento = g_procedimiento.Id)     \nINNER JOIN ingreso  ON (f_ordenes.Id_Ingreso = ingreso.Id) \nINNER JOIN `f_empresacontxconvenio`  ON (f_empresacontxconvenio.`Id` = ingreso.`Id_EmpresaContxConv`) \nINNER JOIN `g_usuario`  ON (`ingreso`.`Id_Usuario` = `g_usuario`.`Id_persona`) \nINNER JOIN `g_persona`  ON (`g_usuario`.`Id_persona` = `g_persona`.`Id`)\nINNER JOIN g_sedes gs   ON (`gs`.`Id` = ingreso.Id_Sede )    \nINNER JOIN `g_tipoedad`  ON (`g_persona`.`Id_TipoEdad` = `g_tipoedad`.`Id`)  \nINNER JOIN `g_tipoatencion`  ON (g_tipoatencion.`Id` = ingreso.`Id_TipoAtencion`)  \nLEFT JOIN `f_camas`  ON (f_camas.`Id` = ingreso.`Cama`) \nLEFT JOIN `f_unidadcama`  ON (f_camas.`Id_UnidadCamas` = f_unidadcama.`Id`) INNER JOIN  `l_recepcion` ON (l_recepcion.`Id_OrdenFacturac`=f_ordenes.`Id` AND f_ordenes.`Estado`=0) \nINNER JOIN  `l_recepcion_citologia` rc ON (rc.Id_Recepcion = l_recepcion.Id)\nWHERE ( g_procedimiento.EsOdontologico=0 \nAND f_ordenes.EstadoRecep IN (1,2) AND f_ordenes.Estado =0\nAND f_ordenes.FechaOrden between '" + xFechaI + "' AND '" + xFechaF + "'\n");
            if (sedes != null && !sedes.isEmpty()) {
                String[] sedesArray = sedes.split(",");
                String sedesList = String.join(",", sedesArray);
                sql.append("AND l_recepcion.Id_Sede  IN(" + sedesList + ")\n");
            }
            sql.append(")\nGROUP BY f_ordenes.Id ORDER BY ingreso.HoraIngreso ASC, ingreso.FechaIngreso ASC");
        }
        List<Object[]> list = this.jdbcTemplate.query(sql.toString(), mapper);
        return list;
    }

    @Override // com.genoma.plus.dao.laboratorio.RecepcionStikerDAO
    public List<Object[]> ListRecepcionByRangosCitologia(Integer desde, Integer hasta) {
        RowMapper mapper = (rs, rowNum) -> {
            Object[] fila = {Long.valueOf(rs.getLong("idCosecutivo")), rs.getString("documento"), rs.getString("NUsuario"), rs.getString("sede"), true, rs.getString(5), Long.valueOf(rs.getLong("idRecepcion")), Long.valueOf(rs.getLong("idOrden"))};
            return fila;
        };
        String sql = "SELECT rc.Id_Consecutivo idCosecutivo, concat(g_persona.Id_TipoIdentificacion, '_', g_persona.NoDocumento) documento, CONCAT(g_persona.`Apellido1`,' ',g_persona.`Apellido2`,' ',g_persona.`Nombre1`,' ',g_persona.`Nombre2`) AS NUsuario, `gs`.`Nbre` AS sede, l_recepcion.ImpresionStiker, l_recepcion.Id idRecepcion, f_ordenes.Id idOrden\nFROM f_itemordenesproced \nINNER JOIN l_codigoprouni ON (f_itemordenesproced.Id_Procedimiento = l_codigoprouni.Id_Procedimiento) \nINNER JOIN f_ordenes ON (f_itemordenesproced.Id_Ordenes = f_ordenes.Id) \nINNER JOIN g_procedimiento ON (f_itemordenesproced.Id_Procedimiento = g_procedimiento.Id)     \nINNER JOIN ingreso  ON (f_ordenes.Id_Ingreso = ingreso.Id) \nINNER JOIN `f_empresacontxconvenio`  ON (f_empresacontxconvenio.`Id` = ingreso.`Id_EmpresaContxConv`) \nINNER JOIN `g_usuario`  ON (`ingreso`.`Id_Usuario` = `g_usuario`.`Id_persona`) \nINNER JOIN `g_persona`  ON (`g_usuario`.`Id_persona` = `g_persona`.`Id`)\nINNER JOIN g_sedes gs   ON (`gs`.`Id` = ingreso.Id_Sede )      \nINNER JOIN `g_tipoedad`  ON (`g_persona`.`Id_TipoEdad` = `g_tipoedad`.`Id`)  \nINNER JOIN `g_tipoatencion`  ON (g_tipoatencion.`Id` = ingreso.`Id_TipoAtencion`)  \nLEFT JOIN `f_camas`  ON (f_camas.`Id` = ingreso.`Cama`) \nLEFT JOIN `f_unidadcama`  ON (f_camas.`Id_UnidadCamas` = f_unidadcama.`Id`) INNER JOIN  `l_recepcion` ON (l_recepcion.`Id_OrdenFacturac`=f_ordenes.`Id` AND f_ordenes.`Estado`=0) \nINNER JOIN  `l_recepcion_citologia` rc ON (rc.Id_Recepcion = l_recepcion.Id)\nWHERE ( g_procedimiento.EsOdontologico=0 \nAND f_ordenes.EstadoRecep IN (1,2) AND f_ordenes.Estado =0 AND rc.Id_Consecutivo BETWEEN '" + desde + "' and '" + hasta + "')\nGROUP BY f_ordenes.Id ORDER BY ingreso.HoraIngreso ASC, ingreso.FechaIngreso ASC";
        List<Object[]> list = this.jdbcTemplate.query(sql, mapper);
        return list;
    }
}
