package Mantenimiento;

import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/* JADX INFO: loaded from: GenomaP.jar:Mantenimiento/formato5W1H.class */
public class formato5W1H extends JInternalFrame {
    private ButtonGroup buttonGroup1;
    private JComboBox jComboBox1;
    private JComboBox jComboBox3;
    private JComboBox jComboBox4;
    private JDateChooser jDateChooser1;
    private JDateChooser jDateChooser2;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JRadioButton jRadioButton1;
    private JRadioButton jRadioButton2;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JScrollPane jScrollPane3;
    private JScrollPane jScrollPane4;
    private JSpinner jSpinner1;
    private JTable jTable1;
    private JTextArea jTextArea1;
    private JTextArea jTextArea2;
    private JTextArea jTextArea3;
    private JTextField txtreporte;

    public formato5W1H() {
        initComponents();
    }

    /* JADX WARN: Type inference failed for: r3v69, types: [java.lang.Object[], java.lang.Object[][]] */
    private void initComponents() {
        this.buttonGroup1 = new ButtonGroup();
        this.jScrollPane1 = new JScrollPane();
        this.jTextArea1 = new JTextArea();
        this.jScrollPane2 = new JScrollPane();
        this.jTextArea2 = new JTextArea();
        this.jScrollPane3 = new JScrollPane();
        this.jTextArea3 = new JTextArea();
        this.jDateChooser1 = new JDateChooser();
        this.jPanel2 = new JPanel();
        this.jRadioButton2 = new JRadioButton();
        this.jRadioButton1 = new JRadioButton();
        this.jLabel1 = new JLabel();
        this.jLabel2 = new JLabel();
        this.jDateChooser2 = new JDateChooser();
        this.jSpinner1 = new JSpinner();
        this.jComboBox1 = new JComboBox();
        this.jComboBox3 = new JComboBox();
        this.txtreporte = new JTextField();
        this.jComboBox4 = new JComboBox();
        this.jPanel1 = new JPanel();
        this.jScrollPane4 = new JScrollPane();
        this.jTable1 = new JTable();
        setTitle("FICHA 5W1H");
        setFrameIcon(new ImageIcon(getClass().getResource("/Imagenes/genomap.png")));
        getContentPane().setLayout(new AbsoluteLayout());
        this.jTextArea1.setColumns(20);
        this.jTextArea1.setFont(new Font("Arial", 1, 12));
        this.jTextArea1.setRows(5);
        this.jTextArea1.setBorder(BorderFactory.createTitledBorder((Border) null, "QUE", 0, 0, new Font("Arial", 1, 14), new Color(255, 0, 0)));
        this.jScrollPane1.setViewportView(this.jTextArea1);
        getContentPane().add(this.jScrollPane1, new AbsoluteConstraints(20, 90, 230, -1));
        this.jTextArea2.setColumns(20);
        this.jTextArea2.setFont(new Font("Arial", 1, 12));
        this.jTextArea2.setRows(5);
        this.jTextArea2.setBorder(BorderFactory.createTitledBorder((Border) null, "COMO", 0, 0, new Font("Arial", 1, 14), new Color(255, 0, 0)));
        this.jScrollPane2.setViewportView(this.jTextArea2);
        getContentPane().add(this.jScrollPane2, new AbsoluteConstraints(500, 90, 230, -1));
        this.jTextArea3.setColumns(20);
        this.jTextArea3.setFont(new Font("Arial", 1, 12));
        this.jTextArea3.setRows(5);
        this.jTextArea3.setBorder(BorderFactory.createTitledBorder((Border) null, "PARA QUE", 0, 0, new Font("Arial", 1, 14), new Color(255, 0, 0)));
        this.jScrollPane3.setViewportView(this.jTextArea3);
        getContentPane().add(this.jScrollPane3, new AbsoluteConstraints(260, 90, 230, -1));
        this.jDateChooser1.setBorder(BorderFactory.createTitledBorder((Border) null, "Cuando", 0, 0, new Font("Arial", 1, 12), new Color(0, 0, 255)));
        this.jDateChooser1.setFont(new Font("Arial", 1, 12));
        getContentPane().add(this.jDateChooser1, new AbsoluteConstraints(600, 30, 130, -1));
        this.jPanel2.setBorder(BorderFactory.createTitledBorder((Border) null, "Requiere Seguimiento?", 0, 0, new Font("Arial", 1, 14), new Color(0, 102, 0)));
        this.jPanel2.setFont(new Font("Arial", 1, 12));
        this.jRadioButton2.setFont(new Font("Arial", 1, 12));
        this.jRadioButton2.setText("No");
        this.jRadioButton1.setFont(new Font("Arial", 1, 12));
        this.jRadioButton1.setText("Si");
        this.jLabel1.setFont(new Font("Arial", 1, 12));
        this.jLabel1.setText("Cuantos?");
        this.jLabel2.setFont(new Font("Arial", 1, 12));
        this.jLabel2.setText("Fecha Inicial");
        this.jDateChooser2.setFont(new Font("Arial", 1, 12));
        this.jSpinner1.setFont(new Font("Arial", 1, 12));
        GroupLayout jPanel2Layout = new GroupLayout(this.jPanel2);
        this.jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addComponent(this.jRadioButton1).addGap(10, 10, 10).addComponent(this.jRadioButton2).addGap(18, 18, 18).addComponent(this.jLabel1).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.jSpinner1, -2, 42, -2).addGap(18, 18, 18).addComponent(this.jLabel2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jDateChooser2, -2, 140, -2).addContainerGap(-1, 32767)));
        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jRadioButton1).addComponent(this.jRadioButton2).addComponent(this.jLabel1).addComponent(this.jLabel2).addComponent(this.jSpinner1, -2, 24, -2)).addComponent(this.jDateChooser2, -2, -1, -2)).addContainerGap(-1, 32767)));
        getContentPane().add(this.jPanel2, new AbsoluteConstraints(20, 200, 470, 60));
        this.jComboBox1.setFont(new Font("Arial", 1, 12));
        this.jComboBox1.setModel(new DefaultComboBoxModel(new String[]{"Acción Correctiva", "Acción Preventiva", "Acción de Mejora", "Tareas"}));
        this.jComboBox1.setBorder(BorderFactory.createTitledBorder((Border) null, "Tipo de Acción", 0, 0, new Font("Arial", 1, 12), new Color(0, 0, 255)));
        getContentPane().add(this.jComboBox1, new AbsoluteConstraints(20, 30, 150, -1));
        this.jComboBox3.setFont(new Font("Arial", 1, 12));
        this.jComboBox3.setModel(new DefaultComboBoxModel(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));
        this.jComboBox3.setBorder(BorderFactory.createTitledBorder((Border) null, "Quien", 0, 0, new Font("Arial", 1, 12), new Color(0, 0, 255)));
        getContentPane().add(this.jComboBox3, new AbsoluteConstraints(400, 30, 190, -1));
        this.txtreporte.setFont(new Font("Arial", 1, 18));
        this.txtreporte.setForeground(new Color(0, 102, 0));
        this.txtreporte.setBorder(BorderFactory.createTitledBorder((Border) null, "NºConsecutivo", 0, 0, new Font("Arial", 1, 12), new Color(0, 102, 0)));
        this.txtreporte.setEnabled(false);
        getContentPane().add(this.txtreporte, new AbsoluteConstraints(580, 200, 150, -1));
        this.jComboBox4.setFont(new Font("Arial", 1, 12));
        this.jComboBox4.setModel(new DefaultComboBoxModel(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));
        this.jComboBox4.setBorder(BorderFactory.createTitledBorder((Border) null, "Donde", 0, 0, new Font("Arial", 1, 12), new Color(0, 0, 255)));
        getContentPane().add(this.jComboBox4, new AbsoluteConstraints(180, 30, 210, -1));
        this.jPanel1.setBorder(BorderFactory.createTitledBorder((Border) null, "Ficha de Mejoramiento Continuo 5W1H", 0, 0, new Font("Arial", 1, 14), new Color(255, 0, 0)));
        this.jTable1.setFont(new Font("Arial", 1, 12));
        this.jTable1.setModel(new DefaultTableModel((Object[][]) new Object[]{new Object[]{null, null, null, null}, new Object[]{null, null, null, null}, new Object[]{null, null, null, null}, new Object[]{null, null, null, null}}, new String[]{"Title 1", "Title 2", "Title 3", "Title 4"}));
        this.jTable1.setRowHeight(25);
        this.jTable1.setSelectionBackground(new Color(255, 255, 255));
        this.jTable1.setSelectionForeground(new Color(255, 0, 0));
        this.jTable1.setSelectionMode(0);
        this.jScrollPane4.setViewportView(this.jTable1);
        GroupLayout jPanel1Layout = new GroupLayout(this.jPanel1);
        this.jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.jScrollPane4, -1, 708, 32767));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.jScrollPane4, GroupLayout.Alignment.TRAILING, -1, 284, 32767));
        getContentPane().add(this.jPanel1, new AbsoluteConstraints(10, 290, 720, 310));
        pack();
    }
}
