package com.genoma.plus.dao.impl.sgc;

import com.genoma.plus.dao.sgc.SC_EventoAdversoAnalisisDAO;
import com.genoma.plus.dto.gcuenta.GCGenericoDTO;
import com.genoma.plus.dto.sgc.SC_EventoAdversoAnalisisDTO;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.sql.DataSource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;

/* JADX INFO: loaded from: GenomaP.jar:com/genoma/plus/dao/impl/sgc/SC_EventoAdversoAnalisisDAOImpl.class */
public class SC_EventoAdversoAnalisisDAOImpl implements SC_EventoAdversoAnalisisDAO {
    private JdbcTemplate jdbcTemplate;

    public void setDataSource(DataSource dataSource) {
        this.jdbcTemplate = new JdbcTemplate(dataSource);
    }

    @Override // com.genoma.plus.dao.sgc.SC_EventoAdversoAnalisisDAO
    public List<SC_EventoAdversoAnalisisDTO> listEvento(int xtipo, String xbusqueda1, String xbusqueda2) {
        String sql = "";
        if (xtipo == 0) {
            sql = "SELECT `s_sgc_sc_evento_adverso`.`Id` , `s_sgc_sc_evento_adverso`.`FechaE` AS `Fecha` ,  `s_sgc_sc_evento_adverso`.`HoraE` AS Hora , CONCAT(`g_persona`.`Id_TipoIdentificacion` ,' ', `g_persona`.`NoDocumento`) AS `Documento`\n, CONCAT(`g_persona`.`Apellido1` ,' ', `g_persona`.`Apellido2` ,' ', `g_persona`.`Nombre1` ,' ', `g_persona`.`Nombre2`) AS `NUsuario`, `s_sgc_tipoproceso`.`Nbre` AS `ProcesoR`\n, `s_sgc_sc_tipoevento`.`Nbre` AS `TEvento`, `s_sgc_sc_tiporiesgo`.`Nbre` AS `NRiesgo`, `s_sgc_sc_evento_adverso`.`Descripcion`, CONCAT(`g_persona_1`.`Apellido1` ,' ', `g_persona_1`.`Apellido2` ,' ', `g_persona_1`.`Nombre1` ,' ', `g_persona_1`.`Nombre2`) AS `PReporta`\n, `rh_tipo_cargo`.`Nbre` AS `Cargo`, IFNULL(`s_sgc_sc_evento_adverso_analisis`.`Id`,0) AS `Id_Analisis`, IFNULL(`s_sgc_sc_evento_adverso_clasificacion`.`Id_Evento`,0) AS `Id_Clasificacion`, (DATEDIFF(ADDDATE(`s_sgc_sc_evento_adverso`.`FechaE`, INTERVAL `s_sgc_sc_tipoevento`.`NDiasV` DAY), (NOW()))) AS DVencimiento\n, `s_sgc_sc_tipoevento`.`NDiasV`, s_sgc_sc_evento_adverso.`Id_Ingreso` FROM `s_sgc_sc_evento_adverso` INNER JOIN `ingreso` ON (`s_sgc_sc_evento_adverso`.`Id_Ingreso` = `ingreso`.`Id`)\nINNER JOIN `s_sgc_tipoproceso` ON (`s_sgc_sc_evento_adverso`.`Id_TProceso` = `s_sgc_tipoproceso`.`Id`) INNER JOIN `g_usuario` \nON (`ingreso`.`Id_Usuario` = `g_usuario`.`Id_persona`) INNER JOIN `g_persona` ON (`g_usuario`.`Id_persona` = `g_persona`.`Id`) INNER JOIN `s_sgc_sc_triesgo_tevento` \nON (`s_sgc_sc_triesgo_tevento`.`Id` = `s_sgc_sc_evento_adverso`.`Id_TRiesgoE`) INNER JOIN `s_sgc_sc_tiporiesgo` ON (`s_sgc_sc_triesgo_tevento`.`Id_TipoRiesgo` = `s_sgc_sc_tiporiesgo`.`Id`)\nINNER JOIN `s_sgc_sc_tipoevento` ON (`s_sgc_sc_triesgo_tevento`.`Id_TipoEvento` = `s_sgc_sc_tipoevento`.`Id`) INNER JOIN `rh_tipo_persona_cargon` \nON (`rh_tipo_persona_cargon`.`Id` = `s_sgc_sc_evento_adverso`.`Id_PersonaR`) INNER JOIN `g_persona` AS `g_persona_1` ON (`rh_tipo_persona_cargon`.`Id_Persona` = `g_persona_1`.`Id`)\nINNER JOIN `rh_unidadf_cargo` ON (`rh_tipo_persona_cargon`.`Id_unidadf_cargo` = `rh_unidadf_cargo`.`Id`) INNER JOIN `rh_tipo_cargo` \nON (`rh_unidadf_cargo`.`Id_Cargo` = `rh_tipo_cargo`.`Id`) LEFT JOIN `s_sgc_sc_evento_adverso_analisis` ON (`s_sgc_sc_evento_adverso_analisis`.`Id_Evento` = `s_sgc_sc_evento_adverso`.`Id` AND `s_sgc_sc_evento_adverso_analisis`.`Estado`=1)\nLEFT JOIN `s_sgc_sc_evento_adverso_clasificacion` ON (`s_sgc_sc_evento_adverso_clasificacion`.`Id_Evento` = `s_sgc_sc_evento_adverso`.`Id`)WHERE (`s_sgc_sc_evento_adverso`.`Id_Anulado` =1) ORDER BY `s_sgc_sc_evento_adverso`.`FechaE` DESC, `NUsuario` ASC;";
        } else if (xtipo == 1) {
            sql = "SELECT `s_sgc_sc_evento_adverso`.`Id` , `s_sgc_sc_evento_adverso`.`FechaE` AS `Fecha` ,  `s_sgc_sc_evento_adverso`.`HoraE` AS Hora , CONCAT(`g_persona`.`Id_TipoIdentificacion` ,' ', `g_persona`.`NoDocumento`) AS `Documento`\n, CONCAT(`g_persona`.`Apellido1` ,' ', `g_persona`.`Apellido2` ,' ', `g_persona`.`Nombre1` ,' ', `g_persona`.`Nombre2`) AS `NUsuario`, `s_sgc_tipoproceso`.`Nbre` AS `ProcesoR`\n, `s_sgc_sc_tipoevento`.`Nbre` AS `TEvento`, `s_sgc_sc_tiporiesgo`.`Nbre` AS `NRiesgo`, `s_sgc_sc_evento_adverso`.`Descripcion`, CONCAT(`g_persona_1`.`Apellido1` ,' ', `g_persona_1`.`Apellido2` ,' ', `g_persona_1`.`Nombre1` ,' ', `g_persona_1`.`Nombre2`) AS `PReporta`\n, `rh_tipo_cargo`.`Nbre` AS `Cargo`, IFNULL(`s_sgc_sc_evento_adverso_analisis`.`Id`,0) AS `Id_Analisis`, IFNULL(`s_sgc_sc_evento_adverso_clasificacion`.`Id_Evento`,0) AS `Id_Clasificacion`, (DATEDIFF(ADDDATE(`s_sgc_sc_evento_adverso`.`FechaE`, INTERVAL `s_sgc_sc_tipoevento`.`NDiasV` DAY), (NOW()))) AS DVencimiento\n, `s_sgc_sc_tipoevento`.`NDiasV`, s_sgc_sc_evento_adverso.`Id_Ingreso` FROM `s_sgc_sc_evento_adverso` INNER JOIN `ingreso` ON (`s_sgc_sc_evento_adverso`.`Id_Ingreso` = `ingreso`.`Id`)\nINNER JOIN `s_sgc_tipoproceso` ON (`s_sgc_sc_evento_adverso`.`Id_TProceso` = `s_sgc_tipoproceso`.`Id`) INNER JOIN `g_usuario` \nON (`ingreso`.`Id_Usuario` = `g_usuario`.`Id_persona`) INNER JOIN `g_persona` ON (`g_usuario`.`Id_persona` = `g_persona`.`Id`) INNER JOIN `s_sgc_sc_triesgo_tevento` \nON (`s_sgc_sc_triesgo_tevento`.`Id` = `s_sgc_sc_evento_adverso`.`Id_TRiesgoE`) INNER JOIN `s_sgc_sc_tiporiesgo` ON (`s_sgc_sc_triesgo_tevento`.`Id_TipoRiesgo` = `s_sgc_sc_tiporiesgo`.`Id`)\nINNER JOIN `s_sgc_sc_tipoevento` ON (`s_sgc_sc_triesgo_tevento`.`Id_TipoEvento` = `s_sgc_sc_tipoevento`.`Id`) INNER JOIN `rh_tipo_persona_cargon` \nON (`rh_tipo_persona_cargon`.`Id` = `s_sgc_sc_evento_adverso`.`Id_PersonaR`) INNER JOIN `g_persona` AS `g_persona_1` ON (`rh_tipo_persona_cargon`.`Id_Persona` = `g_persona_1`.`Id`)\nINNER JOIN `rh_unidadf_cargo` ON (`rh_tipo_persona_cargon`.`Id_unidadf_cargo` = `rh_unidadf_cargo`.`Id`) INNER JOIN `rh_tipo_cargo` \nON (`rh_unidadf_cargo`.`Id_Cargo` = `rh_tipo_cargo`.`Id`) LEFT JOIN `s_sgc_sc_evento_adverso_analisis` ON (`s_sgc_sc_evento_adverso_analisis`.`Id_Evento` = `s_sgc_sc_evento_adverso`.`Id` AND `s_sgc_sc_evento_adverso_analisis`.`Estado`=1)\nLEFT JOIN `s_sgc_sc_evento_adverso_clasificacion` ON (`s_sgc_sc_evento_adverso_clasificacion`.`Id_Evento` = `s_sgc_sc_evento_adverso`.`Id`)\nWHERE (`s_sgc_sc_tipoevento`.`Nbre` LIKE '%" + xbusqueda1 + "%' AND`s_sgc_sc_evento_adverso`.`Id_Anulado` =1) ORDER BY `s_sgc_sc_evento_adverso`.`FechaE` DESC, `NUsuario` ASC;";
        } else if (xtipo == 2) {
            sql = "SELECT `s_sgc_sc_evento_adverso`.`Id` , `s_sgc_sc_evento_adverso`.`FechaE` AS `Fecha` ,  `s_sgc_sc_evento_adverso`.`HoraE` AS Hora , CONCAT(`g_persona`.`Id_TipoIdentificacion` ,' ', `g_persona`.`NoDocumento`) AS `Documento`\n, CONCAT(`g_persona`.`Apellido1` ,' ', `g_persona`.`Apellido2` ,' ', `g_persona`.`Nombre1` ,' ', `g_persona`.`Nombre2`) AS `NUsuario`, `s_sgc_tipoproceso`.`Nbre` AS `ProcesoR`\n, `s_sgc_sc_tipoevento`.`Nbre` AS `TEvento`, `s_sgc_sc_tiporiesgo`.`Nbre` AS `NRiesgo`, `s_sgc_sc_evento_adverso`.`Descripcion`, CONCAT(`g_persona_1`.`Apellido1` ,' ', `g_persona_1`.`Apellido2` ,' ', `g_persona_1`.`Nombre1` ,' ', `g_persona_1`.`Nombre2`) AS `PReporta`\n, `rh_tipo_cargo`.`Nbre` AS `Cargo`, IFNULL(`s_sgc_sc_evento_adverso_analisis`.`Id`,0) AS `Id_Analisis`, IFNULL(`s_sgc_sc_evento_adverso_clasificacion`.`Id_Evento`,0) AS `Id_Clasificacion`, (DATEDIFF(ADDDATE(`s_sgc_sc_evento_adverso`.`FechaE`, INTERVAL `s_sgc_sc_tipoevento`.`NDiasV` DAY), (NOW()))) AS DVencimiento\n, `s_sgc_sc_tipoevento`.`NDiasV`, s_sgc_sc_evento_adverso.`Id_Ingreso` FROM `s_sgc_sc_evento_adverso` INNER JOIN `ingreso` ON (`s_sgc_sc_evento_adverso`.`Id_Ingreso` = `ingreso`.`Id`)\nINNER JOIN `s_sgc_tipoproceso` ON (`s_sgc_sc_evento_adverso`.`Id_TProceso` = `s_sgc_tipoproceso`.`Id`) INNER JOIN `g_usuario` \nON (`ingreso`.`Id_Usuario` = `g_usuario`.`Id_persona`) INNER JOIN `g_persona` ON (`g_usuario`.`Id_persona` = `g_persona`.`Id`) INNER JOIN `s_sgc_sc_triesgo_tevento` \nON (`s_sgc_sc_triesgo_tevento`.`Id` = `s_sgc_sc_evento_adverso`.`Id_TRiesgoE`) INNER JOIN `s_sgc_sc_tiporiesgo` ON (`s_sgc_sc_triesgo_tevento`.`Id_TipoRiesgo` = `s_sgc_sc_tiporiesgo`.`Id`)\nINNER JOIN `s_sgc_sc_tipoevento` ON (`s_sgc_sc_triesgo_tevento`.`Id_TipoEvento` = `s_sgc_sc_tipoevento`.`Id`) INNER JOIN `rh_tipo_persona_cargon` \nON (`rh_tipo_persona_cargon`.`Id` = `s_sgc_sc_evento_adverso`.`Id_PersonaR`) INNER JOIN `g_persona` AS `g_persona_1` ON (`rh_tipo_persona_cargon`.`Id_Persona` = `g_persona_1`.`Id`)\nINNER JOIN `rh_unidadf_cargo` ON (`rh_tipo_persona_cargon`.`Id_unidadf_cargo` = `rh_unidadf_cargo`.`Id`) INNER JOIN `rh_tipo_cargo` \nON (`rh_unidadf_cargo`.`Id_Cargo` = `rh_tipo_cargo`.`Id`) LEFT JOIN `s_sgc_sc_evento_adverso_analisis` ON (`s_sgc_sc_evento_adverso_analisis`.`Id_Evento` = `s_sgc_sc_evento_adverso`.`Id` AND `s_sgc_sc_evento_adverso_analisis`.`Estado`=1)\nLEFT JOIN `s_sgc_sc_evento_adverso_clasificacion` ON (`s_sgc_sc_evento_adverso_clasificacion`.`Id_Evento` = `s_sgc_sc_evento_adverso`.`Id`)\nWHERE ( `g_persona`.`NoDocumento` LIKE '" + xbusqueda1 + "%' AND`s_sgc_sc_evento_adverso`.`Id_Anulado` =1) ORDER BY `s_sgc_sc_evento_adverso`.`FechaE` DESC, `NUsuario` ASC;";
        } else if (xtipo == 3) {
            sql = "SELECT `s_sgc_sc_evento_adverso`.`Id` , `s_sgc_sc_evento_adverso`.`FechaE` AS `Fecha` ,  `s_sgc_sc_evento_adverso`.`HoraE` AS Hora , CONCAT(`g_persona`.`Id_TipoIdentificacion` ,' ', `g_persona`.`NoDocumento`) AS `Documento`\n, CONCAT(`g_persona`.`Apellido1` ,' ', `g_persona`.`Apellido2` ,' ', `g_persona`.`Nombre1` ,' ', `g_persona`.`Nombre2`) AS `NUsuario`, `s_sgc_tipoproceso`.`Nbre` AS `ProcesoR`\n, `s_sgc_sc_tipoevento`.`Nbre` AS `TEvento`, `s_sgc_sc_tiporiesgo`.`Nbre` AS `NRiesgo`, `s_sgc_sc_evento_adverso`.`Descripcion`, CONCAT(`g_persona_1`.`Apellido1` ,' ', `g_persona_1`.`Apellido2` ,' ', `g_persona_1`.`Nombre1` ,' ', `g_persona_1`.`Nombre2`) AS `PReporta`\n, `rh_tipo_cargo`.`Nbre` AS `Cargo`, IFNULL(`s_sgc_sc_evento_adverso_analisis`.`Id`,0) AS `Id_Analisis`, IFNULL(`s_sgc_sc_evento_adverso_clasificacion`.`Id_Evento`,0) AS `Id_Clasificacion`, (DATEDIFF(ADDDATE(`s_sgc_sc_evento_adverso`.`FechaE`, INTERVAL `s_sgc_sc_tipoevento`.`NDiasV` DAY), (NOW()))) AS DVencimiento\n, `s_sgc_sc_tipoevento`.`NDiasV`, s_sgc_sc_evento_adverso.`Id_Ingreso` FROM `s_sgc_sc_evento_adverso` INNER JOIN `ingreso` ON (`s_sgc_sc_evento_adverso`.`Id_Ingreso` = `ingreso`.`Id`)\nINNER JOIN `s_sgc_tipoproceso` ON (`s_sgc_sc_evento_adverso`.`Id_TProceso` = `s_sgc_tipoproceso`.`Id`) INNER JOIN `g_usuario` \nON (`ingreso`.`Id_Usuario` = `g_usuario`.`Id_persona`) INNER JOIN `g_persona` ON (`g_usuario`.`Id_persona` = `g_persona`.`Id`) INNER JOIN `s_sgc_sc_triesgo_tevento` \nON (`s_sgc_sc_triesgo_tevento`.`Id` = `s_sgc_sc_evento_adverso`.`Id_TRiesgoE`) INNER JOIN `s_sgc_sc_tiporiesgo` ON (`s_sgc_sc_triesgo_tevento`.`Id_TipoRiesgo` = `s_sgc_sc_tiporiesgo`.`Id`)\nINNER JOIN `s_sgc_sc_tipoevento` ON (`s_sgc_sc_triesgo_tevento`.`Id_TipoEvento` = `s_sgc_sc_tipoevento`.`Id`) INNER JOIN `rh_tipo_persona_cargon` \nON (`rh_tipo_persona_cargon`.`Id` = `s_sgc_sc_evento_adverso`.`Id_PersonaR`) INNER JOIN `g_persona` AS `g_persona_1` ON (`rh_tipo_persona_cargon`.`Id_Persona` = `g_persona_1`.`Id`)\nINNER JOIN `rh_unidadf_cargo` ON (`rh_tipo_persona_cargon`.`Id_unidadf_cargo` = `rh_unidadf_cargo`.`Id`) INNER JOIN `rh_tipo_cargo` \nON (`rh_unidadf_cargo`.`Id_Cargo` = `rh_tipo_cargo`.`Id`) LEFT JOIN `s_sgc_sc_evento_adverso_analisis` ON (`s_sgc_sc_evento_adverso_analisis`.`Id_Evento` = `s_sgc_sc_evento_adverso`.`Id` AND `s_sgc_sc_evento_adverso_analisis`.`Estado`=1)\nLEFT JOIN `s_sgc_sc_evento_adverso_clasificacion` ON (`s_sgc_sc_evento_adverso_clasificacion`.`Id_Evento` = `s_sgc_sc_evento_adverso`.`Id`)\nWHERE (s_sgc_sc_evento_adverso.FechaE >='" + xbusqueda1 + "' AND s_sgc_sc_evento_adverso.FechaE <='" + xbusqueda2 + "' AND`s_sgc_sc_evento_adverso`.`Id_Anulado` =1) ORDER BY `s_sgc_sc_evento_adverso`.`FechaE` DESC, `NUsuario` ASC;";
        } else if (xtipo == 4) {
            sql = "SELECT `s_sgc_sc_evento_adverso`.`Id` , `s_sgc_sc_evento_adverso`.`FechaE` AS `Fecha` ,  `s_sgc_sc_evento_adverso`.`HoraE` AS Hora , CONCAT(`g_persona`.`Id_TipoIdentificacion` ,' ', `g_persona`.`NoDocumento`) AS `Documento`\n, CONCAT(`g_persona`.`Apellido1` ,' ', `g_persona`.`Apellido2` ,' ', `g_persona`.`Nombre1` ,' ', `g_persona`.`Nombre2`) AS `NUsuario`, `s_sgc_tipoproceso`.`Nbre` AS `ProcesoR`\n, `s_sgc_sc_tipoevento`.`Nbre` AS `TEvento`, `s_sgc_sc_tiporiesgo`.`Nbre` AS `NRiesgo`, `s_sgc_sc_evento_adverso`.`Descripcion`, CONCAT(`g_persona_1`.`Apellido1` ,' ', `g_persona_1`.`Apellido2` ,' ', `g_persona_1`.`Nombre1` ,' ', `g_persona_1`.`Nombre2`) AS `PReporta`\n, `rh_tipo_cargo`.`Nbre` AS `Cargo`, IFNULL(`s_sgc_sc_evento_adverso_analisis`.`Id`,0) AS `Id_Analisis`, IFNULL(`s_sgc_sc_evento_adverso_clasificacion`.`Id_Evento`,0) AS `Id_Clasificacion`, (DATEDIFF(ADDDATE(`s_sgc_sc_evento_adverso`.`FechaE`, INTERVAL `s_sgc_sc_tipoevento`.`NDiasV` DAY), (NOW()))) AS DVencimiento\n, `s_sgc_sc_tipoevento`.`NDiasV`, s_sgc_sc_evento_adverso.`Id_Ingreso` FROM `s_sgc_sc_evento_adverso` INNER JOIN `ingreso` ON (`s_sgc_sc_evento_adverso`.`Id_Ingreso` = `ingreso`.`Id`)\nINNER JOIN `s_sgc_tipoproceso` ON (`s_sgc_sc_evento_adverso`.`Id_TProceso` = `s_sgc_tipoproceso`.`Id`) INNER JOIN `g_usuario` \nON (`ingreso`.`Id_Usuario` = `g_usuario`.`Id_persona`) INNER JOIN `g_persona` ON (`g_usuario`.`Id_persona` = `g_persona`.`Id`) INNER JOIN `s_sgc_sc_triesgo_tevento` \nON (`s_sgc_sc_triesgo_tevento`.`Id` = `s_sgc_sc_evento_adverso`.`Id_TRiesgoE`) INNER JOIN `s_sgc_sc_tiporiesgo` ON (`s_sgc_sc_triesgo_tevento`.`Id_TipoRiesgo` = `s_sgc_sc_tiporiesgo`.`Id`)\nINNER JOIN `s_sgc_sc_tipoevento` ON (`s_sgc_sc_triesgo_tevento`.`Id_TipoEvento` = `s_sgc_sc_tipoevento`.`Id`) INNER JOIN `rh_tipo_persona_cargon` \nON (`rh_tipo_persona_cargon`.`Id` = `s_sgc_sc_evento_adverso`.`Id_PersonaR`) INNER JOIN `g_persona` AS `g_persona_1` ON (`rh_tipo_persona_cargon`.`Id_Persona` = `g_persona_1`.`Id`)\nINNER JOIN `rh_unidadf_cargo` ON (`rh_tipo_persona_cargon`.`Id_unidadf_cargo` = `rh_unidadf_cargo`.`Id`) INNER JOIN `rh_tipo_cargo` \nON (`rh_unidadf_cargo`.`Id_Cargo` = `rh_tipo_cargo`.`Id`) LEFT JOIN `s_sgc_sc_evento_adverso_analisis` ON (`s_sgc_sc_evento_adverso_analisis`.`Id_Evento` = `s_sgc_sc_evento_adverso`.`Id` AND `s_sgc_sc_evento_adverso_analisis`.`Estado`=1)\nLEFT JOIN `s_sgc_sc_evento_adverso_clasificacion` ON (`s_sgc_sc_evento_adverso_clasificacion`.`Id_Evento` = `s_sgc_sc_evento_adverso`.`Id`)\nWHERE (`s_sgc_tipoproceso`.`Id` ='" + xbusqueda1 + "' AND`s_sgc_sc_evento_adverso`.`Id_Anulado` =1) ORDER BY `s_sgc_sc_evento_adverso`.`FechaE` DESC, `NUsuario` ASC;";
        }
        RowMapper rowMapper = new RowMapper() { // from class: com.genoma.plus.dao.impl.sgc.SC_EventoAdversoAnalisisDAOImpl.1
            public Object mapRow(ResultSet rs, int i) throws SQLException {
                SC_EventoAdversoAnalisisDTO xEvento = new SC_EventoAdversoAnalisisDTO();
                xEvento.setXCodEvent(rs.getInt("Id"));
                xEvento.setXFechaEvent(rs.getString("Fecha"));
                xEvento.setXHoraEvent(rs.getString("Hora"));
                xEvento.setXIdentificacion(rs.getString("Documento"));
                xEvento.setXNombre(rs.getString("NUsuario"));
                xEvento.setXProcesoR(rs.getString("ProcesoR"));
                xEvento.setXTipoEvento(rs.getString("TEvento"));
                xEvento.setXRiesgo(rs.getString("NRiesgo"));
                xEvento.setXDescripcion(rs.getString("Descripcion"));
                xEvento.setXPReporta(rs.getString("PReporta"));
                xEvento.setXCargo(rs.getString("Cargo"));
                xEvento.setXIdAnalisis(rs.getInt("Id_Analisis"));
                xEvento.setXIdClasificacion(rs.getInt("Id_Clasificacion"));
                xEvento.setDVencimiento(rs.getInt("DVencimiento"));
                xEvento.setNDiasV(rs.getInt("NDiasV"));
                xEvento.setXIdIngreso(rs.getInt("Id_Ingreso"));
                return xEvento;
            }
        };
        List<SC_EventoAdversoAnalisisDTO> lsTipo = this.jdbcTemplate.query(sql, rowMapper);
        return lsTipo;
    }

    @Override // com.genoma.plus.dao.sgc.SC_EventoAdversoAnalisisDAO
    public List<GCGenericoDTO> listaTProceso() {
        RowMapper mapper = new RowMapper() { // from class: com.genoma.plus.dao.impl.sgc.SC_EventoAdversoAnalisisDAOImpl.2
            public Object mapRow(ResultSet rs, int rowNum) throws SQLException {
                GCGenericoDTO g = new GCGenericoDTO();
                g.setId(rs.getInt("Id"));
                g.setNombre(rs.getString("Nbre"));
                return g;
            }
        };
        List<GCGenericoDTO> list = this.jdbcTemplate.query("SELECT `s_sgc_tipoproceso`.`Id` , `s_sgc_tipoproceso`.`Nbre` FROM `s_sgc_sc_evento_adverso` INNER JOIN `s_sgc_tipoproceso` ON (`s_sgc_sc_evento_adverso`.`Id_TProceso` = `s_sgc_tipoproceso`.`Id`)\nGROUP BY `s_sgc_tipoproceso`.`Id` ORDER BY `s_sgc_tipoproceso`.`Nbre` ASC;", mapper);
        return list;
    }
}
