jdbc.driverClassName=org.postgresql.Driver

#AMBIENTE DE PRODUCCION
#jdbc.url=jdbc:sqlserver://;serverName=192.168.30.212;databaseName=DGempres02



#AMBIENTE DE PRUEBA
jdbc.url=jdbc:postgresql://172.16.0.42:5432/GENOMA

jdbc.username=genoma

jdbc.password=genoma1
