jdbc.driverClassName=org.firebirdsql.jdbc.FBDriver
#SERVICIO MEDICO SAN IGNACION
#jdbc.url=jdbc:firebirdsql://190.0.18.122:3050/D:\\SIMEDI\\BASE\\SMSILAB.FDB?encoding=ISO8859_1
jdbc.url=jdbc:firebirdsql://192.168.0.2:3050/D:\\SIMEDI\\BASE\\SMSILAB.FDB?encoding=ISO8859_1
jdbc.username=BIOSYS
jdbc.password=b10syst3ms*