jdbc.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

#AMBIENTE DE PRUEBA
#jdbc.url=jdbc:sqlserver://;serverName=localhost;databaseName=MASTER
#jdbc.username=sa
#jdbc.password=yourStrong(!)Password

#PUERTO BERRIO
#jdbc.url=jdbc:sqlserver://;serverName=192.168.1.9;databaseName=CNTBERRIO
#jdbc.username=biomed
#jdbc.password=Biomed2020*

#BELEN DE UMBRIA
#jdbc.url=jdbc:sqlserver://;serverName=192.200.138.100;databaseName=HSJOSE
#jdbc.username=ADMIN
#jdbc.password=TRIACON

#SANTA ROSA DE CABAL
#jdbc.url=jdbc:sqlserver://;serverName=192.168.30.212;databaseName=DGempres02
#jdbc.url=jdbc:sqlserver://;serverName=192.168.30.212;databaseName=DGempres99
#jdbc.username=sa
#jdbc.password=Admin*84

#PEREIRA
jdbc.url=jdbc:sqlserver://192.168.0.98:1433;databaseName=dbBS1
jdbc.username=sa
jdbc.password=Hormiga1289

#jdbc.url=jdbc:sqlserver://;serverName=192.200.138.100;databaseName=HSJOSE
#jdbc.username=ADMIN
#jdbc.password=TRIACON

