url.facturadian=http://192.168.0.56:30095//facturas
url.notificacion.estado.facturadian=http://192.168.0.56:10080//rest//v1.0//status//event
url.leer.correo=http://192.168.0.56:30095//email

url.validacionlaboratorio=http://localhost:8080//validacion-administrativa
url.validacionlaboratorio.list=http://localhost:8080/list-infoResultado
url.validacionlaboratorio.save.list=http://localhost:8080/save-list-validacion-administrativa

#url.validacionlaboratorio.list=http://192.168.10.8:8080/list-infoResultado
