package Facturacion;

import Acceso.Principal;
import Utilidades.ConsultasMySQL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import org.quartz.Job;
import org.quartz.JobExecutionContext;
import org.quartz.JobExecutionException;

/* JADX INFO: loaded from: GenomaP.jar:Facturacion/TareaLiquidacion.class */
public class TareaLiquidacion implements Job {
    ConsultasMySQL xct = new ConsultasMySQL();

    public void execute(JobExecutionContext jec) throws JobExecutionException {
        if (mNumeroLiquidaciones() > 0) {
            Principal.btnCancelar.setIcon(new ImageIcon(getClass().getResource("/Imagenes/campana_alerta.gif")));
            Principal.btnCancelar.setText("" + mNumeroLiquidaciones());
        }
    }

    private int mNumeroLiquidaciones() {
        String sql;
        int xValor = 0;
        if (Principal.informacionIps.getNombreIps().equals("CLINICA OFTALMOLOGICA DAJUD SAS") || Principal.informacionIps.getNombreIps().equals("COD-OPTICA UT") || Principal.informacionIps.getNombreIps().equals("JAIME CESAR DAJUD FERNANDEZ")) {
            sql = "SELECT     ingreso.Id     ,\n ingreso.FechaIngreso     ,\n ingreso.Id_TipoAtencion     ,\n ingreso.Egreso     ,\n ingreso.Egreso_H     ,\n g_usuario.NoHistoria     ,\n g_tipoatencion.Nbre AS TipoAtencion      ,\n f_liquidacion.Id AS NID,\n CONCAT(g_persona.Apellido1,' ',g_persona.Apellido2,' ',g_persona.Nombre1,' ',g_persona.Nombre2) AS NombreUusario,\n h_atencion.Codigo_Dxp  ,\n f_empresacontxconvenio.Nbre AS Empresa,\n f_empresacontxconvenio.EsCapitado,\n h_egreso_atencion.FechaSO AS FechaE,\n h_egreso_atencion.HoraSO AS HoraE, IF( `ingreso_salida_administrativa`.`estado` IS  NULL, 0, 1) estadoSalidaAdministrativa\nFROM ingreso     \nINNER JOIN  g_usuario  ON (ingreso.Id_Usuario = g_usuario.Id_persona) \nINNER JOIN  f_empresacontxconvenio  ON (ingreso.Id_EmpresaContxConv = f_empresacontxconvenio.Id)\nLEFT JOIN f_liquidacion  ON f_liquidacion.Id_Ingreso= ingreso.Id AND f_liquidacion.Estado=0  \nLEFT JOIN h_egreso_atencion ON  h_egreso_atencion.Id_Ingreso =ingreso.Id   \n\tAND h_egreso_atencion.Id_Tipo =ingreso.Id_TipoAtencion \n\tAND h_egreso_atencion.Estado =1 \nINNER JOIN  g_tipoatencion  ON (ingreso.Id_TipoAtencion = g_tipoatencion.Id)     \nINNER JOIN g_persona ON (g_usuario.Id_persona= g_persona.Id)  \nINNER JOIN h_atencion ON (h_atencion.Id_Ingreso= ingreso.Id)  \nINNER JOIN`q_agendacx` ON (q_agendacx.`Id_Ingreso`= ingreso.Id)  \n LEFT JOIN  `ingreso_salida_administrativa` ON (`ingreso_salida_administrativa`.`idIngreso` = `ingreso`.`Id`) AND(`ingreso_salida_administrativa`.`estado`=1) \nWHERE   h_atencion.Codigo_Dxp<>'' and f_empresacontxconvenio.Id_GIps='" + Principal.informacionIps.getId() + "' and IF( `ingreso_salida_administrativa`.`estado` IS  NULL, 0, 1)=0  AND f_liquidacion.Id IS NULL  AND ingreso.`Estado`=0 ORDER BY FechaE DESC, HoraE DESC";
        } else if (Principal.informacionIps.getIdentificacion().equals("812005644")) {
            sql = "SELECT     ingreso.Id     ,\n ingreso.FechaIngreso     ,\n ingreso.Id_TipoAtencion     ,\n ingreso.Egreso     ,\n ingreso.Egreso_H     ,\n g_usuario.NoHistoria     ,\n g_tipoatencion.Nbre AS TipoAtencion      ,\n f_liquidacion.Id AS NID,\n CONCAT(g_persona.Apellido1,' ',g_persona.Apellido2,' ',g_persona.Nombre1,' ',g_persona.Nombre2) AS NombreUusario,\n h_atencion.Codigo_Dxp  ,\n f_empresacontxconvenio.Nbre AS Empresa,\n f_empresacontxconvenio.EsCapitado,\n h_egreso_atencion.FechaSO AS FechaE,\n h_egreso_atencion.HoraSO AS HoraE, IF( `ingreso_salida_administrativa`.`estado` IS  NULL, 0, 1) estadoSalidaAdministrativa\nFROM ingreso     \nINNER JOIN  g_usuario  ON (ingreso.Id_Usuario = g_usuario.Id_persona) \nINNER JOIN  f_empresacontxconvenio  ON (ingreso.Id_EmpresaContxConv = f_empresacontxconvenio.Id)\nLEFT JOIN f_liquidacion  ON f_liquidacion.Id_Ingreso= ingreso.Id AND f_liquidacion.Estado=0  \nLEFT JOIN h_egreso_atencion ON  h_egreso_atencion.Id_Ingreso =ingreso.Id   \n\tAND h_egreso_atencion.Id_Tipo =ingreso.Id_TipoAtencion \n\tAND h_egreso_atencion.Estado =1 \nINNER JOIN  g_tipoatencion  ON (ingreso.Id_TipoAtencion = g_tipoatencion.Id)     \nINNER JOIN g_persona ON (g_usuario.Id_persona= g_persona.Id)  \nINNER JOIN h_atencion ON (h_atencion.Id_Ingreso= ingreso.Id)  \n LEFT JOIN  `ingreso_salida_administrativa` ON (`ingreso_salida_administrativa`.`idIngreso` = `ingreso`.`Id`) AND(`ingreso_salida_administrativa`.`estado`=1) \nWHERE   h_atencion.Codigo_Dxp<>'' \n\tAND h_egreso_atencion.FechaSO IS NOT NULL \n\tAND h_egreso_atencion.`Id_Destino`<>3 AND ingreso.Id_TipoAtencion >1 \n\tAND f_liquidacion.Id IS NULL AND ingreso.`Estado`=0  and IF( `ingreso_salida_administrativa`.`estado` IS  NULL, 0, 1)=0 \n\tAND ingreso.Id_TipoAtencion IN(2,3) \n AND ingreso.FechaIngreso>='2017-06-01' \n ORDER BY FechaE DESC, HoraE DESC";
        } else if (Principal.informacionIps.getNombreIps().equals("EMPRESA SOCIAL DEL ESTADO CAMU DEL PRADO")) {
            sql = "SELECT     ingreso.Id     ,\n ingreso.FechaIngreso     ,\n ingreso.Id_TipoAtencion     ,\n ingreso.Egreso     ,\n ingreso.Egreso_H     ,\n g_usuario.NoHistoria     ,\n g_tipoatencion.Nbre AS TipoAtencion      ,\n f_liquidacion.Id AS NID,\n CONCAT(g_persona.Apellido1,' ',g_persona.Apellido2,' ',g_persona.Nombre1,' ',g_persona.Nombre2) AS NombreUusario,\n h_atencion.Codigo_Dxp  ,\n f_empresacontxconvenio.Nbre AS Empresa,\n f_empresacontxconvenio.EsCapitado,\n h_egreso_atencion.FechaSO AS FechaE,\n h_egreso_atencion.HoraSO AS HoraE,IFNULL(h_triage.`Clasificacion`, 0) triage, IF( `ingreso_salida_administrativa`.`estado` IS  NULL, 0, 1) estadoSalidaAdministrativa\nFROM ingreso     \nINNER JOIN  g_usuario  ON (ingreso.Id_Usuario = g_usuario.Id_persona) \nINNER JOIN  f_empresacontxconvenio  ON (ingreso.Id_EmpresaContxConv = f_empresacontxconvenio.Id)\nLEFT JOIN f_liquidacion  ON f_liquidacion.Id_Ingreso= ingreso.Id AND f_liquidacion.Estado=0  \nLEFT JOIN h_egreso_atencion ON  h_egreso_atencion.Id_Ingreso =ingreso.Id   \n\tAND h_egreso_atencion.Id_Tipo =ingreso.Id_TipoAtencion \n\tAND h_egreso_atencion.Estado =1 \nINNER JOIN  g_tipoatencion  ON (ingreso.Id_TipoAtencion = g_tipoatencion.Id)     \nINNER JOIN g_persona ON (g_usuario.Id_persona= g_persona.Id)  \nINNER JOIN h_atencion ON (h_atencion.Id_Ingreso= ingreso.Id) LEFT JOIN `h_triage` ON (h_triage.`IdIngreso`= ingreso.Id) AND (h_triage.`Estado`=0) \n LEFT JOIN  `ingreso_salida_administrativa` ON (`ingreso_salida_administrativa`.`idIngreso` = `ingreso`.`Id`) AND(`ingreso_salida_administrativa`.`estado`=1) \nWHERE   h_atencion.Codigo_Dxp<>'' \n AND h_egreso_atencion.`Id_Destino`<>3\tAND h_egreso_atencion.FechaSO IS NOT NULL \n\tAND ingreso.Id_TipoAtencion >1 \n\tAND f_liquidacion.Id IS NULL AND ingreso.`Estado`=0 AND ingreso.FechaIngreso>='2020-01-01' \n HAVING triage<4\tand estadoSalidaAdministrativa=0 ORDER BY FechaE DESC, HoraE DESC";
        } else if (Principal.informacionIps.getNombreIps().equals("CLINICA LAURELES PSIQUIATRAS ASOCIADOS I.P.S. S.A.S.") || Principal.informacionIps.getNombreIps().equals("UNION TEMPORAL CLINICA LAURELES")) {
            sql = "SELECT     ingreso.Id     ,\n ingreso.FechaIngreso     ,\n ingreso.Id_TipoAtencion     ,\n ingreso.Egreso     ,\n ingreso.Egreso_H     ,\n g_usuario.NoHistoria     ,\n g_tipoatencion.Nbre AS TipoAtencion      ,\n f_liquidacion.Id AS NID,\n CONCAT(g_persona.Apellido1,' ',g_persona.Apellido2,' ',g_persona.Nombre1,' ',g_persona.Nombre2) AS NombreUusario,\n h_atencion.Codigo_Dxp  ,\n f_empresacontxconvenio.Nbre AS Empresa,\n f_empresacontxconvenio.EsCapitado,\n h_egreso_atencion.FechaSO AS FechaE,\n h_egreso_atencion.HoraSO AS HoraE,IFNULL(h_triage.`Clasificacion`, 0) triage, IF( `ingreso_salida_administrativa`.`estado` IS  NULL, 0, 1) estadoSalidaAdministrativa\nFROM ingreso     \nINNER JOIN  g_usuario  ON (ingreso.Id_Usuario = g_usuario.Id_persona) \nINNER JOIN  f_empresacontxconvenio  ON (ingreso.Id_EmpresaContxConv = f_empresacontxconvenio.Id)\nLEFT JOIN f_liquidacion  ON f_liquidacion.Id_Ingreso= ingreso.Id AND f_liquidacion.Estado=0  \nLEFT JOIN h_egreso_atencion ON  h_egreso_atencion.Id_Ingreso =ingreso.Id   \n\tAND h_egreso_atencion.Id_Tipo =ingreso.Id_TipoAtencion \n\tAND h_egreso_atencion.Estado =1 \nINNER JOIN  g_tipoatencion  ON (ingreso.Id_TipoAtencion = g_tipoatencion.Id)     \nINNER JOIN g_persona ON (g_usuario.Id_persona= g_persona.Id)  \nINNER JOIN h_atencion ON (h_atencion.Id_Ingreso= ingreso.Id) LEFT JOIN `h_triage` ON (h_triage.`IdIngreso`= ingreso.Id) AND (h_triage.`Estado`=0) \n LEFT JOIN  `ingreso_salida_administrativa` ON (`ingreso_salida_administrativa`.`idIngreso` = `ingreso`.`Id`) AND(`ingreso_salida_administrativa`.`estado`=1) \nWHERE   h_atencion.Codigo_Dxp<>'' \nAND h_egreso_atencion.FechaSO IS NOT NULL \n\tAND ingreso.Id_TipoAtencion >1 \n\tAND f_liquidacion.Id IS NULL AND ingreso.`Estado`=0  \n HAVING triage<4\tand estadoSalidaAdministrativa=0 ORDER BY FechaE DESC, HoraE DESC";
        } else if (Principal.informacionIps.getNombreIps().equals("BIOMED VIDA IPS S.A.S")) {
            sql = "SELECT\n ingreso.Id     ,\n ingreso.FechaIngreso     ,\n ingreso.Id_TipoAtencion     ,\n ingreso.Egreso     ,\n ingreso.Egreso_H     ,\n g_usuario.NoHistoria     ,\n g_tipoatencion.Nbre AS TipoAtencion      ,\n IF(f_liquidacion.Id IS NULL, 0,f_liquidacion.Id)  AS NID,\n CONCAT(g_persona.Apellido1,' ',g_persona.Apellido2,' ',g_persona.Nombre1,' ',g_persona.Nombre2) AS NombreUusario,\n ingreso.`DxIngreso`,\n f_empresacontxconvenio.Nbre AS Empresa,\n f_empresacontxconvenio.EsCapitado,\n ingreso.`FechaIngreso` as FechaE ,\n 0 , \nIF(ingreso.`HoraIngreso` IS NULL,'', ingreso.`HoraIngreso`) AS HoraI,IF(ingreso.`HoraIngreso` IS NULL,'', ingreso.`HoraIngreso`) AS HoraE, \nIF( `ingreso_salida_administrativa`.`estado` IS  NULL, 0, 1) estadoSalidaAdministrativa \nFROM\n`g_usuario`\nINNER JOIN `g_persona`ON (`g_usuario`.`Id_persona` = `g_persona`.`Id`)\nINNER JOIN `ingreso` ON (`ingreso`.`Id_Usuario` = `g_persona`.`Id`)\nINNER JOIN  g_tipoatencion  ON (ingreso.Id_TipoAtencion = g_tipoatencion.Id) \nINNER JOIN  f_empresacontxconvenio  ON (ingreso.Id_EmpresaContxConv = f_empresacontxconvenio.Id)\nLEFT JOIN  `ingreso_salida_administrativa` ON (`ingreso_salida_administrativa`.`idIngreso` = `ingreso`.`Id`) AND(`ingreso_salida_administrativa`.`estado`=1) \nleft JOIN `f_liquidacion`    ON (`ingreso`.`Id` = `f_liquidacion`.`Id_Ingreso`)\nwhere  f_empresacontxconvenio.`Id` IN(49,8,100,119) and ingreso.`FechaIngreso`>='2023-08-24' and `f_liquidacion`.`Id_Ingreso` is null ;";
        } else {
            sql = "SELECT     ingreso.Id     ,\n ingreso.FechaIngreso     ,\n ingreso.Id_TipoAtencion     ,\n ingreso.Egreso     ,\n ingreso.Egreso_H     ,\n g_usuario.NoHistoria     ,\n g_tipoatencion.Nbre AS TipoAtencion      ,\n f_liquidacion.Id AS NID,\n CONCAT(g_persona.Apellido1,' ',g_persona.Apellido2,' ',g_persona.Nombre1,' ',g_persona.Nombre2) AS NombreUusario,\n h_atencion.Codigo_Dxp  ,\n f_empresacontxconvenio.Nbre AS Empresa,\n f_empresacontxconvenio.EsCapitado,\n h_egreso_atencion.FechaSO AS FechaE,\n h_egreso_atencion.HoraSO AS HoraE,IFNULL(h_triage.`Clasificacion`, 0) triage, IF( `ingreso_salida_administrativa`.`estado` IS  NULL, 0, 1) estadoSalidaAdministrativa\nFROM ingreso     \nINNER JOIN  g_usuario  ON (ingreso.Id_Usuario = g_usuario.Id_persona) \nINNER JOIN  f_empresacontxconvenio  ON (ingreso.Id_EmpresaContxConv = f_empresacontxconvenio.Id)\nLEFT JOIN f_liquidacion  ON f_liquidacion.Id_Ingreso= ingreso.Id AND f_liquidacion.Estado=0  \nLEFT JOIN h_egreso_atencion ON  h_egreso_atencion.Id_Ingreso =ingreso.Id   \n\tAND h_egreso_atencion.Id_Tipo =ingreso.Id_TipoAtencion \n\tAND h_egreso_atencion.Estado =1 \nINNER JOIN  g_tipoatencion  ON (ingreso.Id_TipoAtencion = g_tipoatencion.Id)     \nINNER JOIN g_persona ON (g_usuario.Id_persona= g_persona.Id)  \nINNER JOIN h_atencion ON (h_atencion.Id_Ingreso= ingreso.Id) LEFT JOIN `h_triage` ON (h_triage.`IdIngreso`= ingreso.Id) AND (h_triage.`Estado`=0) \n LEFT JOIN  `ingreso_salida_administrativa` ON (`ingreso_salida_administrativa`.`idIngreso` = `ingreso`.`Id`) AND(`ingreso_salida_administrativa`.`estado`=1) \nWHERE   h_atencion.Codigo_Dxp<>'' \n AND h_egreso_atencion.`Id_Destino`<>3\tAND h_egreso_atencion.FechaSO IS NOT NULL \n\tAND ingreso.Id_TipoAtencion >1 \n\tAND f_liquidacion.Id IS NULL AND ingreso.`Estado`=0  \n HAVING triage<4\tand estadoSalidaAdministrativa=0 ORDER BY FechaE DESC, HoraE DESC";
        }
        ResultSet xrs = this.xct.traerRs(sql);
        try {
            if (xrs.next()) {
                xrs.last();
                xValor = xrs.getRow();
            }
            xrs.close();
            this.xct.cerrarConexionBd();
        } catch (SQLException ex) {
            Logger.getLogger(TareaLiquidacion.class.getName()).log(Level.SEVERE, (String) null, (Throwable) ex);
        }
        return xValor;
    }
}
