package Historia;

import Acceso.Principal;
import Utilidades.ConsultasMySQL;
import Utilidades.Metodos;
import java.awt.Color;
import java.awt.Font;
import java.awt.Point;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/* JADX INFO: loaded from: GenomaP.jar:Historia/JIFAdultoJoven2.class */
public class JIFAdultoJoven2 extends JPanel {
    private Point posicion = new Point(3, 8);
    private Metodos xmt = new Metodos();
    private ConsultasMySQL xct = new ConsultasMySQL();
    private DefaultTableModel xmodelo;
    private Object[] xdato;
    private ButtonGroup Agua;
    private ButtonGroup Alcoho;
    private ButtonGroup Alimentacion;
    private ButtonGroup Amigos;
    private ButtonGroup Animo;
    private ButtonGroup Anticoncepcion;
    private ButtonGroup Apoyo;
    private ButtonGroup ApoyoSocial;
    private ButtonGroup Ciclo;
    private ButtonGroup Conduce;
    private ButtonGroup Desercion;
    private ButtonGroup Dismenorrea;
    private ButtonGroup EduNoFormal;
    private ButtonGroup Energia;
    private ButtonGroup EstMadre;
    private ButtonGroup EstPadre;
    private ButtonGroup EstPareja;
    private ButtonGroup Estudia;
    private ButtonGroup Fuma;
    private ButtonGroup Hacinamiento;
    private ButtonGroup ITS;
    private JComboBox JCBAceptacion;
    private JComboBox JCBRelSex;
    private JComboBox JCBRelSex1;
    private JComboBox JCBRelSex2;
    private JComboBox JCBTrabajo;
    private JComboBox JCPersepcion;
    private JPanel JPAnimo;
    private JPanel JPReferente;
    private JTextField JTFActividades;
    private JTextField JTFAprobado;
    private JTextField JTFCelPadre;
    private JTextField JTFComida;
    private JTextField JTFEdadInicio;
    private JTextField JTFEdadRel;
    private JTextField JTFEdadRel1;
    private JTextField JTFFechaMest;
    private JTextField JTFGrado;
    private JTextField JTFHoras;
    private JTextField JTFITS;
    private JTextField JTFInstitucion;
    private JTextField JTFProPadres;
    private JTextField JTFProPareja;
    private JTextField JTFRepetido;
    private JTextField JTFSustancias;
    private JTextField JTFTelPadre;
    private JTable JTHistorio;
    private ButtonGroup Mestruacion;
    private ButtonGroup Pareja;
    private ButtonGroup Peneana;
    private ButtonGroup Problemas;
    private ButtonGroup Suenio;
    private ButtonGroup Sustancias;
    private ButtonGroup TrabInfantil;
    private ButtonGroup TrabJuvenil;
    private ButtonGroup TrabMadre;
    private ButtonGroup TrabPadre;
    private ButtonGroup TrabPareja;
    private ButtonGroup TratamientoIts;
    private ButtonGroup Violencia;
    private ButtonGroup ViolenciaEsc;
    private JComboBox jComboBox1;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel jLabel13;
    private JLabel jLabel14;
    private JLabel jLabel15;
    private JLabel jLabel16;
    private JLabel jLabel17;
    private JLabel jLabel18;
    private JLabel jLabel19;
    private JLabel jLabel2;
    private JLabel jLabel20;
    private JLabel jLabel21;
    private JLabel jLabel22;
    private JLabel jLabel23;
    private JLabel jLabel24;
    private JLabel jLabel25;
    private JLabel jLabel26;
    private JLabel jLabel27;
    private JLabel jLabel28;
    private JLabel jLabel29;
    private JLabel jLabel3;
    private JLabel jLabel30;
    private JLabel jLabel31;
    private JLabel jLabel32;
    private JLabel jLabel33;
    private JLabel jLabel34;
    private JLabel jLabel35;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel9;
    private JPanel jPanel1;
    private JPanel jPanel10;
    private JPanel jPanel11;
    private JPanel jPanel12;
    private JPanel jPanel13;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JPanel jPanel5;
    private JPanel jPanel6;
    private JPanel jPanel7;
    private JPanel jPanel8;
    private JPanel jPanel9;
    private JRadioButton jRadioButton1;
    private JRadioButton jRadioButton10;
    private JRadioButton jRadioButton11;
    private JRadioButton jRadioButton12;
    private JRadioButton jRadioButton13;
    private JRadioButton jRadioButton14;
    private JRadioButton jRadioButton19;
    private JRadioButton jRadioButton2;
    private JRadioButton jRadioButton20;
    private JRadioButton jRadioButton21;
    private JRadioButton jRadioButton22;
    private JRadioButton jRadioButton23;
    private JRadioButton jRadioButton24;
    private JRadioButton jRadioButton25;
    private JRadioButton jRadioButton26;
    private JRadioButton jRadioButton27;
    private JRadioButton jRadioButton28;
    private JRadioButton jRadioButton29;
    private JRadioButton jRadioButton3;
    private JRadioButton jRadioButton30;
    private JRadioButton jRadioButton31;
    private JRadioButton jRadioButton32;
    private JRadioButton jRadioButton33;
    private JRadioButton jRadioButton34;
    private JRadioButton jRadioButton35;
    private JRadioButton jRadioButton36;
    private JRadioButton jRadioButton37;
    private JRadioButton jRadioButton38;
    private JRadioButton jRadioButton39;
    private JRadioButton jRadioButton4;
    private JRadioButton jRadioButton40;
    private JRadioButton jRadioButton41;
    private JRadioButton jRadioButton42;
    private JRadioButton jRadioButton43;
    private JRadioButton jRadioButton44;
    private JRadioButton jRadioButton45;
    private JRadioButton jRadioButton46;
    private JRadioButton jRadioButton47;
    private JRadioButton jRadioButton48;
    private JRadioButton jRadioButton49;
    private JRadioButton jRadioButton5;
    private JRadioButton jRadioButton50;
    private JRadioButton jRadioButton51;
    private JRadioButton jRadioButton52;
    private JRadioButton jRadioButton53;
    private JRadioButton jRadioButton54;
    private JRadioButton jRadioButton55;
    private JRadioButton jRadioButton56;
    private JRadioButton jRadioButton57;
    private JRadioButton jRadioButton58;
    private JRadioButton jRadioButton59;
    private JRadioButton jRadioButton6;
    private JRadioButton jRadioButton60;
    private JRadioButton jRadioButton61;
    private JRadioButton jRadioButton62;
    private JRadioButton jRadioButton63;
    private JRadioButton jRadioButton64;
    private JRadioButton jRadioButton65;
    private JRadioButton jRadioButton66;
    private JRadioButton jRadioButton67;
    private JRadioButton jRadioButton68;
    private JRadioButton jRadioButton69;
    private JRadioButton jRadioButton7;
    private JRadioButton jRadioButton70;
    private JRadioButton jRadioButton71;
    private JRadioButton jRadioButton72;
    private JRadioButton jRadioButton8;
    private JRadioButton jRadioButton9;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JTabbedPane jTabbedPane1;

    public JIFAdultoJoven2() {
        initComponents();
        mBuscaHistorico();
    }

    private void mLlenaComboChVi() {
    }

    private void mLlenaComboChConVi() {
    }

    /* JADX WARN: Type inference failed for: r3v499, types: [java.lang.Object[], java.lang.Object[][]] */
    private void initComponents() {
        this.EstPadre = new ButtonGroup();
        this.EstMadre = new ButtonGroup();
        this.EstPareja = new ButtonGroup();
        this.TrabPadre = new ButtonGroup();
        this.TrabMadre = new ButtonGroup();
        this.TrabPareja = new ButtonGroup();
        this.ApoyoSocial = new ButtonGroup();
        this.Energia = new ButtonGroup();
        this.Agua = new ButtonGroup();
        this.Hacinamiento = new ButtonGroup();
        this.Estudia = new ButtonGroup();
        this.Problemas = new ButtonGroup();
        this.ViolenciaEsc = new ButtonGroup();
        this.Desercion = new ButtonGroup();
        this.EduNoFormal = new ButtonGroup();
        this.TrabInfantil = new ButtonGroup();
        this.TrabJuvenil = new ButtonGroup();
        this.Pareja = new ButtonGroup();
        this.Violencia = new ButtonGroup();
        this.Amigos = new ButtonGroup();
        this.Suenio = new ButtonGroup();
        this.Alimentacion = new ButtonGroup();
        this.Fuma = new ButtonGroup();
        this.Alcoho = new ButtonGroup();
        this.Sustancias = new ButtonGroup();
        this.Conduce = new ButtonGroup();
        this.Mestruacion = new ButtonGroup();
        this.Ciclo = new ButtonGroup();
        this.Dismenorrea = new ButtonGroup();
        this.Peneana = new ButtonGroup();
        this.ITS = new ButtonGroup();
        this.TratamientoIts = new ButtonGroup();
        this.Anticoncepcion = new ButtonGroup();
        this.Animo = new ButtonGroup();
        this.Apoyo = new ButtonGroup();
        this.jTabbedPane1 = new JTabbedPane();
        this.jScrollPane1 = new JScrollPane();
        this.jPanel1 = new JPanel();
        this.jPanel3 = new JPanel();
        this.jPanel4 = new JPanel();
        this.jLabel1 = new JLabel();
        this.jRadioButton1 = new JRadioButton();
        this.jRadioButton2 = new JRadioButton();
        this.jLabel2 = new JLabel();
        this.jRadioButton3 = new JRadioButton();
        this.jRadioButton4 = new JRadioButton();
        this.jLabel3 = new JLabel();
        this.jRadioButton5 = new JRadioButton();
        this.jRadioButton6 = new JRadioButton();
        this.jPanel5 = new JPanel();
        this.jLabel4 = new JLabel();
        this.jRadioButton7 = new JRadioButton();
        this.jRadioButton8 = new JRadioButton();
        this.jLabel5 = new JLabel();
        this.jRadioButton9 = new JRadioButton();
        this.jRadioButton10 = new JRadioButton();
        this.jLabel6 = new JLabel();
        this.jRadioButton11 = new JRadioButton();
        this.jRadioButton12 = new JRadioButton();
        this.JTFProPadres = new JTextField();
        this.JTFProPareja = new JTextField();
        this.jLabel7 = new JLabel();
        this.jRadioButton13 = new JRadioButton();
        this.jRadioButton14 = new JRadioButton();
        this.JCPersepcion = new JComboBox();
        this.jPanel6 = new JPanel();
        this.jLabel9 = new JLabel();
        this.jRadioButton19 = new JRadioButton();
        this.jRadioButton20 = new JRadioButton();
        this.jLabel10 = new JLabel();
        this.jRadioButton21 = new JRadioButton();
        this.jRadioButton22 = new JRadioButton();
        this.jLabel11 = new JLabel();
        this.jRadioButton23 = new JRadioButton();
        this.jRadioButton24 = new JRadioButton();
        this.jPanel7 = new JPanel();
        this.jLabel12 = new JLabel();
        this.jRadioButton25 = new JRadioButton();
        this.jRadioButton26 = new JRadioButton();
        this.JTFInstitucion = new JTextField();
        this.jComboBox1 = new JComboBox();
        this.JTFGrado = new JTextField();
        this.JTFAprobado = new JTextField();
        this.jLabel13 = new JLabel();
        this.jRadioButton27 = new JRadioButton();
        this.jRadioButton28 = new JRadioButton();
        this.JTFRepetido = new JTextField();
        this.jLabel14 = new JLabel();
        this.jRadioButton29 = new JRadioButton();
        this.jRadioButton30 = new JRadioButton();
        this.jLabel15 = new JLabel();
        this.jRadioButton31 = new JRadioButton();
        this.jRadioButton32 = new JRadioButton();
        this.jLabel16 = new JLabel();
        this.jRadioButton33 = new JRadioButton();
        this.jRadioButton34 = new JRadioButton();
        this.jPanel8 = new JPanel();
        this.JCBTrabajo = new JComboBox();
        this.JTFEdadInicio = new JTextField();
        this.jLabel17 = new JLabel();
        this.jRadioButton35 = new JRadioButton();
        this.jRadioButton36 = new JRadioButton();
        this.jLabel18 = new JLabel();
        this.jRadioButton37 = new JRadioButton();
        this.jRadioButton38 = new JRadioButton();
        this.jPanel9 = new JPanel();
        this.JCBAceptacion = new JComboBox();
        this.jLabel19 = new JLabel();
        this.jRadioButton39 = new JRadioButton();
        this.jRadioButton40 = new JRadioButton();
        this.jLabel20 = new JLabel();
        this.jRadioButton41 = new JRadioButton();
        this.jRadioButton42 = new JRadioButton();
        this.jLabel21 = new JLabel();
        this.jRadioButton43 = new JRadioButton();
        this.jRadioButton44 = new JRadioButton();
        this.JTFActividades = new JTextField();
        this.jPanel10 = new JPanel();
        this.jLabel24 = new JLabel();
        this.jRadioButton49 = new JRadioButton();
        this.jRadioButton50 = new JRadioButton();
        this.JTFHoras = new JTextField();
        this.jLabel25 = new JLabel();
        this.jRadioButton51 = new JRadioButton();
        this.jRadioButton52 = new JRadioButton();
        this.JTFComida = new JTextField();
        this.jLabel26 = new JLabel();
        this.jRadioButton53 = new JRadioButton();
        this.jRadioButton54 = new JRadioButton();
        this.jLabel27 = new JLabel();
        this.jRadioButton55 = new JRadioButton();
        this.jRadioButton56 = new JRadioButton();
        this.jLabel28 = new JLabel();
        this.jRadioButton57 = new JRadioButton();
        this.jRadioButton58 = new JRadioButton();
        this.JTFSustancias = new JTextField();
        this.jLabel29 = new JLabel();
        this.jRadioButton59 = new JRadioButton();
        this.jRadioButton60 = new JRadioButton();
        this.jPanel11 = new JPanel();
        this.jLabel22 = new JLabel();
        this.jRadioButton45 = new JRadioButton();
        this.jRadioButton46 = new JRadioButton();
        this.JTFFechaMest = new JTextField();
        this.jLabel23 = new JLabel();
        this.jRadioButton47 = new JRadioButton();
        this.jRadioButton48 = new JRadioButton();
        this.jLabel30 = new JLabel();
        this.jRadioButton61 = new JRadioButton();
        this.jRadioButton62 = new JRadioButton();
        this.jLabel31 = new JLabel();
        this.jRadioButton63 = new JRadioButton();
        this.jRadioButton64 = new JRadioButton();
        this.jLabel32 = new JLabel();
        this.jRadioButton65 = new JRadioButton();
        this.jRadioButton66 = new JRadioButton();
        this.JTFITS = new JTextField();
        this.jLabel33 = new JLabel();
        this.jRadioButton67 = new JRadioButton();
        this.jRadioButton68 = new JRadioButton();
        this.jPanel12 = new JPanel();
        this.JCBRelSex = new JComboBox();
        this.JCBRelSex1 = new JComboBox();
        this.JTFEdadRel = new JTextField();
        this.jLabel34 = new JLabel();
        this.jRadioButton69 = new JRadioButton();
        this.jRadioButton70 = new JRadioButton();
        this.JTFEdadRel1 = new JTextField();
        this.jPanel13 = new JPanel();
        this.JCBRelSex2 = new JComboBox();
        this.JPAnimo = new JPanel();
        this.JPReferente = new JPanel();
        this.jLabel35 = new JLabel();
        this.jRadioButton71 = new JRadioButton();
        this.jRadioButton72 = new JRadioButton();
        this.JTFCelPadre = new JTextField();
        this.JTFTelPadre = new JTextField();
        this.jPanel2 = new JPanel();
        this.jScrollPane2 = new JScrollPane();
        this.JTHistorio = new JTable();
        setName("xjpAdultoJoven2");
        this.jTabbedPane1.setForeground(Color.red);
        this.jTabbedPane1.setFont(new Font("Arial", 1, 12));
        this.jScrollPane1.setHorizontalScrollBar((JScrollBar) null);
        this.jPanel3.setBorder(BorderFactory.createTitledBorder((Border) null, "FAMILIA", 0, 0, new Font("Arial", 1, 14), new Color(0, 102, 0)));
        this.jPanel4.setBorder(BorderFactory.createTitledBorder((Border) null, "Estudio", 0, 0, new Font("Arial", 1, 12), Color.red));
        this.jLabel1.setFont(new Font("Arial", 1, 12));
        this.jLabel1.setText("Estudió el Padre");
        this.EstPadre.add(this.jRadioButton1);
        this.jRadioButton1.setFont(new Font("Arial", 1, 12));
        this.jRadioButton1.setText("Si");
        this.jRadioButton1.setName("1");
        this.EstPadre.add(this.jRadioButton2);
        this.jRadioButton2.setFont(new Font("Arial", 1, 12));
        this.jRadioButton2.setSelected(true);
        this.jRadioButton2.setText("No");
        this.jRadioButton2.setName("0");
        this.jLabel2.setFont(new Font("Arial", 1, 12));
        this.jLabel2.setText("Estudió la Madre");
        this.EstMadre.add(this.jRadioButton3);
        this.jRadioButton3.setFont(new Font("Arial", 1, 12));
        this.jRadioButton3.setText("Si");
        this.jRadioButton3.setName("1");
        this.EstMadre.add(this.jRadioButton4);
        this.jRadioButton4.setFont(new Font("Arial", 1, 12));
        this.jRadioButton4.setSelected(true);
        this.jRadioButton4.setText("No");
        this.jRadioButton4.setName("0");
        this.jLabel3.setFont(new Font("Arial", 1, 12));
        this.jLabel3.setText("Estudió la Pareja");
        this.EstPareja.add(this.jRadioButton5);
        this.jRadioButton5.setFont(new Font("Arial", 1, 12));
        this.jRadioButton5.setText("Si");
        this.jRadioButton5.setName("1");
        this.EstPareja.add(this.jRadioButton6);
        this.jRadioButton6.setFont(new Font("Arial", 1, 12));
        this.jRadioButton6.setSelected(true);
        this.jRadioButton6.setText("No");
        this.jRadioButton6.setName("0");
        GroupLayout jPanel4Layout = new GroupLayout(this.jPanel4);
        this.jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel4Layout.createSequentialGroup().addGap(2, 2, 2).addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.TRAILING).addGroup(jPanel4Layout.createSequentialGroup().addComponent(this.jLabel1).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.jRadioButton1).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton2)).addGroup(jPanel4Layout.createSequentialGroup().addComponent(this.jLabel2, -2, 98, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton3).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton4))).addGroup(jPanel4Layout.createSequentialGroup().addComponent(this.jLabel3, -2, 98, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton5).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton6))).addGap(2, 2, 2)));
        jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel4Layout.createSequentialGroup().addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jRadioButton1).addComponent(this.jRadioButton2).addComponent(this.jLabel1)).addGap(0, 0, 0).addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jRadioButton3).addComponent(this.jRadioButton4).addComponent(this.jLabel2)).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jRadioButton5).addComponent(this.jRadioButton6).addComponent(this.jLabel3)).addGap(2, 2, 2)));
        this.jPanel5.setBorder(BorderFactory.createTitledBorder((Border) null, "Trabajo", 0, 0, new Font("Arial", 1, 12), Color.red));
        this.jLabel4.setFont(new Font("Arial", 1, 12));
        this.jLabel4.setText("Padre");
        this.TrabPadre.add(this.jRadioButton7);
        this.jRadioButton7.setFont(new Font("Arial", 1, 12));
        this.jRadioButton7.setText("Si");
        this.jRadioButton7.setName("1");
        this.TrabPadre.add(this.jRadioButton8);
        this.jRadioButton8.setFont(new Font("Arial", 1, 12));
        this.jRadioButton8.setSelected(true);
        this.jRadioButton8.setText("No");
        this.jRadioButton8.setName("0");
        this.jLabel5.setFont(new Font("Arial", 1, 12));
        this.jLabel5.setText("Madre");
        this.TrabMadre.add(this.jRadioButton9);
        this.jRadioButton9.setFont(new Font("Arial", 1, 12));
        this.jRadioButton9.setText("Si");
        this.jRadioButton9.setName("1");
        this.TrabMadre.add(this.jRadioButton10);
        this.jRadioButton10.setFont(new Font("Arial", 1, 12));
        this.jRadioButton10.setSelected(true);
        this.jRadioButton10.setText("No");
        this.jRadioButton10.setName("0");
        this.jLabel6.setFont(new Font("Arial", 1, 12));
        this.jLabel6.setText("Pareja");
        this.TrabPareja.add(this.jRadioButton11);
        this.jRadioButton11.setFont(new Font("Arial", 1, 12));
        this.jRadioButton11.setText("Si");
        this.jRadioButton11.setName("1");
        this.TrabPareja.add(this.jRadioButton12);
        this.jRadioButton12.setFont(new Font("Arial", 1, 12));
        this.jRadioButton12.setSelected(true);
        this.jRadioButton12.setText("No");
        this.jRadioButton12.setName("0");
        GroupLayout jPanel5Layout = new GroupLayout(this.jPanel5);
        this.jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel5Layout.createSequentialGroup().addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup().addGap(2, 2, 2).addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false).addComponent(this.jLabel6, -1, 46, 32767).addComponent(this.jLabel5, -1, -1, 32767))).addGroup(jPanel5Layout.createSequentialGroup().addComponent(this.jLabel4).addGap(14, 14, 14))).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel5Layout.createSequentialGroup().addComponent(this.jRadioButton7).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton8)).addGroup(GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup().addComponent(this.jRadioButton9).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton10)).addGroup(GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup().addComponent(this.jRadioButton11).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton12)))));
        jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel5Layout.createSequentialGroup().addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jRadioButton7).addComponent(this.jRadioButton8).addComponent(this.jLabel4)).addGap(2, 2, 2).addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jRadioButton9).addComponent(this.jRadioButton10).addComponent(this.jLabel5)).addGap(2, 2, 2).addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jRadioButton11).addComponent(this.jRadioButton12).addComponent(this.jLabel6)).addGap(2, 2, 2)));
        this.JTFProPadres.setFont(new Font("Arial", 1, 12));
        this.JTFProPadres.setBorder(BorderFactory.createTitledBorder((Border) null, "Profesion Padres", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.JTFProPareja.setFont(new Font("Arial", 1, 12));
        this.JTFProPareja.setBorder(BorderFactory.createTitledBorder((Border) null, "Profesion Pareja", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.jLabel7.setFont(new Font("Arial", 1, 12));
        this.jLabel7.setText("Apoyo Social o Subsidio");
        this.ApoyoSocial.add(this.jRadioButton13);
        this.jRadioButton13.setFont(new Font("Arial", 1, 12));
        this.jRadioButton13.setText("Si");
        this.jRadioButton13.setName("1");
        this.ApoyoSocial.add(this.jRadioButton14);
        this.jRadioButton14.setFont(new Font("Arial", 1, 12));
        this.jRadioButton14.setSelected(true);
        this.jRadioButton14.setText("No");
        this.jRadioButton14.setName("0");
        this.JCPersepcion.setFont(new Font("Arial", 1, 12));
        this.JCPersepcion.setModel(new DefaultComboBoxModel(new String[]{" ", "BUENA", "REGULAR", "MALA", "NO HAY RELACIÓN"}));
        this.JCPersepcion.setBorder(BorderFactory.createTitledBorder((Border) null, "Persepción sobre su Familia", 0, 0, new Font("Arial", 1, 12), Color.blue));
        GroupLayout jPanel3Layout = new GroupLayout(this.jPanel3);
        this.jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel3Layout.createSequentialGroup().addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel3Layout.createSequentialGroup().addComponent(this.jLabel7, -2, 137, -2).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.jRadioButton13).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton14).addGap(69, 69, 69).addComponent(this.JCPersepcion, -2, 231, -2)).addGroup(jPanel3Layout.createSequentialGroup().addGap(3, 3, 3).addComponent(this.jPanel4, -2, -1, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jPanel5, -2, -1, -2).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false).addComponent(this.JTFProPadres, -1, 322, 32767).addComponent(this.JTFProPareja)))).addContainerGap(-1, 32767)));
        jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel3Layout.createSequentialGroup().addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel3Layout.createSequentialGroup().addGap(3, 3, 3).addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.jPanel5, -2, 95, -2).addComponent(this.jPanel4, -2, -1, -2))).addGroup(GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup().addGap(3, 3, 3).addComponent(this.JTFProPadres, -2, -1, -2).addGap(1, 1, 1).addComponent(this.JTFProPareja, -2, -1, -2))).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.JCPersepcion, -2, 41, -2).addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jRadioButton13).addComponent(this.jRadioButton14).addComponent(this.jLabel7))).addGap(3, 3, 3)));
        this.jPanel6.setBorder(BorderFactory.createTitledBorder((Border) null, "VIVIENDA", 0, 0, new Font("Arial", 1, 14), new Color(0, 102, 0)));
        this.jLabel9.setFont(new Font("Arial", 1, 12));
        this.jLabel9.setText("Energia Eléctrica");
        this.Energia.add(this.jRadioButton19);
        this.jRadioButton19.setFont(new Font("Arial", 1, 12));
        this.jRadioButton19.setText("Si");
        this.jRadioButton19.setName("1");
        this.Energia.add(this.jRadioButton20);
        this.jRadioButton20.setFont(new Font("Arial", 1, 12));
        this.jRadioButton20.setSelected(true);
        this.jRadioButton20.setText("No");
        this.jRadioButton20.setName("0");
        this.jLabel10.setFont(new Font("Arial", 1, 12));
        this.jLabel10.setText("Agua");
        this.Agua.add(this.jRadioButton21);
        this.jRadioButton21.setFont(new Font("Arial", 1, 12));
        this.jRadioButton21.setText("Si");
        this.jRadioButton21.setName("1");
        this.Agua.add(this.jRadioButton22);
        this.jRadioButton22.setFont(new Font("Arial", 1, 12));
        this.jRadioButton22.setSelected(true);
        this.jRadioButton22.setText("No");
        this.jRadioButton22.setName("0");
        this.jLabel11.setFont(new Font("Arial", 1, 12));
        this.jLabel11.setText("Hacinamiento");
        this.Hacinamiento.add(this.jRadioButton23);
        this.jRadioButton23.setFont(new Font("Arial", 1, 12));
        this.jRadioButton23.setText("Si");
        this.jRadioButton23.setName("1");
        this.Hacinamiento.add(this.jRadioButton24);
        this.jRadioButton24.setFont(new Font("Arial", 1, 12));
        this.jRadioButton24.setSelected(true);
        this.jRadioButton24.setText("No");
        this.jRadioButton24.setName("0");
        GroupLayout jPanel6Layout = new GroupLayout(this.jPanel6);
        this.jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel6Layout.createSequentialGroup().addComponent(this.jLabel9, -2, 105, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton19).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton20).addGap(15, 15, 15).addComponent(this.jLabel10, -2, 41, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton21).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton22).addGap(31, 31, 31).addComponent(this.jLabel11, -2, 87, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton23).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton24).addContainerGap(-1, 32767)));
        jPanel6Layout.setVerticalGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel6Layout.createSequentialGroup().addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jRadioButton23).addComponent(this.jRadioButton24).addComponent(this.jLabel11)).addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jRadioButton19).addComponent(this.jRadioButton20).addComponent(this.jLabel9).addComponent(this.jRadioButton21).addComponent(this.jRadioButton22).addComponent(this.jLabel10))).addGap(3, 3, 3)));
        this.jPanel7.setBorder(BorderFactory.createTitledBorder((Border) null, "EDUCACIÓN", 0, 0, new Font("Arial", 1, 14), new Color(0, 102, 0)));
        this.jLabel12.setFont(new Font("Arial", 1, 12));
        this.jLabel12.setText("Estudia");
        this.Estudia.add(this.jRadioButton25);
        this.jRadioButton25.setFont(new Font("Arial", 1, 12));
        this.jRadioButton25.setText("Si");
        this.jRadioButton25.setName("1");
        this.Estudia.add(this.jRadioButton26);
        this.jRadioButton26.setFont(new Font("Arial", 1, 12));
        this.jRadioButton26.setSelected(true);
        this.jRadioButton26.setText("No");
        this.jRadioButton26.setName("0");
        this.JTFInstitucion.setFont(new Font("Arial", 1, 12));
        this.JTFInstitucion.setBorder(BorderFactory.createTitledBorder((Border) null, "Nombre Institución", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.jComboBox1.setFont(new Font("Arial", 1, 12));
        this.jComboBox1.setModel(new DefaultComboBoxModel(new String[]{" ", "NO ESCOLARIZADO", "PRIMARIA", "SECUNDARIA", "TECNICO", "UNIVERSITARIO"}));
        this.jComboBox1.setBorder(BorderFactory.createTitledBorder((Border) null, "Nivel Estudio", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.JTFGrado.setFont(new Font("Arial", 1, 12));
        this.JTFGrado.setBorder(BorderFactory.createTitledBorder((Border) null, "Grado", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.JTFAprobado.setFont(new Font("Arial", 1, 12));
        this.JTFAprobado.setBorder(BorderFactory.createTitledBorder((Border) null, "Años Aprobados", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.jLabel13.setFont(new Font("Arial", 1, 12));
        this.jLabel13.setText("Problemas en la Escuela");
        this.Problemas.add(this.jRadioButton27);
        this.jRadioButton27.setFont(new Font("Arial", 1, 12));
        this.jRadioButton27.setText("Si");
        this.jRadioButton27.setName("1");
        this.Problemas.add(this.jRadioButton28);
        this.jRadioButton28.setFont(new Font("Arial", 1, 12));
        this.jRadioButton28.setSelected(true);
        this.jRadioButton28.setText("No");
        this.jRadioButton28.setName("0");
        this.JTFRepetido.setFont(new Font("Arial", 1, 12));
        this.JTFRepetido.setBorder(BorderFactory.createTitledBorder((Border) null, "Años Repetido", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.jLabel14.setFont(new Font("Arial", 1, 12));
        this.jLabel14.setText("Violencia Escolar");
        this.ViolenciaEsc.add(this.jRadioButton29);
        this.jRadioButton29.setFont(new Font("Arial", 1, 12));
        this.jRadioButton29.setText("Si");
        this.jRadioButton29.setName("1");
        this.ViolenciaEsc.add(this.jRadioButton30);
        this.jRadioButton30.setFont(new Font("Arial", 1, 12));
        this.jRadioButton30.setSelected(true);
        this.jRadioButton30.setText("No");
        this.jRadioButton30.setName("0");
        this.jLabel15.setFont(new Font("Arial", 1, 12));
        this.jLabel15.setText("Deserción");
        this.Desercion.add(this.jRadioButton31);
        this.jRadioButton31.setFont(new Font("Arial", 1, 12));
        this.jRadioButton31.setText("Si");
        this.jRadioButton31.setName("1");
        this.Desercion.add(this.jRadioButton32);
        this.jRadioButton32.setFont(new Font("Arial", 1, 12));
        this.jRadioButton32.setSelected(true);
        this.jRadioButton32.setText("No");
        this.jRadioButton32.setName("0");
        this.jLabel16.setFont(new Font("Arial", 1, 12));
        this.jLabel16.setText("Educación No Formal");
        this.EduNoFormal.add(this.jRadioButton33);
        this.jRadioButton33.setFont(new Font("Arial", 1, 12));
        this.jRadioButton33.setText("Si");
        this.jRadioButton33.setName("1");
        this.EduNoFormal.add(this.jRadioButton34);
        this.jRadioButton34.setFont(new Font("Arial", 1, 12));
        this.jRadioButton34.setSelected(true);
        this.jRadioButton34.setText("No");
        this.jRadioButton34.setName("0");
        GroupLayout jPanel7Layout = new GroupLayout(this.jPanel7);
        this.jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel7Layout.createSequentialGroup().addGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.TRAILING).addGroup(jPanel7Layout.createSequentialGroup().addComponent(this.jLabel12, -2, 50, -2).addGap(3, 3, 3).addComponent(this.jRadioButton25).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton26).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JTFInstitucion, -2, 191, -2).addGap(1, 1, 1).addComponent(this.jComboBox1, -2, 179, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JTFGrado, -2, 60, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JTFAprobado, -2, 117, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JTFRepetido, -2, 109, -2)).addGroup(jPanel7Layout.createSequentialGroup().addComponent(this.jLabel13).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton27).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton28).addGap(18, 18, 18).addComponent(this.jLabel14).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton29).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton30).addGap(34, 34, 34).addComponent(this.jLabel15, -2, 62, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton31).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton32).addGap(18, 18, 18).addComponent(this.jLabel16).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.jRadioButton33).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton34))).addGap(22, 23, 32767)));
        jPanel7Layout.setVerticalGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel7Layout.createSequentialGroup().addGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.JTFAprobado, -2, -1, -2).addComponent(this.JTFRepetido, -2, -1, -2)).addGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jRadioButton25).addComponent(this.jRadioButton26).addComponent(this.jLabel12).addComponent(this.JTFInstitucion, -2, -1, -2).addComponent(this.jComboBox1, -2, 41, -2).addComponent(this.JTFGrado, -2, -1, -2))).addGap(3, 3, 3).addGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jRadioButton27).addComponent(this.jRadioButton28).addComponent(this.jLabel13)).addGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jRadioButton29).addComponent(this.jRadioButton30).addComponent(this.jLabel14).addComponent(this.jRadioButton31).addComponent(this.jRadioButton32).addComponent(this.jLabel15).addComponent(this.jRadioButton33).addComponent(this.jRadioButton34).addComponent(this.jLabel16))).addContainerGap(-1, 32767)));
        this.jPanel8.setBorder(BorderFactory.createTitledBorder((Border) null, "TRABAJO", 0, 0, new Font("Arial", 1, 14), new Color(0, 102, 0)));
        this.JCBTrabajo.setFont(new Font("Arial", 1, 12));
        this.JCBTrabajo.setModel(new DefaultComboBoxModel(new String[]{" ", "TRABAJA", "BUSCA 1ra VEZ", "NO Y NO BUSCA", "PASANTIA", "DESOCUPADO", "NO TRABAJA Y NO ESTUDIA"}));
        this.JCBTrabajo.setBorder(BorderFactory.createTitledBorder((Border) null, "Actividad", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.JTFEdadInicio.setFont(new Font("Arial", 1, 12));
        this.JTFEdadInicio.setBorder(BorderFactory.createTitledBorder((Border) null, "Edad Inicio", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.jLabel17.setFont(new Font("Arial", 1, 12));
        this.jLabel17.setText("Trabajo Infantil");
        this.TrabInfantil.add(this.jRadioButton35);
        this.jRadioButton35.setFont(new Font("Arial", 1, 12));
        this.jRadioButton35.setText("Si");
        this.jRadioButton35.setName("1");
        this.TrabInfantil.add(this.jRadioButton36);
        this.jRadioButton36.setFont(new Font("Arial", 1, 12));
        this.jRadioButton36.setSelected(true);
        this.jRadioButton36.setText("No");
        this.jRadioButton36.setName("0");
        this.jLabel18.setFont(new Font("Arial", 1, 12));
        this.jLabel18.setText("Trabajo Juvenil");
        this.TrabJuvenil.add(this.jRadioButton37);
        this.jRadioButton37.setFont(new Font("Arial", 1, 12));
        this.jRadioButton37.setText("Si");
        this.jRadioButton37.setName("1");
        this.TrabJuvenil.add(this.jRadioButton38);
        this.jRadioButton38.setFont(new Font("Arial", 1, 12));
        this.jRadioButton38.setSelected(true);
        this.jRadioButton38.setText("No");
        this.jRadioButton38.setName("0");
        GroupLayout jPanel8Layout = new GroupLayout(this.jPanel8);
        this.jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel8Layout.createSequentialGroup().addContainerGap().addComponent(this.JCBTrabajo, -2, 191, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JTFEdadInicio, -2, 83, -2).addGap(18, 18, 18).addComponent(this.jLabel17).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.jRadioButton35).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton36).addGap(18, 18, 18).addComponent(this.jLabel18, -2, 90, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton37).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton38).addContainerGap(-1, 32767)));
        jPanel8Layout.setVerticalGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel8Layout.createSequentialGroup().addGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.JCBTrabajo, -2, 41, -2).addComponent(this.JTFEdadInicio, -2, -1, -2).addGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jRadioButton35).addComponent(this.jRadioButton36).addComponent(this.jLabel17).addComponent(this.jRadioButton37).addComponent(this.jRadioButton38).addComponent(this.jLabel18))).addGap(2, 2, 2)));
        this.jPanel9.setBorder(BorderFactory.createTitledBorder((Border) null, "VIDA SOCIAL", 0, 0, new Font("Arial", 1, 14), new Color(0, 102, 0)));
        this.JCBAceptacion.setFont(new Font("Arial", 1, 12));
        this.JCBAceptacion.setModel(new DefaultComboBoxModel(new String[]{" ", "ACEPTADO", "IGNORADO", "RECHAZADO", "NO SABE"}));
        this.JCBAceptacion.setBorder(BorderFactory.createTitledBorder((Border) null, "Aceptación", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.jLabel19.setFont(new Font("Arial", 1, 12));
        this.jLabel19.setText("Pareja");
        this.Pareja.add(this.jRadioButton39);
        this.jRadioButton39.setFont(new Font("Arial", 1, 12));
        this.jRadioButton39.setText("Si");
        this.jRadioButton39.setName("1");
        this.Pareja.add(this.jRadioButton40);
        this.jRadioButton40.setFont(new Font("Arial", 1, 12));
        this.jRadioButton40.setSelected(true);
        this.jRadioButton40.setText("No");
        this.jRadioButton40.setName("0");
        this.jLabel20.setFont(new Font("Arial", 1, 12));
        this.jLabel20.setText("<html><p align=\"justify\">Violencia en la Pareja</p></html>");
        this.Violencia.add(this.jRadioButton41);
        this.jRadioButton41.setFont(new Font("Arial", 1, 12));
        this.jRadioButton41.setText("Si");
        this.jRadioButton41.setName("1");
        this.Violencia.add(this.jRadioButton42);
        this.jRadioButton42.setFont(new Font("Arial", 1, 12));
        this.jRadioButton42.setSelected(true);
        this.jRadioButton42.setText("No");
        this.jRadioButton42.setName("0");
        this.jLabel21.setFont(new Font("Arial", 1, 12));
        this.jLabel21.setText("Amigos");
        this.Amigos.add(this.jRadioButton43);
        this.jRadioButton43.setFont(new Font("Arial", 1, 12));
        this.jRadioButton43.setText("Si");
        this.jRadioButton43.setName("1");
        this.Amigos.add(this.jRadioButton44);
        this.jRadioButton44.setFont(new Font("Arial", 1, 12));
        this.jRadioButton44.setSelected(true);
        this.jRadioButton44.setText("No");
        this.jRadioButton44.setName("0");
        this.JTFActividades.setFont(new Font("Arial", 1, 12));
        this.JTFActividades.setToolTipText("Computador, TV, Video Juegos");
        this.JTFActividades.setBorder(BorderFactory.createTitledBorder((Border) null, "Actividades o Hobbies", 0, 0, new Font("Arial", 1, 12), Color.blue));
        GroupLayout jPanel9Layout = new GroupLayout(this.jPanel9);
        this.jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel9Layout.createSequentialGroup().addGap(3, 3, 3).addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false).addGroup(jPanel9Layout.createSequentialGroup().addGap(2, 2, 2).addComponent(this.jLabel21).addGap(2, 2, 2).addComponent(this.jRadioButton43).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton44).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JTFActividades)).addGroup(jPanel9Layout.createSequentialGroup().addComponent(this.JCBAceptacion, -2, 191, -2).addGap(18, 18, 18).addComponent(this.jLabel19).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.jRadioButton39).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton40).addGap(48, 48, 48).addComponent(this.jLabel20, -2, 131, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton41).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton42))).addContainerGap(-1, 32767)));
        jPanel9Layout.setVerticalGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel9Layout.createSequentialGroup().addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.JCBAceptacion, -2, 41, -2).addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jRadioButton41).addComponent(this.jRadioButton42)).addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jRadioButton39).addComponent(this.jRadioButton40).addComponent(this.jLabel19).addComponent(this.jLabel20, -2, 23, -2))).addGap(5, 5, 5).addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jRadioButton43).addComponent(this.jRadioButton44).addComponent(this.jLabel21)).addComponent(this.JTFActividades, -2, -1, -2))));
        this.jPanel10.setBorder(BorderFactory.createTitledBorder((Border) null, "HÁBITOS/CONSUMOS", 0, 0, new Font("Arial", 1, 14), new Color(0, 102, 0)));
        this.jLabel24.setFont(new Font("Arial", 1, 12));
        this.jLabel24.setText("Sueño Normal");
        this.Suenio.add(this.jRadioButton49);
        this.jRadioButton49.setFont(new Font("Arial", 1, 12));
        this.jRadioButton49.setText("Si");
        this.jRadioButton49.setName("1");
        this.Suenio.add(this.jRadioButton50);
        this.jRadioButton50.setFont(new Font("Arial", 1, 12));
        this.jRadioButton50.setSelected(true);
        this.jRadioButton50.setText("No");
        this.jRadioButton50.setName("0");
        this.JTFHoras.setFont(new Font("Arial", 1, 12));
        this.JTFHoras.setBorder(BorderFactory.createTitledBorder((Border) null, "Horas", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.jLabel25.setFont(new Font("Arial", 1, 12));
        this.jLabel25.setText("Alimentacion adecuada");
        this.Alimentacion.add(this.jRadioButton51);
        this.jRadioButton51.setFont(new Font("Arial", 1, 12));
        this.jRadioButton51.setText("Si");
        this.jRadioButton51.setName("1");
        this.Alimentacion.add(this.jRadioButton52);
        this.jRadioButton52.setFont(new Font("Arial", 1, 12));
        this.jRadioButton52.setSelected(true);
        this.jRadioButton52.setText("No");
        this.jRadioButton52.setName("0");
        this.JTFComida.setFont(new Font("Arial", 1, 12));
        this.JTFComida.setBorder(BorderFactory.createTitledBorder((Border) null, "Comida x dia", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.jLabel26.setFont(new Font("Arial", 1, 12));
        this.jLabel26.setText("Fuma");
        this.Fuma.add(this.jRadioButton53);
        this.jRadioButton53.setFont(new Font("Arial", 1, 12));
        this.jRadioButton53.setText("Si");
        this.jRadioButton53.setName("1");
        this.Fuma.add(this.jRadioButton54);
        this.jRadioButton54.setFont(new Font("Arial", 1, 12));
        this.jRadioButton54.setSelected(true);
        this.jRadioButton54.setText("No");
        this.jRadioButton54.setName("0");
        this.jLabel27.setFont(new Font("Arial", 1, 12));
        this.jLabel27.setText("Alcohol");
        this.Alcoho.add(this.jRadioButton55);
        this.jRadioButton55.setFont(new Font("Arial", 1, 12));
        this.jRadioButton55.setText("Si");
        this.jRadioButton55.setName("1");
        this.Alcoho.add(this.jRadioButton56);
        this.jRadioButton56.setFont(new Font("Arial", 1, 12));
        this.jRadioButton56.setSelected(true);
        this.jRadioButton56.setText("No");
        this.jRadioButton56.setName("0");
        this.jLabel28.setFont(new Font("Arial", 1, 12));
        this.jLabel28.setText("Sustancias");
        this.Sustancias.add(this.jRadioButton57);
        this.jRadioButton57.setFont(new Font("Arial", 1, 12));
        this.jRadioButton57.setText("Si");
        this.jRadioButton57.setName("1");
        this.Sustancias.add(this.jRadioButton58);
        this.jRadioButton58.setFont(new Font("Arial", 1, 12));
        this.jRadioButton58.setSelected(true);
        this.jRadioButton58.setText("No");
        this.jRadioButton58.setName("0");
        this.JTFSustancias.setFont(new Font("Arial", 1, 12));
        this.JTFSustancias.setBorder(BorderFactory.createTitledBorder((Border) null, "Cuales Sustancias", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.jLabel29.setFont(new Font("Arial", 1, 12));
        this.jLabel29.setText("Conduce");
        this.Conduce.add(this.jRadioButton59);
        this.jRadioButton59.setFont(new Font("Arial", 1, 12));
        this.jRadioButton59.setText("Si");
        this.jRadioButton59.setName("1");
        this.Conduce.add(this.jRadioButton60);
        this.jRadioButton60.setFont(new Font("Arial", 1, 12));
        this.jRadioButton60.setSelected(true);
        this.jRadioButton60.setText("No");
        this.jRadioButton60.setName("0");
        GroupLayout jPanel10Layout = new GroupLayout(this.jPanel10);
        this.jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(jPanel10Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel10Layout.createSequentialGroup().addGroup(jPanel10Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel10Layout.createSequentialGroup().addComponent(this.jLabel24).addGap(2, 2, 2).addComponent(this.jRadioButton49).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton50).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JTFHoras, -2, 65, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jLabel25).addGap(2, 2, 2).addComponent(this.jRadioButton51).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton52).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.JTFComida, -2, 101, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jLabel26).addGap(2, 2, 2).addComponent(this.jRadioButton53).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton54).addGap(10, 10, 10).addComponent(this.jLabel27).addGap(2, 2, 2).addComponent(this.jRadioButton55).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton56)).addGroup(jPanel10Layout.createSequentialGroup().addComponent(this.jLabel29).addGap(2, 2, 2).addComponent(this.jRadioButton59).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton60).addGap(18, 18, 18).addComponent(this.jLabel28).addGap(2, 2, 2).addComponent(this.jRadioButton57).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton58).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JTFSustancias, -2, 428, -2))).addGap(0, 0, 32767)));
        jPanel10Layout.setVerticalGroup(jPanel10Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel10Layout.createSequentialGroup().addGroup(jPanel10Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel10Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jRadioButton49).addComponent(this.jRadioButton50).addComponent(this.jLabel24)).addComponent(this.JTFHoras, -2, -1, -2).addComponent(this.JTFComida, -2, -1, -2).addGroup(jPanel10Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jRadioButton51).addComponent(this.jRadioButton52).addComponent(this.jLabel25)).addGroup(jPanel10Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jRadioButton53).addComponent(this.jRadioButton54).addComponent(this.jLabel26).addComponent(this.jRadioButton55).addComponent(this.jRadioButton56).addComponent(this.jLabel27))).addGroup(jPanel10Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel10Layout.createSequentialGroup().addGap(1, 1, 1).addGroup(jPanel10Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jRadioButton59).addComponent(this.jRadioButton60).addComponent(this.jLabel29).addComponent(this.jRadioButton57).addComponent(this.jRadioButton58).addComponent(this.jLabel28))).addComponent(this.JTFSustancias, -2, -1, -2))));
        this.jPanel11.setBorder(BorderFactory.createTitledBorder((Border) null, "GINECO-UROLOGICO", 0, 0, new Font("Arial", 1, 14), new Color(0, 102, 0)));
        this.jLabel22.setFont(new Font("Arial", 1, 12));
        this.jLabel22.setText("Mestruación");
        this.Mestruacion.add(this.jRadioButton45);
        this.jRadioButton45.setFont(new Font("Arial", 1, 12));
        this.jRadioButton45.setText("Si");
        this.jRadioButton45.setName("1");
        this.Mestruacion.add(this.jRadioButton46);
        this.jRadioButton46.setFont(new Font("Arial", 1, 12));
        this.jRadioButton46.setSelected(true);
        this.jRadioButton46.setText("No");
        this.jRadioButton46.setName("0");
        this.JTFFechaMest.setFont(new Font("Arial", 1, 12));
        this.JTFFechaMest.setBorder(BorderFactory.createTitledBorder((Border) null, "Fecha Mestruación", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.jLabel23.setFont(new Font("Arial", 1, 12));
        this.jLabel23.setText("Ciclos Regulares");
        this.Ciclo.add(this.jRadioButton47);
        this.jRadioButton47.setFont(new Font("Arial", 1, 12));
        this.jRadioButton47.setText("Si");
        this.jRadioButton47.setName("1");
        this.Ciclo.add(this.jRadioButton48);
        this.jRadioButton48.setFont(new Font("Arial", 1, 12));
        this.jRadioButton48.setSelected(true);
        this.jRadioButton48.setText("No");
        this.jRadioButton48.setName("0");
        this.jLabel30.setFont(new Font("Arial", 1, 12));
        this.jLabel30.setText("Dismenorrea");
        this.Dismenorrea.add(this.jRadioButton61);
        this.jRadioButton61.setFont(new Font("Arial", 1, 12));
        this.jRadioButton61.setText("Si");
        this.jRadioButton61.setName("1");
        this.Dismenorrea.add(this.jRadioButton62);
        this.jRadioButton62.setFont(new Font("Arial", 1, 12));
        this.jRadioButton62.setSelected(true);
        this.jRadioButton62.setText("No");
        this.jRadioButton62.setName("0");
        this.jLabel31.setFont(new Font("Arial", 1, 12));
        this.jLabel31.setText("Secreación Peneana");
        this.Peneana.add(this.jRadioButton63);
        this.jRadioButton63.setFont(new Font("Arial", 1, 12));
        this.jRadioButton63.setText("Si");
        this.jRadioButton63.setName("1");
        this.Peneana.add(this.jRadioButton64);
        this.jRadioButton64.setFont(new Font("Arial", 1, 12));
        this.jRadioButton64.setSelected(true);
        this.jRadioButton64.setText("No");
        this.jRadioButton64.setName("0");
        this.jLabel32.setFont(new Font("Arial", 1, 12));
        this.jLabel32.setText("ITS/VIH");
        this.ITS.add(this.jRadioButton65);
        this.jRadioButton65.setFont(new Font("Arial", 1, 12));
        this.jRadioButton65.setText("Si");
        this.jRadioButton65.setName("1");
        this.ITS.add(this.jRadioButton66);
        this.jRadioButton66.setFont(new Font("Arial", 1, 12));
        this.jRadioButton66.setSelected(true);
        this.jRadioButton66.setText("No");
        this.jRadioButton66.setName("0");
        this.JTFITS.setFont(new Font("Arial", 1, 12));
        this.JTFITS.setBorder(BorderFactory.createTitledBorder((Border) null, "Cuál ITS", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.jLabel33.setFont(new Font("Arial", 1, 12));
        this.jLabel33.setText("Tratamiento ITS");
        this.TratamientoIts.add(this.jRadioButton67);
        this.jRadioButton67.setFont(new Font("Arial", 1, 12));
        this.jRadioButton67.setText("Si");
        this.jRadioButton67.setName("1");
        this.TratamientoIts.add(this.jRadioButton68);
        this.jRadioButton68.setFont(new Font("Arial", 1, 12));
        this.jRadioButton68.setSelected(true);
        this.jRadioButton68.setText("No");
        this.jRadioButton68.setName("0");
        GroupLayout jPanel11Layout = new GroupLayout(this.jPanel11);
        this.jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup().addComponent(this.jLabel31).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton63).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton64).addGap(44, 44, 44).addComponent(this.jLabel32).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.jRadioButton65).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton66).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.JTFITS, -2, 249, -2).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.jLabel33).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.jRadioButton67).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton68).addContainerGap(-1, 32767)).addGroup(GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup().addGap(0, 0, 32767).addComponent(this.jLabel22).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.jRadioButton45).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton46).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.JTFFechaMest, -2, 133, -2).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.jLabel23).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.jRadioButton47).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton48).addGap(18, 18, 18).addComponent(this.jLabel30).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.jRadioButton61).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton62).addGap(161, 161, 161)));
        jPanel11Layout.setVerticalGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel11Layout.createSequentialGroup().addGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jRadioButton45).addComponent(this.jRadioButton46).addComponent(this.jLabel22)).addComponent(this.JTFFechaMest, -2, 37, -2).addGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jRadioButton47).addComponent(this.jRadioButton48).addComponent(this.jLabel23).addComponent(this.jRadioButton61).addComponent(this.jRadioButton62).addComponent(this.jLabel30))).addGap(1, 1, 1).addGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jRadioButton63).addComponent(this.jRadioButton64).addComponent(this.jLabel31)).addGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jRadioButton65).addComponent(this.jRadioButton66).addComponent(this.jLabel32)).addGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jRadioButton67).addComponent(this.jRadioButton68).addComponent(this.jLabel33)).addComponent(this.JTFITS, -2, 37, -2))));
        this.jPanel12.setBorder(BorderFactory.createTitledBorder((Border) null, "SEXUALIDAD", 0, 0, new Font("Arial", 1, 14), new Color(0, 102, 0)));
        this.JCBRelSex.setFont(new Font("Arial", 1, 12));
        this.JCBRelSex.setModel(new DefaultComboBoxModel(new String[]{" ", "NO", "HETEROSEXUAL", "HOMOSEXUAL", "AMBAS"}));
        this.JCBRelSex.setBorder(BorderFactory.createTitledBorder((Border) null, "Relaciones Sexuales", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.JCBRelSex1.setFont(new Font("Arial", 1, 12));
        this.JCBRelSex1.setModel(new DefaultComboBoxModel(new String[]{" ", "PAREJA UNICA", "VARIAS PAREJAS", "NO TIENE"}));
        this.JCBRelSex1.setBorder(BorderFactory.createTitledBorder((Border) null, "Pareja Sexual", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.JTFEdadRel.setFont(new Font("Arial", 1, 12));
        this.JTFEdadRel.setBorder(BorderFactory.createTitledBorder((Border) null, "Edad Inicio Rel. Sex.", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.jLabel34.setFont(new Font("Arial", 1, 12));
        this.jLabel34.setText("Anticoncepción");
        this.Anticoncepcion.add(this.jRadioButton69);
        this.jRadioButton69.setFont(new Font("Arial", 1, 12));
        this.jRadioButton69.setText("Si");
        this.jRadioButton69.setName("1");
        this.Anticoncepcion.add(this.jRadioButton70);
        this.jRadioButton70.setFont(new Font("Arial", 1, 12));
        this.jRadioButton70.setSelected(true);
        this.jRadioButton70.setText("No");
        this.jRadioButton70.setName("0");
        this.JTFEdadRel1.setFont(new Font("Arial", 1, 12));
        this.JTFEdadRel1.setBorder(BorderFactory.createTitledBorder((Border) null, "Cuales Anticonceptivos", 0, 0, new Font("Arial", 1, 12), Color.blue));
        GroupLayout jPanel12Layout = new GroupLayout(this.jPanel12);
        this.jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(jPanel12Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel12Layout.createSequentialGroup().addComponent(this.JCBRelSex, -2, 144, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JCBRelSex1, -2, -1, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JTFEdadRel, -2, 138, -2).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.jLabel34).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton69).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton70).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.JTFEdadRel1, -2, 207, -2).addGap(0, 0, 32767)));
        jPanel12Layout.setVerticalGroup(jPanel12Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel12Layout.createSequentialGroup().addGroup(jPanel12Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel12Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jRadioButton69).addComponent(this.jRadioButton70).addComponent(this.jLabel34).addComponent(this.JTFEdadRel1, -2, -1, -2)).addGroup(jPanel12Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.JCBRelSex, -2, 41, -2).addComponent(this.JCBRelSex1, -2, 41, -2).addComponent(this.JTFEdadRel, -2, -1, -2))).addGap(3, 3, 3)));
        this.jPanel13.setBorder(BorderFactory.createTitledBorder((Border) null, "SITUACIÓN PSICOEMOCIONAL", 0, 0, new Font("Arial", 1, 14), new Color(0, 102, 0)));
        this.JCBRelSex2.setFont(new Font("Arial", 1, 12));
        this.JCBRelSex2.setModel(new DefaultComboBoxModel(new String[]{" ", "CONFORME", "CREA PREOCUPACIÓN", "IMPIDE RELACIÓN CON LOS DEMÁS"}));
        this.JCBRelSex2.setBorder(BorderFactory.createTitledBorder((Border) null, "Imagen Corporal", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.JPAnimo.setBorder(BorderFactory.createTitledBorder((Border) null, "Estado de Ánimo", 0, 0, new Font("Arial", 1, 12), Color.blue));
        GroupLayout JPAnimoLayout = new GroupLayout(this.JPAnimo);
        this.JPAnimo.setLayout(JPAnimoLayout);
        JPAnimoLayout.setHorizontalGroup(JPAnimoLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGap(0, 194, 32767));
        JPAnimoLayout.setVerticalGroup(JPAnimoLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGap(0, 23, 32767));
        this.JPReferente.setBorder(BorderFactory.createTitledBorder((Border) null, "Referente", 0, 0, new Font("Arial", 1, 12), Color.blue));
        GroupLayout JPReferenteLayout = new GroupLayout(this.JPReferente);
        this.JPReferente.setLayout(JPReferenteLayout);
        JPReferenteLayout.setHorizontalGroup(JPReferenteLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGap(0, 194, 32767));
        JPReferenteLayout.setVerticalGroup(JPReferenteLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGap(0, 23, 32767));
        this.jLabel35.setFont(new Font("Arial", 1, 12));
        this.jLabel35.setText("Redes sociales de Apoyo");
        this.Apoyo.add(this.jRadioButton71);
        this.jRadioButton71.setFont(new Font("Arial", 1, 12));
        this.jRadioButton71.setText("Si");
        this.jRadioButton71.setName("1");
        this.Apoyo.add(this.jRadioButton72);
        this.jRadioButton72.setFont(new Font("Arial", 1, 12));
        this.jRadioButton72.setSelected(true);
        this.jRadioButton72.setText("No");
        this.jRadioButton72.setName("0");
        this.JTFCelPadre.setFont(new Font("Arial", 1, 12));
        this.JTFCelPadre.setBorder(BorderFactory.createTitledBorder((Border) null, "Cel. Adulto Responsable", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.JTFTelPadre.setFont(new Font("Arial", 1, 12));
        this.JTFTelPadre.setBorder(BorderFactory.createTitledBorder((Border) null, "Tel. Adulto Responsable", 0, 0, new Font("Arial", 1, 12), Color.blue));
        GroupLayout jPanel13Layout = new GroupLayout(this.jPanel13);
        this.jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(jPanel13Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel13Layout.createSequentialGroup().addGroup(jPanel13Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel13Layout.createSequentialGroup().addComponent(this.JCBRelSex2, -2, 144, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JPAnimo, -2, -1, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JPReferente, -2, -1, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jLabel35).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton71).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jRadioButton72)).addGroup(jPanel13Layout.createSequentialGroup().addComponent(this.JTFCelPadre, -2, 178, -2).addGap(18, 18, 18).addComponent(this.JTFTelPadre, -2, 178, -2))).addContainerGap(-1, 32767)));
        jPanel13Layout.setVerticalGroup(jPanel13Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel13Layout.createSequentialGroup().addGroup(jPanel13Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.JCBRelSex2, -2, 41, -2).addComponent(this.JPAnimo, -2, -1, -2).addComponent(this.JPReferente, -2, -1, -2).addGroup(jPanel13Layout.createSequentialGroup().addContainerGap().addGroup(jPanel13Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jRadioButton71).addComponent(this.jRadioButton72).addComponent(this.jLabel35)))).addGap(3, 3, 3).addGroup(jPanel13Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.JTFCelPadre, -2, -1, -2).addComponent(this.JTFTelPadre, -2, -1, -2)).addGap(3, 3, 3)));
        GroupLayout jPanel1Layout = new GroupLayout(this.jPanel1);
        this.jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false).addComponent(this.jPanel10, GroupLayout.Alignment.LEADING, -1, -1, 32767).addComponent(this.jPanel8, GroupLayout.Alignment.LEADING, -1, -1, 32767).addComponent(this.jPanel6, GroupLayout.Alignment.LEADING, -1, -1, 32767).addComponent(this.jPanel9, GroupLayout.Alignment.LEADING, -1, -1, 32767).addComponent(this.jPanel7, GroupLayout.Alignment.LEADING, -1, -1, 32767).addComponent(this.jPanel3, GroupLayout.Alignment.LEADING, -1, -1, 32767).addComponent(this.jPanel11, -1, -1, 32767).addComponent(this.jPanel12, -1, -1, 32767).addComponent(this.jPanel13, GroupLayout.Alignment.LEADING, -1, -1, 32767)).addGap(2, 2, 2)));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addGap(2, 2, 2).addComponent(this.jPanel3, -2, -1, -2).addGap(3, 3, 3).addComponent(this.jPanel7, -2, -1, -2).addGap(3, 3, 3).addComponent(this.jPanel9, -2, -1, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jPanel6, -2, -1, -2).addGap(3, 3, 3).addComponent(this.jPanel8, -2, -1, -2).addGap(3, 3, 3).addComponent(this.jPanel10, -2, -1, -2).addGap(3, 3, 3).addComponent(this.jPanel11, -2, -1, -2).addGap(3, 3, 3).addComponent(this.jPanel12, -2, -1, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, -1, 32767).addComponent(this.jPanel13, -2, -1, -2).addContainerGap()));
        this.jScrollPane1.setViewportView(this.jPanel1);
        this.jTabbedPane1.addTab("DATOS", this.jScrollPane1);
        this.JTHistorio.setFont(new Font("Arial", 1, 12));
        this.JTHistorio.setModel(new DefaultTableModel((Object[][]) new Object[]{new Object[0], new Object[0], new Object[0], new Object[0]}, new String[0]));
        this.JTHistorio.setSelectionBackground(new Color(255, 255, 255));
        this.JTHistorio.setSelectionForeground(Color.red);
        this.jScrollPane2.setViewportView(this.JTHistorio);
        GroupLayout jPanel2Layout = new GroupLayout(this.jPanel2);
        this.jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addComponent(this.jScrollPane2, -1, 831, 32767).addContainerGap()));
        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addComponent(this.jScrollPane2, -2, 378, -2).addContainerGap(559, 32767)));
        this.jTabbedPane1.addTab("HISTÓRICO", this.jPanel2);
        GroupLayout layout = new GroupLayout(this);
        setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.jTabbedPane1, GroupLayout.Alignment.TRAILING));
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.jTabbedPane1, GroupLayout.Alignment.TRAILING));
    }

    public void mGuardar() {
        if (!mVerifica()) {
            int n = JOptionPane.showInternalConfirmDialog(this, "Esta seguro de grabar?", "CONFIRMAR", 0, 1, new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/Question.png"))));
            if (n == 0) {
                String sql = " INSERT INTO `h_aj_encuesta` ( `IdProfesional`,`IdEspecialidad`,`IdAtencion`,`IdUsuarioA`,`FechaR`,`Vive`,`Convive`,`EstPadre`,             `EstMadre`,`EstPareja`,`TrabajoPadre`,`TrabajoMadre`,`TrabajoPareja`,`OcupacionPareja`,`OcupacionPadres`,             `ApoyoSubsidio`,`Persepcion`,`EnergiaElec`,`Agua`,`Hacinamiento`,`Estudia`,`NInstitucion`,`NivelEst`,`Grado`,             `AnioAprobado`,`ProblemasEsc`,`AnioRepetido`,`ViolEscolar`,`Desercion`,`EduNoFormal`,`ActTrabajo`,             `EdadTrabajo`,`TrabInfantil`,`TrabJuvenil`,`Aceptacion`,`Pareja`,`ViolPareja`,`Amigos`,`OtrasActi`,`SuenoNormal`,             `Horas`,`Alimentacion`,`ComidaDia`,`Fuma`,`Alcohol`,`Sustancias`,`CualesSust`,`Conduce`,`Mestrua`,`FechaMest`,`CicloReg`,             `Dismenorrea`,`FlujoPeneana`,`ITS`,`CualITS`,`Tratamiento`,`Sexualidad`,`ParejaSex`,`EdadRelSex`,`Anticoncepcion`,             `CualesAnt`,`SitEmocional`,`Animo`,`Referente`,`RedesApoyo`,`TelAdulto`,`CelAdulto`,`UsuarioS`) VALUES ( '" + Principal.usuarioSistemaDTO.getIdUsuarioSistema() + "','" + Principal.informacionGeneralPrincipalDTO.getIdEspecialidad() + "','" + clasesHistoriaCE.informacionAgendaMedicaDTO.getIdAtencion() + "','" + clasesHistoriaCE.informacionAgendaMedicaDTO.getIdUsuarioAtendido() + "','" + this.xmt.formatoAMD.format(this.xmt.getFechaActual()) + "','Vive','Convive','" + this.xmt.OptionButtonSelected(this.EstPadre) + "','" + this.xmt.OptionButtonSelected(this.EstMadre) + "',        '" + this.xmt.OptionButtonSelected(this.EstPareja) + "','" + this.xmt.OptionButtonSelected(this.TrabPadre) + "','" + this.xmt.OptionButtonSelected(this.TrabMadre) + "','" + this.xmt.OptionButtonSelected(this.TrabPareja) + "','" + this.JTFProPareja.getText() + "','" + this.JTFProPadres.getText() + "','" + this.xmt.OptionButtonSelected(this.ApoyoSocial) + "','" + this.JCPersepcion.getSelectedItem() + "',        '" + this.xmt.OptionButtonSelected(this.Energia) + "','" + this.xmt.OptionButtonSelected(this.Agua) + "','" + this.xmt.OptionButtonSelected(this.Hacinamiento) + "','" + this.xmt.OptionButtonSelected(this.Estudia) + "','" + this.JTFInstitucion.getText() + "','" + this.jComboBox1.getSelectedItem() + "','" + this.JTFGrado.getText() + "','" + this.JTFAprobado.getText() + "','" + this.xmt.OptionButtonSelected(this.Problemas) + "','" + this.JTFRepetido.getText() + "',        '" + this.xmt.OptionButtonSelected(this.ViolenciaEsc) + "','" + this.xmt.OptionButtonSelected(this.Desercion) + "','" + this.xmt.OptionButtonSelected(this.EduNoFormal) + "','" + this.JCBTrabajo.getSelectedItem() + "','" + this.JTFEdadInicio.getText() + "','" + this.xmt.OptionButtonSelected(this.TrabInfantil) + "','" + this.xmt.OptionButtonSelected(this.TrabJuvenil) + "','" + this.JCBAceptacion.getSelectedItem() + "','" + this.xmt.OptionButtonSelected(this.Pareja) + "',         '" + this.xmt.OptionButtonSelected(this.Violencia) + "','" + this.xmt.OptionButtonSelected(this.Amigos) + "','" + this.JTFActividades.getText() + "','" + this.xmt.OptionButtonSelected(this.Suenio) + "','" + this.JTFHoras.getText() + "','" + this.xmt.OptionButtonSelected(this.Alimentacion) + "','" + this.JTFComida.getText() + "','" + this.xmt.OptionButtonSelected(this.Fuma) + "','" + this.xmt.OptionButtonSelected(this.Alcoho) + "','" + this.xmt.OptionButtonSelected(this.Sustancias) + "',        '" + this.JTFSustancias.getText() + "','" + this.xmt.OptionButtonSelected(this.Conduce) + "','" + this.xmt.OptionButtonSelected(this.Mestruacion) + "','" + this.JTFFechaMest.getText() + "','" + this.xmt.OptionButtonSelected(this.Ciclo) + "','" + this.xmt.OptionButtonSelected(this.Dismenorrea) + "','" + this.xmt.OptionButtonSelected(this.Peneana) + "','" + this.xmt.OptionButtonSelected(this.ITS) + "','" + this.JTFITS.getText() + "','" + this.xmt.OptionButtonSelected(this.TratamientoIts) + "','" + this.JCBRelSex.getSelectedItem() + "',        '" + this.JCBRelSex1.getSelectedItem() + "','" + this.JTFEdadRel.getText() + "','" + this.xmt.OptionButtonSelected(this.Anticoncepcion) + "','" + this.JTFEdadRel1.getText() + "','" + this.JCBRelSex2.getSelectedItem() + "','Animo','Referente','" + this.xmt.OptionButtonSelected(this.Apoyo) + "',        '" + this.JTFCelPadre.getText() + "','" + this.JTFTelPadre.getText() + "','" + Principal.usuarioSistemaDTO.getLogin() + "') ";
                this.xct.ejecutarSQL(sql);
                this.xct.cerrarConexionBd();
                mBuscaHistorico();
                this.xmt.cambiarEstadoValidadoItemHC(getName(), 1, true);
                return;
            }
            return;
        }
        JOptionPane.showInternalMessageDialog(this, "Información ya se encuentra guardada", "VERIFICAR", 1, new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/Information.png"))));
    }

    private boolean mVerifica() {
        boolean xExite = false;
        String sql = "SELECT IdAtencion FROM `h_aj_encuesta` WHERE (IdAtencion='" + clasesHistoriaCE.informacionAgendaMedicaDTO.getIdAtencion() + "' AND Estado=1)";
        ResultSet xrs = this.xct.traerRs(sql);
        try {
            if (xrs.next()) {
                xrs.first();
                this.xmt.cambiarEstadoValidadoItemHC(getName(), 1, true);
                xExite = true;
            }
            xrs.close();
            this.xct.cerrarConexionBd();
        } catch (SQLException ex) {
            Logger.getLogger(JIFAdultoJoven2.class.getName()).log(Level.SEVERE, (String) null, (Throwable) ex);
        }
        return xExite;
    }

    /* JADX WARN: Type inference failed for: r4v1, types: [java.lang.Object[], java.lang.Object[][]] */
    private void mCrearModeloDatos() {
        this.xmodelo = new DefaultTableModel(new Object[0], new String[]{"IdAtencion", "Fecha", "Profesional", "Especialidad"}) { // from class: Historia.JIFAdultoJoven2.1
            Class[] types = {Long.class, String.class, String.class, String.class};
            boolean[] canEdit = {false, false, false, false};

            public Class getColumnClass(int columnIndex) {
                return this.types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return this.canEdit[columnIndex];
            }
        };
        this.JTHistorio.setModel(this.xmodelo);
        this.JTHistorio.getColumnModel().getColumn(0).setPreferredWidth(10);
        this.JTHistorio.getColumnModel().getColumn(1).setPreferredWidth(50);
        this.JTHistorio.getColumnModel().getColumn(2).setPreferredWidth(250);
        this.JTHistorio.getColumnModel().getColumn(3).setPreferredWidth(30);
    }

    private void mBuscaHistorico() {
        mCrearModeloDatos();
        String sql = "SELECT `h_aj_encuesta`.`IdAtencion`, `h_aj_encuesta`.`FechaR`, `profesional1`.`NProfesional`, `profesional1`.`Especialidad`FROM    `h_aj_encuesta` INNER JOIN `profesional1`         ON (`h_aj_encuesta`.`IdProfesional` = `profesional1`.`Id_Persona`) AND (`h_aj_encuesta`.`IdEspecialidad` = `profesional1`.`IdEspecialidad`)WHERE (`h_aj_encuesta`.`IdUsuarioA` ='" + clasesHistoriaCE.informacionAgendaMedicaDTO.getIdUsuarioAtendido() + "'  AND `h_aj_encuesta`.`Estado` =1) ORDER BY FechaR DESC;";
        ResultSet xrs = this.xct.traerRs(sql);
        try {
            if (xrs.next()) {
                xrs.beforeFirst();
                int n = 0;
                while (xrs.next()) {
                    this.xmodelo.addRow(this.xdato);
                    this.xmodelo.setValueAt(xrs.getString(1), n, 0);
                    this.xmodelo.setValueAt(xrs.getString(2), n, 1);
                    this.xmodelo.setValueAt(xrs.getString(3), n, 2);
                    this.xmodelo.setValueAt(xrs.getString(4), n, 3);
                    n++;
                }
            }
            xrs.close();
            this.xct.cerrarConexionBd();
        } catch (SQLException ex) {
            Logger.getLogger(JIFAdultoJoven2.class.getName()).log(Level.SEVERE, (String) null, (Throwable) ex);
        }
    }

    /* JADX INFO: loaded from: GenomaP.jar:Historia/JIFAdultoJoven2$Option.class */
    private class Option<T> implements Comparable<T> {
        private String label;
        private T value;

        public Option(String label, T value) {
            this.label = label;
            this.value = value;
        }

        public String toString() {
            return this.label;
        }

        @Override // java.lang.Comparable
        public int compareTo(T o) {
            return 0;
        }
    }
}
