package Historia;

import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.awt.Font;
import java.text.DecimalFormat;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JFormattedTextField;
import javax.swing.JPanel;
import javax.swing.LayoutStyle;
import javax.swing.border.Border;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/* JADX INFO: loaded from: GenomaP.jar:Historia/JP_PyP_Ayudas_Dx.class */
public class JP_PyP_Ayudas_Dx extends JPanel {
    private JDateChooser JDR_FColesterolHDL;
    private JDateChooser JDR_FColesterolLDL;
    private JDateChooser JDR_FColesterolTotal;
    private JDateChooser JDR_FCreatinina;
    private JDateChooser JDR_FGlicemia;
    private JDateChooser JDR_FHGlicosilada;
    private JDateChooser JDR_FMicroalbumina;
    private JDateChooser JDR_FTrigliceridos;
    private JPanel JPIColesterolHDL;
    private JPanel JPIColesterolLDL;
    private JPanel JPIColesterolTotal;
    private JPanel JPICreatinina;
    private JPanel JPIGlicemia;
    private JPanel JPIHGlicosilada;
    private JPanel JPIMicroalbumina;
    private JPanel JPITrigliceridos;
    private JFormattedTextField JTFFR_VColesterolHDL;
    private JFormattedTextField JTFFR_VColesterolLDL;
    private JFormattedTextField JTFFR_VColesterolTotal;
    private JFormattedTextField JTFFR_VCreatinina;
    private JFormattedTextField JTFFR_VGlicemia;
    private JFormattedTextField JTFFR_VHGlicosilada;
    private JFormattedTextField JTFFR_VMicroalbumina;
    private JFormattedTextField JTFFR_VTrigliceridos;

    public JP_PyP_Ayudas_Dx() {
        initComponents();
    }

    private void initComponents() {
        this.JPICreatinina = new JPanel();
        this.JDR_FCreatinina = new JDateChooser();
        this.JTFFR_VCreatinina = new JFormattedTextField();
        this.JPIMicroalbumina = new JPanel();
        this.JDR_FMicroalbumina = new JDateChooser();
        this.JTFFR_VMicroalbumina = new JFormattedTextField();
        this.JPIGlicemia = new JPanel();
        this.JDR_FGlicemia = new JDateChooser();
        this.JTFFR_VGlicemia = new JFormattedTextField();
        this.JPIHGlicosilada = new JPanel();
        this.JDR_FHGlicosilada = new JDateChooser();
        this.JTFFR_VHGlicosilada = new JFormattedTextField();
        this.JPIColesterolTotal = new JPanel();
        this.JDR_FColesterolTotal = new JDateChooser();
        this.JTFFR_VColesterolTotal = new JFormattedTextField();
        this.JPIColesterolHDL = new JPanel();
        this.JDR_FColesterolHDL = new JDateChooser();
        this.JTFFR_VColesterolHDL = new JFormattedTextField();
        this.JPIColesterolLDL = new JPanel();
        this.JDR_FColesterolLDL = new JDateChooser();
        this.JTFFR_VColesterolLDL = new JFormattedTextField();
        this.JPITrigliceridos = new JPanel();
        this.JDR_FTrigliceridos = new JDateChooser();
        this.JTFFR_VTrigliceridos = new JFormattedTextField();
        this.JPICreatinina.setBorder(BorderFactory.createTitledBorder((Border) null, "CREATININA", 2, 0, new Font("Arial", 1, 12), new Color(255, 0, 0)));
        this.JDR_FCreatinina.setBorder(BorderFactory.createTitledBorder((Border) null, "Fecha", 0, 0, new Font("Arial", 1, 12), new Color(0, 0, 255)));
        this.JDR_FCreatinina.setToolTipText("Fecha Creatinina");
        this.JDR_FCreatinina.setDateFormatString("dd/MM/yyyy");
        this.JDR_FCreatinina.setFont(new Font("Arial", 1, 12));
        this.JTFFR_VCreatinina.setBorder(BorderFactory.createTitledBorder((Border) null, "Valor", 0, 0, new Font("Arial", 1, 12), new Color(0, 0, 255)));
        this.JTFFR_VCreatinina.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0.00"))));
        this.JTFFR_VCreatinina.setHorizontalAlignment(4);
        this.JTFFR_VCreatinina.setToolTipText("Valor Creatinina");
        this.JTFFR_VCreatinina.setFont(new Font("Arial", 1, 12));
        GroupLayout JPICreatininaLayout = new GroupLayout(this.JPICreatinina);
        this.JPICreatinina.setLayout(JPICreatininaLayout);
        JPICreatininaLayout.setHorizontalGroup(JPICreatininaLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(JPICreatininaLayout.createSequentialGroup().addContainerGap(-1, 32767).addComponent(this.JDR_FCreatinina, -2, 110, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JTFFR_VCreatinina, -2, 71, -2)));
        JPICreatininaLayout.setVerticalGroup(JPICreatininaLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.JDR_FCreatinina, -2, 50, -2).addComponent(this.JTFFR_VCreatinina, -2, 50, -2));
        this.JDR_FCreatinina.getAccessibleContext().setAccessibleName("Fecha Creatinina");
        this.JTFFR_VCreatinina.getAccessibleContext().setAccessibleName("Valor Creatinina");
        this.JPIMicroalbumina.setBorder(BorderFactory.createTitledBorder((Border) null, "MICROALBUMINA", 2, 0, new Font("Arial", 1, 12), new Color(255, 0, 0)));
        this.JDR_FMicroalbumina.setBorder(BorderFactory.createTitledBorder((Border) null, "Fecha", 0, 0, new Font("Arial", 1, 12), new Color(0, 0, 255)));
        this.JDR_FMicroalbumina.setToolTipText("Fecha Microalbumina");
        this.JDR_FMicroalbumina.setDateFormatString("dd/MM/yyyy");
        this.JDR_FMicroalbumina.setFont(new Font("Arial", 1, 12));
        this.JTFFR_VMicroalbumina.setBorder(BorderFactory.createTitledBorder((Border) null, "Valor", 0, 0, new Font("Arial", 1, 12), new Color(0, 0, 255)));
        this.JTFFR_VMicroalbumina.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0.00"))));
        this.JTFFR_VMicroalbumina.setHorizontalAlignment(4);
        this.JTFFR_VMicroalbumina.setToolTipText("Valor Microalbumina");
        this.JTFFR_VMicroalbumina.setFont(new Font("Arial", 1, 12));
        GroupLayout JPIMicroalbuminaLayout = new GroupLayout(this.JPIMicroalbumina);
        this.JPIMicroalbumina.setLayout(JPIMicroalbuminaLayout);
        JPIMicroalbuminaLayout.setHorizontalGroup(JPIMicroalbuminaLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(JPIMicroalbuminaLayout.createSequentialGroup().addContainerGap(-1, 32767).addComponent(this.JDR_FMicroalbumina, -2, 110, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JTFFR_VMicroalbumina, -2, 71, -2)));
        JPIMicroalbuminaLayout.setVerticalGroup(JPIMicroalbuminaLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.JDR_FMicroalbumina, -2, 50, -2).addComponent(this.JTFFR_VMicroalbumina, -2, 50, -2));
        this.JDR_FMicroalbumina.getAccessibleContext().setAccessibleName("Fecha Microalbumina");
        this.JTFFR_VMicroalbumina.getAccessibleContext().setAccessibleName("Valor Microalbumina");
        this.JPIGlicemia.setBorder(BorderFactory.createTitledBorder((Border) null, "GLICEMIA", 2, 0, new Font("Arial", 1, 12), new Color(255, 0, 0)));
        this.JDR_FGlicemia.setBorder(BorderFactory.createTitledBorder((Border) null, "Fecha", 0, 0, new Font("Arial", 1, 12), new Color(0, 0, 255)));
        this.JDR_FGlicemia.setToolTipText("Fecha Glicemia");
        this.JDR_FGlicemia.setDateFormatString("dd/MM/yyyy");
        this.JDR_FGlicemia.setFont(new Font("Arial", 1, 12));
        this.JTFFR_VGlicemia.setBorder(BorderFactory.createTitledBorder((Border) null, "Valor", 0, 0, new Font("Arial", 1, 12), new Color(0, 0, 255)));
        this.JTFFR_VGlicemia.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0.00"))));
        this.JTFFR_VGlicemia.setHorizontalAlignment(4);
        this.JTFFR_VGlicemia.setToolTipText("Valor Glicemia");
        this.JTFFR_VGlicemia.setFont(new Font("Arial", 1, 12));
        GroupLayout JPIGlicemiaLayout = new GroupLayout(this.JPIGlicemia);
        this.JPIGlicemia.setLayout(JPIGlicemiaLayout);
        JPIGlicemiaLayout.setHorizontalGroup(JPIGlicemiaLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(JPIGlicemiaLayout.createSequentialGroup().addContainerGap(-1, 32767).addComponent(this.JDR_FGlicemia, -2, 110, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JTFFR_VGlicemia, -2, 71, -2)));
        JPIGlicemiaLayout.setVerticalGroup(JPIGlicemiaLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.JDR_FGlicemia, -2, 50, -2).addComponent(this.JTFFR_VGlicemia, -2, 50, -2));
        this.JDR_FGlicemia.getAccessibleContext().setAccessibleName("Fecha Glicemia");
        this.JTFFR_VGlicemia.getAccessibleContext().setAccessibleName("Valor Glicemia");
        this.JPIHGlicosilada.setBorder(BorderFactory.createTitledBorder((Border) null, "HEMOGLOBINA GLICOSILADA", 2, 0, new Font("Arial", 1, 12), new Color(255, 0, 0)));
        this.JDR_FHGlicosilada.setBorder(BorderFactory.createTitledBorder((Border) null, "Fecha", 0, 0, new Font("Arial", 1, 12), new Color(0, 0, 255)));
        this.JDR_FHGlicosilada.setToolTipText("Fecha Hemoglobina Glicosilada");
        this.JDR_FHGlicosilada.setDateFormatString("dd/MM/yyyy");
        this.JDR_FHGlicosilada.setFont(new Font("Arial", 1, 12));
        this.JTFFR_VHGlicosilada.setBorder(BorderFactory.createTitledBorder((Border) null, "Valor", 0, 0, new Font("Arial", 1, 12), new Color(0, 0, 255)));
        this.JTFFR_VHGlicosilada.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0.00"))));
        this.JTFFR_VHGlicosilada.setHorizontalAlignment(4);
        this.JTFFR_VHGlicosilada.setToolTipText("Valor Hemoglobina Glicosilada");
        this.JTFFR_VHGlicosilada.setFont(new Font("Arial", 1, 12));
        GroupLayout JPIHGlicosiladaLayout = new GroupLayout(this.JPIHGlicosilada);
        this.JPIHGlicosilada.setLayout(JPIHGlicosiladaLayout);
        JPIHGlicosiladaLayout.setHorizontalGroup(JPIHGlicosiladaLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(JPIHGlicosiladaLayout.createSequentialGroup().addContainerGap(-1, 32767).addComponent(this.JDR_FHGlicosilada, -2, 110, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JTFFR_VHGlicosilada, -2, 71, -2)));
        JPIHGlicosiladaLayout.setVerticalGroup(JPIHGlicosiladaLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.JDR_FHGlicosilada, -2, 50, -2).addComponent(this.JTFFR_VHGlicosilada, -2, 50, -2));
        this.JDR_FHGlicosilada.getAccessibleContext().setAccessibleName("Fecha Hemoglobina Glicosilada");
        this.JTFFR_VHGlicosilada.getAccessibleContext().setAccessibleName("Valor Hemoglobina Glicosilada");
        this.JPIColesterolTotal.setBorder(BorderFactory.createTitledBorder((Border) null, "COLESTEROL TOTAL", 2, 0, new Font("Arial", 1, 12), new Color(255, 0, 0)));
        this.JDR_FColesterolTotal.setBorder(BorderFactory.createTitledBorder((Border) null, "Fecha", 0, 0, new Font("Arial", 1, 12), new Color(0, 0, 255)));
        this.JDR_FColesterolTotal.setToolTipText("Fecha Colesterol Total");
        this.JDR_FColesterolTotal.setDateFormatString("dd/MM/yyyy");
        this.JDR_FColesterolTotal.setFont(new Font("Arial", 1, 12));
        this.JTFFR_VColesterolTotal.setBorder(BorderFactory.createTitledBorder((Border) null, "Valor", 0, 0, new Font("Arial", 1, 12), new Color(0, 0, 255)));
        this.JTFFR_VColesterolTotal.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0.00"))));
        this.JTFFR_VColesterolTotal.setHorizontalAlignment(4);
        this.JTFFR_VColesterolTotal.setToolTipText("Valor Colesterol Total");
        this.JTFFR_VColesterolTotal.setFont(new Font("Arial", 1, 12));
        GroupLayout JPIColesterolTotalLayout = new GroupLayout(this.JPIColesterolTotal);
        this.JPIColesterolTotal.setLayout(JPIColesterolTotalLayout);
        JPIColesterolTotalLayout.setHorizontalGroup(JPIColesterolTotalLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(JPIColesterolTotalLayout.createSequentialGroup().addContainerGap(-1, 32767).addComponent(this.JDR_FColesterolTotal, -2, 110, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JTFFR_VColesterolTotal, -2, 71, -2)));
        JPIColesterolTotalLayout.setVerticalGroup(JPIColesterolTotalLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.JDR_FColesterolTotal, -2, 50, -2).addComponent(this.JTFFR_VColesterolTotal, -2, 50, -2));
        this.JDR_FColesterolTotal.getAccessibleContext().setAccessibleName("Fecha Colesterol Total");
        this.JTFFR_VColesterolTotal.getAccessibleContext().setAccessibleName("Valor Colesterol Total");
        this.JPIColesterolHDL.setBorder(BorderFactory.createTitledBorder((Border) null, "COLESTEROL HDL", 2, 0, new Font("Arial", 1, 12), new Color(255, 0, 0)));
        this.JDR_FColesterolHDL.setBorder(BorderFactory.createTitledBorder((Border) null, "Fecha", 0, 0, new Font("Arial", 1, 12), new Color(0, 0, 255)));
        this.JDR_FColesterolHDL.setToolTipText("Fecha Colesterol HDL");
        this.JDR_FColesterolHDL.setDateFormatString("dd/MM/yyyy");
        this.JDR_FColesterolHDL.setFont(new Font("Arial", 1, 12));
        this.JTFFR_VColesterolHDL.setBorder(BorderFactory.createTitledBorder((Border) null, "Valor", 0, 0, new Font("Arial", 1, 12), new Color(0, 0, 255)));
        this.JTFFR_VColesterolHDL.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0.00"))));
        this.JTFFR_VColesterolHDL.setHorizontalAlignment(4);
        this.JTFFR_VColesterolHDL.setToolTipText("Valor Colesterol HDL");
        this.JTFFR_VColesterolHDL.setFont(new Font("Arial", 1, 12));
        GroupLayout JPIColesterolHDLLayout = new GroupLayout(this.JPIColesterolHDL);
        this.JPIColesterolHDL.setLayout(JPIColesterolHDLLayout);
        JPIColesterolHDLLayout.setHorizontalGroup(JPIColesterolHDLLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(JPIColesterolHDLLayout.createSequentialGroup().addGap(4, 4, 4).addComponent(this.JDR_FColesterolHDL, -2, 110, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JTFFR_VColesterolHDL, -2, 71, -2).addContainerGap(-1, 32767)));
        JPIColesterolHDLLayout.setVerticalGroup(JPIColesterolHDLLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.JDR_FColesterolHDL, -2, 50, -2).addComponent(this.JTFFR_VColesterolHDL, -2, 50, -2));
        this.JDR_FColesterolHDL.getAccessibleContext().setAccessibleName("Fecha Colesterol HDL");
        this.JTFFR_VColesterolHDL.getAccessibleContext().setAccessibleName("Valor Colesterol HDL");
        this.JPIColesterolLDL.setBorder(BorderFactory.createTitledBorder((Border) null, "COLESTEROL LDL", 2, 0, new Font("Arial", 1, 12), new Color(255, 0, 0)));
        this.JDR_FColesterolLDL.setBorder(BorderFactory.createTitledBorder((Border) null, "Fecha", 0, 0, new Font("Arial", 1, 12), new Color(0, 0, 255)));
        this.JDR_FColesterolLDL.setToolTipText("Fecha Colesterol LDL");
        this.JDR_FColesterolLDL.setDateFormatString("dd/MM/yyyy");
        this.JDR_FColesterolLDL.setFont(new Font("Arial", 1, 12));
        this.JTFFR_VColesterolLDL.setBorder(BorderFactory.createTitledBorder((Border) null, "Valor", 0, 0, new Font("Arial", 1, 12), new Color(0, 0, 255)));
        this.JTFFR_VColesterolLDL.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0.00"))));
        this.JTFFR_VColesterolLDL.setHorizontalAlignment(4);
        this.JTFFR_VColesterolLDL.setToolTipText("Valor Colesterol LDL");
        this.JTFFR_VColesterolLDL.setFont(new Font("Arial", 1, 12));
        GroupLayout JPIColesterolLDLLayout = new GroupLayout(this.JPIColesterolLDL);
        this.JPIColesterolLDL.setLayout(JPIColesterolLDLLayout);
        JPIColesterolLDLLayout.setHorizontalGroup(JPIColesterolLDLLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(JPIColesterolLDLLayout.createSequentialGroup().addGap(4, 4, 4).addComponent(this.JDR_FColesterolLDL, -2, 110, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JTFFR_VColesterolLDL, -2, 71, -2).addContainerGap(-1, 32767)));
        JPIColesterolLDLLayout.setVerticalGroup(JPIColesterolLDLLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.JDR_FColesterolLDL, -2, 50, -2).addComponent(this.JTFFR_VColesterolLDL, -2, 50, -2));
        this.JDR_FColesterolLDL.getAccessibleContext().setAccessibleName("Fecha Colesterol LDL");
        this.JTFFR_VColesterolLDL.getAccessibleContext().setAccessibleName("Valor Colesterol LDL");
        this.JPITrigliceridos.setBorder(BorderFactory.createTitledBorder((Border) null, "TRIGLICERIDOS", 2, 0, new Font("Arial", 1, 12), new Color(255, 0, 0)));
        this.JDR_FTrigliceridos.setBorder(BorderFactory.createTitledBorder((Border) null, "Fecha", 0, 0, new Font("Arial", 1, 12), new Color(0, 0, 255)));
        this.JDR_FTrigliceridos.setToolTipText("Fecha Trigliceridos");
        this.JDR_FTrigliceridos.setDateFormatString("dd/MM/yyyy");
        this.JDR_FTrigliceridos.setFont(new Font("Arial", 1, 12));
        this.JTFFR_VTrigliceridos.setBorder(BorderFactory.createTitledBorder((Border) null, "Valor", 0, 0, new Font("Arial", 1, 12), new Color(0, 0, 255)));
        this.JTFFR_VTrigliceridos.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0.00"))));
        this.JTFFR_VTrigliceridos.setHorizontalAlignment(4);
        this.JTFFR_VTrigliceridos.setToolTipText("Valor Trigliceridos");
        this.JTFFR_VTrigliceridos.setFont(new Font("Arial", 1, 12));
        GroupLayout JPITrigliceridosLayout = new GroupLayout(this.JPITrigliceridos);
        this.JPITrigliceridos.setLayout(JPITrigliceridosLayout);
        JPITrigliceridosLayout.setHorizontalGroup(JPITrigliceridosLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(JPITrigliceridosLayout.createSequentialGroup().addContainerGap(-1, 32767).addComponent(this.JDR_FTrigliceridos, -2, 110, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JTFFR_VTrigliceridos, -2, 71, -2).addContainerGap()));
        JPITrigliceridosLayout.setVerticalGroup(JPITrigliceridosLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.JDR_FTrigliceridos, -2, 50, -2).addComponent(this.JTFFR_VTrigliceridos, -2, 50, -2));
        this.JDR_FTrigliceridos.getAccessibleContext().setAccessibleName("Fecha Trigliceridos");
        this.JTFFR_VTrigliceridos.getAccessibleContext().setAccessibleName("Valor Trigliceridos");
        GroupLayout layout = new GroupLayout(this);
        setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false).addComponent(this.JPICreatinina, -1, -1, 32767).addComponent(this.JPIColesterolTotal, -1, -1, 32767)).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false).addComponent(this.JPIMicroalbumina, -1, -1, 32767).addComponent(this.JPIColesterolHDL, -1, 0, 32767)).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, -1, 32767).addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.JPIGlicemia, GroupLayout.Alignment.TRAILING, -2, -1, -2).addComponent(this.JPIColesterolLDL, -2, 209, -2)).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false).addComponent(this.JPITrigliceridos, -1, 0, 32767).addComponent(this.JPIHGlicosilada, -1, -1, 32767)).addContainerGap(-1, 32767)));
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false).addComponent(this.JPICreatinina, -1, -1, 32767).addComponent(this.JPIMicroalbumina, -1, -1, 32767).addComponent(this.JPIGlicemia, -1, -1, 32767)).addComponent(this.JPIHGlicosilada, -2, -1, -2)).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.JPIColesterolTotal, -2, -1, -2).addComponent(this.JPIColesterolHDL, -2, -1, -2).addComponent(this.JPITrigliceridos, -2, -1, -2).addComponent(this.JPIColesterolLDL, -2, -1, -2)).addContainerGap(50, 32767)));
    }
}
