package Historia;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.border.Border;

/* JADX INFO: loaded from: GenomaP.jar:Historia/JPOft_OjoExa2.class */
public class JPOft_OjoExa2 extends JPanel {
    public ButtonGroup Capsula;
    public ButtonGroup CuerpoExtranio;
    public ButtonGroup Esclerosis;
    public JComboBox JCBCamara;
    public JComboBox JCBCristalino;
    public JComboBox JCBNegra;
    public JCheckBox JCHAtrapado;
    public JCheckBox JCHCECentral;
    public JCheckBox JCHCEPeriferico;
    public JCheckBox JCHCEProfundo;
    public JCheckBox JCHCESuperficial;
    public JCheckBox JCHCamAnt;
    public JCheckBox JCHCentral;
    public JCheckBox JCHCrisBlanco;
    public JCheckBox JCHCrisTrasparente;
    public JCheckBox JCHDepSube;
    public JCheckBox JCHDiscordia;
    public JCheckBox JCHEstronal;
    public JCheckBox JCHGCarnero;
    public JCheckBox JCHGeneralizada;
    public JCheckBox JCHInflamacion;
    public JCheckBox JCHMicroq;
    public JCheckBox JCHNegraCentral;
    public JCheckBox JCHOpaCueiforme;
    public JCheckBox JCHOpaNuclear;
    public JCheckBox JCHOpaSutural;
    public JCheckBox JCHPeriferico;
    public JCheckBox JCHPigmentados;
    public JCheckBox JCHPliegues;
    public JCheckBox JCHPolarPost;
    public JCheckBox JCHSaco;
    public JCheckBox JCHSulcus;
    public JCheckBox JCHTrasparente;
    public JCheckBox JCHUlCentral;
    public JCheckBox JCHUlPeriferico;
    public JRadioButton JRBEsclPlus1;
    public JRadioButton JRBEsclPlus2;
    public JRadioButton JRBEsclPlus3;
    public JRadioButton JRBEsclPlus4;
    public JRadioButton JRBNTrasparente;
    public JRadioButton JRBOpaAnterior;
    public JRadioButton JRBOpaPosterior;
    public JRadioButton JRBOpaca;
    public JRadioButton JRBUnico;
    public JRadioButton JRBUnico1;
    public JTextField JTFAng1;
    public JTextField JTFAng2;
    public JTextField JTFAng3;
    public JTextField JTFAng4;
    public JTextField JTFOtros;
    public JTextField JTFOtrosCornea;
    public JTextField JTFOtrosCristalino;
    public JTextField JTFPIO;
    public ButtonGroup Opacidad;
    private JLabel jLabel1;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JPanel jPanel1;
    private JPanel jPanel10;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JPanel jPanel5;
    private JPanel jPanel6;
    private JPanel jPanel7;
    private JPanel jPanel8;
    private JPanel jPanel9;

    public JPOft_OjoExa2(String xNombre) {
        initComponents();
        setBorder(BorderFactory.createTitledBorder((Border) null, xNombre, 0, 0, new Font("Arial", 1, 14), Color.red));
    }

    private void initComponents() {
        this.Capsula = new ButtonGroup();
        this.Opacidad = new ButtonGroup();
        this.Esclerosis = new ButtonGroup();
        this.CuerpoExtranio = new ButtonGroup();
        this.jPanel1 = new JPanel();
        this.JCHTrasparente = new JCheckBox();
        this.JCHPliegues = new JCheckBox();
        this.jPanel2 = new JPanel();
        this.JCHCentral = new JCheckBox();
        this.JCHPeriferico = new JCheckBox();
        this.JCHGeneralizada = new JCheckBox();
        this.JCHMicroq = new JCheckBox();
        this.JCHEstronal = new JCheckBox();
        this.JCHInflamacion = new JCheckBox();
        this.JCHDepSube = new JCheckBox();
        this.jPanel3 = new JPanel();
        this.JCHGCarnero = new JCheckBox();
        this.JCHPigmentados = new JCheckBox();
        this.jPanel4 = new JPanel();
        this.JCHUlCentral = new JCheckBox();
        this.JCHUlPeriferico = new JCheckBox();
        this.jPanel5 = new JPanel();
        this.JCHCECentral = new JCheckBox();
        this.JCHCEPeriferico = new JCheckBox();
        this.JCHCESuperficial = new JCheckBox();
        this.JCHCEProfundo = new JCheckBox();
        this.JRBUnico = new JRadioButton();
        this.JRBUnico1 = new JRadioButton();
        this.JTFOtros = new JTextField();
        this.jPanel6 = new JPanel();
        this.jLabel1 = new JLabel();
        this.JCBCamara = new JComboBox();
        this.JCBCristalino = new JComboBox();
        this.jPanel7 = new JPanel();
        this.JCHNegraCentral = new JCheckBox();
        this.JCHDiscordia = new JCheckBox();
        this.JCBNegra = new JComboBox();
        this.JTFOtrosCornea = new JTextField();
        this.jPanel10 = new JPanel();
        this.JTFAng2 = new JTextField();
        this.JTFAng1 = new JTextField();
        this.JTFAng3 = new JTextField();
        this.JTFAng4 = new JTextField();
        this.jPanel8 = new JPanel();
        this.jLabel4 = new JLabel();
        this.JRBOpaca = new JRadioButton();
        this.JRBNTrasparente = new JRadioButton();
        this.JCHCamAnt = new JCheckBox();
        this.JCHSaco = new JCheckBox();
        this.JCHSulcus = new JCheckBox();
        this.JCHAtrapado = new JCheckBox();
        this.jLabel7 = new JLabel();
        this.jPanel9 = new JPanel();
        this.JCHCrisTrasparente = new JCheckBox();
        this.JCHCrisBlanco = new JCheckBox();
        this.jLabel5 = new JLabel();
        this.JRBOpaAnterior = new JRadioButton();
        this.JRBOpaPosterior = new JRadioButton();
        this.jLabel6 = new JLabel();
        this.JRBEsclPlus1 = new JRadioButton();
        this.JRBEsclPlus2 = new JRadioButton();
        this.JRBEsclPlus3 = new JRadioButton();
        this.JRBEsclPlus4 = new JRadioButton();
        this.JCHOpaCueiforme = new JCheckBox();
        this.JCHOpaNuclear = new JCheckBox();
        this.JCHOpaSutural = new JCheckBox();
        this.JCHPolarPost = new JCheckBox();
        this.JTFOtrosCristalino = new JTextField();
        this.JTFPIO = new JTextField();
        setPreferredSize(new Dimension(387, 630));
        this.jPanel1.setBorder(BorderFactory.createTitledBorder((Border) null, "Cornea", 0, 0, new Font("Arial", 1, 12), Color.red));
        this.JCHTrasparente.setFont(new Font("Arial", 1, 11));
        this.JCHTrasparente.setText("Trasparente");
        this.JCHTrasparente.setPreferredSize(new Dimension(113, 15));
        this.JCHPliegues.setFont(new Font("Arial", 1, 11));
        this.JCHPliegues.setText("Pliegues en Descement");
        this.jPanel2.setBorder(BorderFactory.createTitledBorder((Border) null, "Edema", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.JCHCentral.setFont(new Font("Arial", 1, 11));
        this.JCHCentral.setText("Central");
        this.JCHCentral.setPreferredSize(new Dimension(113, 15));
        this.JCHPeriferico.setFont(new Font("Arial", 1, 11));
        this.JCHPeriferico.setText("Periférico");
        this.JCHPeriferico.setPreferredSize(new Dimension(113, 15));
        this.JCHGeneralizada.setFont(new Font("Arial", 1, 11));
        this.JCHGeneralizada.setText("Generalizada");
        this.JCHGeneralizada.setPreferredSize(new Dimension(113, 15));
        this.JCHMicroq.setFont(new Font("Arial", 1, 11));
        this.JCHMicroq.setText("Microquistico");
        this.JCHMicroq.setPreferredSize(new Dimension(113, 15));
        this.JCHEstronal.setFont(new Font("Arial", 1, 11));
        this.JCHEstronal.setText("Estronal");
        this.JCHEstronal.setPreferredSize(new Dimension(113, 15));
        GroupLayout jPanel2Layout = new GroupLayout(this.jPanel2);
        this.jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addComponent(this.JCHGeneralizada, -2, 0, 32767).addContainerGap()).addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false).addComponent(this.JCHCentral, GroupLayout.Alignment.LEADING, -1, 95, 32767).addComponent(this.JCHPeriferico, GroupLayout.Alignment.LEADING, -2, 0, 32767)).addComponent(this.JCHEstronal, -2, 90, -2)).addGap(0, 12, 32767)).addComponent(this.JCHMicroq, -2, 0, 32767));
        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addComponent(this.JCHCentral, -2, -1, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JCHPeriferico, -2, -1, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JCHGeneralizada, -2, -1, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JCHMicroq, -2, -1, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JCHEstronal, -2, -1, -2)));
        this.JCHInflamacion.setFont(new Font("Arial", 1, 11));
        this.JCHInflamacion.setText("Inflam. Local Generalizada");
        this.JCHInflamacion.setPreferredSize(new Dimension(113, 15));
        this.JCHDepSube.setFont(new Font("Arial", 1, 11));
        this.JCHDepSube.setText("Depositos Subepiteliales");
        this.jPanel3.setBorder(BorderFactory.createTitledBorder((Border) null, "Depositos Endoteliales", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.JCHGCarnero.setFont(new Font("Arial", 1, 11));
        this.JCHGCarnero.setText("Grasa de Carnero");
        this.JCHGCarnero.setPreferredSize(new Dimension(113, 15));
        this.JCHPigmentados.setFont(new Font("Arial", 1, 11));
        this.JCHPigmentados.setText("Pigmentados");
        this.JCHPigmentados.setPreferredSize(new Dimension(113, 15));
        GroupLayout jPanel3Layout = new GroupLayout(this.jPanel3);
        this.jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel3Layout.createSequentialGroup().addComponent(this.JCHGCarnero, -2, 123, -2).addGap(4, 4, 4).addComponent(this.JCHPigmentados, -2, 102, -2).addGap(2, 2, 2)));
        jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel3Layout.createSequentialGroup().addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.JCHGCarnero, -2, -1, -2).addComponent(this.JCHPigmentados, -2, -1, -2)).addGap(1, 1, 1)));
        this.jPanel4.setBorder(BorderFactory.createTitledBorder((Border) null, "Ulceras", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.JCHUlCentral.setFont(new Font("Arial", 1, 11));
        this.JCHUlCentral.setText("Central");
        this.JCHUlCentral.setPreferredSize(new Dimension(113, 15));
        this.JCHUlPeriferico.setFont(new Font("Arial", 1, 11));
        this.JCHUlPeriferico.setText("Periférico");
        this.JCHUlPeriferico.setPreferredSize(new Dimension(113, 15));
        GroupLayout jPanel4Layout = new GroupLayout(this.jPanel4);
        this.jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel4Layout.createSequentialGroup().addComponent(this.JCHUlCentral, -2, 123, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, -1, 32767).addComponent(this.JCHUlPeriferico, -2, 87, -2).addGap(21, 21, 21)));
        jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel4Layout.createSequentialGroup().addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.JCHUlCentral, -2, -1, -2).addComponent(this.JCHUlPeriferico, -2, -1, -2)).addGap(1, 1, 1)));
        this.jPanel5.setBorder(BorderFactory.createTitledBorder((Border) null, "Cuerpo Extraño", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.JCHCECentral.setFont(new Font("Arial", 1, 11));
        this.JCHCECentral.setText("Central");
        this.JCHCECentral.setPreferredSize(new Dimension(113, 15));
        this.JCHCEPeriferico.setFont(new Font("Arial", 1, 11));
        this.JCHCEPeriferico.setText("Periférico");
        this.JCHCEPeriferico.setPreferredSize(new Dimension(113, 15));
        this.JCHCESuperficial.setFont(new Font("Arial", 1, 11));
        this.JCHCESuperficial.setText("Superficial");
        this.JCHCESuperficial.setPreferredSize(new Dimension(113, 15));
        this.JCHCEProfundo.setFont(new Font("Arial", 1, 11));
        this.JCHCEProfundo.setText("Profundo");
        this.JCHCEProfundo.setPreferredSize(new Dimension(113, 15));
        this.CuerpoExtranio.add(this.JRBUnico);
        this.JRBUnico.setFont(new Font("Arial", 1, 11));
        this.JRBUnico.setText("Único");
        this.JRBUnico.setName("1");
        this.CuerpoExtranio.add(this.JRBUnico1);
        this.JRBUnico1.setFont(new Font("Arial", 1, 11));
        this.JRBUnico1.setText("Varios");
        this.JRBUnico1.setName("2");
        GroupLayout jPanel5Layout = new GroupLayout(this.jPanel5);
        this.jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel5Layout.createSequentialGroup().addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false).addComponent(this.JCHCECentral, GroupLayout.Alignment.LEADING, -1, 95, 32767).addComponent(this.JCHCEPeriferico, GroupLayout.Alignment.LEADING, -2, 1, 32767)).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.JCHCESuperficial, -2, 88, -2).addComponent(this.JCHCEProfundo, -2, 102, -2)).addGap(14, 14, 14).addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.JRBUnico1).addComponent(this.JRBUnico)).addContainerGap(-1, 32767)));
        jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel5Layout.createSequentialGroup().addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel5Layout.createSequentialGroup().addComponent(this.JCHCECentral, -2, -1, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.JCHCEPeriferico, -2, -1, -2).addComponent(this.JCHCEProfundo, -2, -1, -2).addComponent(this.JRBUnico1, -2, 15, -2))).addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.JCHCESuperficial, -2, -1, -2).addComponent(this.JRBUnico, -2, 15, -2))).addGap(1, 1, 1)));
        this.JTFOtros.setFont(new Font("Arial", 1, 12));
        this.JTFOtros.setBorder(BorderFactory.createTitledBorder((Border) null, "Otros", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.jPanel6.setBorder(BorderFactory.createEtchedBorder());
        this.jLabel1.setFont(new Font("Arial", 1, 12));
        this.jLabel1.setText("Ángulo");
        this.JCBCamara.setFont(new Font("Arial", 1, 11));
        this.JCBCamara.setModel(new DefaultComboBoxModel(new String[]{" ", "I", "II", "III", "ATALAMIA"}));
        this.JCBCamara.setBorder(BorderFactory.createTitledBorder((Border) null, "Cámara", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.JCBCristalino.setFont(new Font("Arial", 1, 11));
        this.JCBCristalino.setModel(new DefaultComboBoxModel(new String[]{" ", "CENTRADO", "SUBLUXADO", "LUXADO", "AUSENTE O AFACO"}));
        this.JCBCristalino.setBorder(BorderFactory.createTitledBorder((Border) null, "Cristalino", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.jPanel7.setBorder(BorderFactory.createTitledBorder((Border) null, "Pupila", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.JCHNegraCentral.setFont(new Font("Arial", 1, 11));
        this.JCHNegraCentral.setText("Negra Central");
        this.JCHNegraCentral.setPreferredSize(new Dimension(113, 15));
        this.JCHNegraCentral.addActionListener(new ActionListener() { // from class: Historia.JPOft_OjoExa2.1
            public void actionPerformed(ActionEvent evt) {
                JPOft_OjoExa2.this.JCHNegraCentralActionPerformed(evt);
            }
        });
        this.JCHDiscordia.setFont(new Font("Arial", 1, 11));
        this.JCHDiscordia.setText("Discordia");
        this.JCHDiscordia.setPreferredSize(new Dimension(113, 15));
        this.JCBNegra.setModel(new DefaultComboBoxModel(new String[]{" ", "03", "04", "05", "06", "07", "08", "09", "10"}));
        this.JCBNegra.setEnabled(false);
        GroupLayout jPanel7Layout = new GroupLayout(this.jPanel7);
        this.jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel7Layout.createSequentialGroup().addComponent(this.JCHNegraCentral, -2, 106, -2).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.JCBNegra, -2, -1, -2).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.JCHDiscordia, -2, 80, -2)));
        jPanel7Layout.setVerticalGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel7Layout.createSequentialGroup().addGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.JCHNegraCentral, -2, -1, -2).addComponent(this.JCHDiscordia, -2, -1, -2).addComponent(this.JCBNegra, -2, -1, -2)).addGap(1, 1, 1)));
        this.JTFOtrosCornea.setFont(new Font("Arial", 1, 12));
        this.JTFOtrosCornea.setBorder(BorderFactory.createTitledBorder((Border) null, "Otros", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.jPanel10.setBackground(new Color(0, 0, 0));
        this.JTFAng2.setFont(new Font("Arial", 1, 11));
        this.JTFAng2.setHorizontalAlignment(0);
        this.JTFAng1.setFont(new Font("Arial", 1, 11));
        this.JTFAng1.setHorizontalAlignment(0);
        this.JTFAng3.setFont(new Font("Arial", 1, 11));
        this.JTFAng3.setHorizontalAlignment(0);
        this.JTFAng4.setFont(new Font("Arial", 1, 11));
        this.JTFAng4.setHorizontalAlignment(0);
        GroupLayout jPanel10Layout = new GroupLayout(this.jPanel10);
        this.jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(jPanel10Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel10Layout.createSequentialGroup().addComponent(this.JTFAng2, -2, 69, -2).addGap(2, 2, 2).addComponent(this.JTFAng1, -2, 69, -2)).addGroup(jPanel10Layout.createSequentialGroup().addComponent(this.JTFAng3, -2, 69, -2).addGap(2, 2, 2).addComponent(this.JTFAng4, -2, 69, -2)));
        jPanel10Layout.setVerticalGroup(jPanel10Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel10Layout.createSequentialGroup().addGroup(jPanel10Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.JTFAng2, -2, -1, -2).addComponent(this.JTFAng1, -2, -1, -2)).addGap(2, 2, 2).addGroup(jPanel10Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.JTFAng3, -2, -1, -2).addComponent(this.JTFAng4, -2, -1, -2))));
        GroupLayout jPanel6Layout = new GroupLayout(this.jPanel6);
        this.jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel6Layout.createSequentialGroup().addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel6Layout.createSequentialGroup().addContainerGap().addComponent(this.jLabel1).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jPanel10, -2, -1, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, -1, 32767).addComponent(this.JCBCamara, -2, 115, -2)).addGroup(GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup().addComponent(this.jPanel7, -1, -1, 32767).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JCBCristalino, -2, 115, -2)).addComponent(this.JTFOtrosCornea)).addGap(3, 3, 3)));
        jPanel6Layout.setVerticalGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel6Layout.createSequentialGroup().addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel6Layout.createSequentialGroup().addGap(2, 2, 2).addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.JCBCamara, -2, 37, -2).addComponent(this.jLabel1))).addComponent(this.jPanel10, -2, -1, -2)).addGap(2, 2, 2).addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.JCBCristalino, -2, 37, -2).addComponent(this.jPanel7, -2, -1, -2)).addGap(2, 2, 2).addComponent(this.JTFOtrosCornea).addGap(3, 3, 3)));
        this.jPanel8.setBorder(BorderFactory.createTitledBorder((Border) null, "Lente Intraocular", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.jLabel4.setFont(new Font("Arial", 1, 11));
        this.jLabel4.setText("Cápsula:");
        this.Capsula.add(this.JRBOpaca);
        this.JRBOpaca.setFont(new Font("Arial", 1, 11));
        this.JRBOpaca.setText("Opaca");
        this.JRBOpaca.setName("1");
        this.Capsula.add(this.JRBNTrasparente);
        this.JRBNTrasparente.setFont(new Font("Arial", 1, 11));
        this.JRBNTrasparente.setText("Trasparente");
        this.JRBNTrasparente.setName("2");
        this.JCHCamAnt.setFont(new Font("Arial", 1, 11));
        this.JCHCamAnt.setText("Cámara anterior");
        this.JCHCamAnt.setPreferredSize(new Dimension(113, 15));
        this.JCHSaco.setFont(new Font("Arial", 1, 11));
        this.JCHSaco.setText("Saco");
        this.JCHSaco.setPreferredSize(new Dimension(113, 15));
        this.JCHSulcus.setFont(new Font("Arial", 1, 11));
        this.JCHSulcus.setText("Sulcus");
        this.JCHSulcus.setPreferredSize(new Dimension(113, 15));
        this.JCHAtrapado.setFont(new Font("Arial", 1, 11));
        this.JCHAtrapado.setText("Atrapado");
        this.JCHAtrapado.setPreferredSize(new Dimension(113, 15));
        this.jLabel7.setFont(new Font("Arial", 1, 11));
        this.jLabel7.setText("Cámara Posterior:");
        GroupLayout jPanel8Layout = new GroupLayout(this.jPanel8);
        this.jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel8Layout.createSequentialGroup().addGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel8Layout.createSequentialGroup().addGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false).addComponent(this.JCHCamAnt, GroupLayout.Alignment.LEADING, -1, -1, 32767).addGroup(GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup().addContainerGap().addComponent(this.jLabel4).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.JRBOpaca))).addGap(8, 8, 8).addComponent(this.JRBNTrasparente)).addGroup(jPanel8Layout.createSequentialGroup().addComponent(this.JCHSaco, -2, 63, -2).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.JCHSulcus, -2, 65, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JCHAtrapado, -2, 79, -2)).addComponent(this.jLabel7)).addContainerGap(-1, 32767)));
        jPanel8Layout.setVerticalGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel8Layout.createSequentialGroup().addGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.JRBOpaca, -2, 15, -2).addGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jLabel4).addComponent(this.JRBNTrasparente, -2, 15, -2))).addGap(3, 3, 3).addComponent(this.JCHCamAnt, -2, -1, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 12, 32767).addComponent(this.jLabel7).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.JCHSaco, -2, -1, -2).addComponent(this.JCHSulcus, -2, -1, -2).addComponent(this.JCHAtrapado, -2, -1, -2)).addGap(1, 1, 1)));
        this.jPanel9.setBorder(BorderFactory.createTitledBorder((Border) null, "Cristalino", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.JCHCrisTrasparente.setFont(new Font("Arial", 1, 11));
        this.JCHCrisTrasparente.setText("Trasparente");
        this.JCHCrisTrasparente.setPreferredSize(new Dimension(113, 15));
        this.JCHCrisBlanco.setFont(new Font("Arial", 1, 11));
        this.JCHCrisBlanco.setText("Blanco");
        this.JCHCrisBlanco.setPreferredSize(new Dimension(113, 15));
        this.jLabel5.setFont(new Font("Arial", 1, 11));
        this.jLabel5.setText("Opacidad Capsular: ");
        this.Opacidad.add(this.JRBOpaAnterior);
        this.JRBOpaAnterior.setFont(new Font("Arial", 1, 11));
        this.JRBOpaAnterior.setText("Anterior");
        this.JRBOpaAnterior.setName("1");
        this.Opacidad.add(this.JRBOpaPosterior);
        this.JRBOpaPosterior.setFont(new Font("Arial", 1, 11));
        this.JRBOpaPosterior.setText("Posterior");
        this.JRBOpaPosterior.setName("2");
        this.jLabel6.setFont(new Font("Arial", 1, 11));
        this.jLabel6.setText("Esclerosis Nuclear:");
        this.Esclerosis.add(this.JRBEsclPlus1);
        this.JRBEsclPlus1.setFont(new Font("Arial", 1, 11));
        this.JRBEsclPlus1.setText("+");
        this.JRBEsclPlus1.setName("1");
        this.Esclerosis.add(this.JRBEsclPlus2);
        this.JRBEsclPlus2.setFont(new Font("Arial", 1, 11));
        this.JRBEsclPlus2.setText("++");
        this.JRBEsclPlus2.setName("2");
        this.Esclerosis.add(this.JRBEsclPlus3);
        this.JRBEsclPlus3.setFont(new Font("Arial", 1, 11));
        this.JRBEsclPlus3.setText("+++");
        this.JRBEsclPlus3.setName("3");
        this.Esclerosis.add(this.JRBEsclPlus4);
        this.JRBEsclPlus4.setFont(new Font("Arial", 1, 11));
        this.JRBEsclPlus4.setText("++++");
        this.JRBEsclPlus4.setName("4");
        this.JCHOpaCueiforme.setFont(new Font("Arial", 1, 11));
        this.JCHOpaCueiforme.setText("Opacidad Cuneiforme");
        this.JCHOpaCueiforme.setPreferredSize(new Dimension(113, 15));
        this.JCHOpaNuclear.setFont(new Font("Arial", 1, 11));
        this.JCHOpaNuclear.setText("Opac. Nuclear Congenita");
        this.JCHOpaNuclear.setPreferredSize(new Dimension(113, 15));
        this.JCHOpaSutural.setFont(new Font("Arial", 1, 11));
        this.JCHOpaSutural.setText("Opacidad Sutural");
        this.JCHOpaSutural.setPreferredSize(new Dimension(113, 15));
        this.JCHPolarPost.setFont(new Font("Arial", 1, 11));
        this.JCHPolarPost.setText("Polar Posterior");
        this.JCHPolarPost.setPreferredSize(new Dimension(113, 15));
        this.JTFOtrosCristalino.setFont(new Font("Arial", 1, 12));
        this.JTFOtrosCristalino.setBorder(BorderFactory.createTitledBorder((Border) null, "Otros", 0, 0, new Font("Arial", 1, 12), Color.blue));
        GroupLayout jPanel9Layout = new GroupLayout(this.jPanel9);
        this.jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel9Layout.createSequentialGroup().addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.JTFOtrosCristalino).addGroup(jPanel9Layout.createSequentialGroup().addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel9Layout.createSequentialGroup().addComponent(this.JCHCrisTrasparente, -2, 99, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JCHCrisBlanco, -2, 80, -2)).addGroup(jPanel9Layout.createSequentialGroup().addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.JCHOpaCueiforme, -2, 154, -2).addComponent(this.JCHOpaNuclear, -2, 163, -2)).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.JCHPolarPost, -2, 154, -2).addComponent(this.JCHOpaSutural, -2, 154, -2))).addGroup(jPanel9Layout.createSequentialGroup().addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel9Layout.createSequentialGroup().addComponent(this.jLabel5).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.JRBOpaAnterior)).addGroup(jPanel9Layout.createSequentialGroup().addComponent(this.jLabel6).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.JRBEsclPlus1).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JRBEsclPlus2))).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel9Layout.createSequentialGroup().addComponent(this.JRBEsclPlus3).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.JRBEsclPlus4)).addComponent(this.JRBOpaPosterior)))).addGap(0, 0, 32767))).addContainerGap()));
        jPanel9Layout.setVerticalGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel9Layout.createSequentialGroup().addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.JCHCrisTrasparente, -2, -1, -2).addComponent(this.JCHCrisBlanco, -2, -1, -2)).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.JRBOpaAnterior, -2, 15, -2).addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jLabel5).addComponent(this.JRBOpaPosterior, -2, 15, -2))).addGap(2, 2, 2).addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.JRBEsclPlus1, -2, 15, -2).addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jLabel6).addComponent(this.JRBEsclPlus2, -2, 15, -2).addComponent(this.JRBEsclPlus3, -2, 15, -2).addComponent(this.JRBEsclPlus4, -2, 15, -2))).addGap(3, 3, 3).addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.JCHOpaCueiforme, -2, -1, -2).addComponent(this.JCHOpaSutural, -2, -1, -2)).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.JCHOpaNuclear, -2, -1, -2).addComponent(this.JCHPolarPost, -2, -1, -2)).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JTFOtrosCristalino).addGap(58, 58, 58)));
        this.JTFPIO.setFont(new Font("Arial", 1, 12));
        this.JTFPIO.setBorder(BorderFactory.createTitledBorder((Border) null, "PIO", 0, 0, new Font("Arial", 1, 12), Color.blue));
        GroupLayout jPanel1Layout = new GroupLayout(this.jPanel1);
        this.jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addComponent(this.JCHTrasparente, -2, 95, -2).addGap(2, 2, 2).addComponent(this.JCHPliegues)).addGroup(jPanel1Layout.createSequentialGroup().addComponent(this.JCHInflamacion, -2, 169, -2).addGap(2, 2, 2).addComponent(this.JCHDepSube)).addGroup(jPanel1Layout.createSequentialGroup().addComponent(this.jPanel2, -2, -1, -2).addGap(3, 3, 3).addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.jPanel3, -1, -1, 32767).addGroup(jPanel1Layout.createSequentialGroup().addGap(3, 3, 3).addComponent(this.jPanel4, -1, -1, 32767)))).addComponent(this.jPanel5, -1, -1, 32767).addComponent(this.JTFOtros, -2, 375, -2).addComponent(this.jPanel6, -1, -1, 32767).addGroup(jPanel1Layout.createSequentialGroup().addComponent(this.jPanel8, -1, -1, 32767).addGap(14, 14, 14).addComponent(this.JTFPIO, -2, 102, -2)).addComponent(this.jPanel9, -1, -1, 32767));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.JCHTrasparente, -2, -1, -2).addComponent(this.JCHPliegues, -2, 15, -2)).addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.JCHInflamacion, -2, -1, -2).addComponent(this.JCHDepSube, -2, 15, -2)).addGap(1, 1, 1).addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.jPanel2, -2, -1, -2).addGroup(jPanel1Layout.createSequentialGroup().addComponent(this.jPanel3, -2, -1, -2).addGap(19, 19, 19).addComponent(this.jPanel4, -2, -1, -2))).addGap(1, 1, 1).addComponent(this.jPanel5, -2, -1, -2).addGap(3, 3, 3).addComponent(this.JTFOtros, -2, -1, -2).addGap(1, 1, 1).addComponent(this.jPanel6, -2, -1, -2).addGap(2, 2, 2).addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.jPanel8, -2, -1, -2).addGroup(jPanel1Layout.createSequentialGroup().addGap(51, 51, 51).addComponent(this.JTFPIO, -2, 45, -2))).addGap(1, 1, 1).addComponent(this.jPanel9, -2, 149, -2)));
        GroupLayout layout = new GroupLayout(this);
        setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.jPanel1, -1, -1, 32767));
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addComponent(this.jPanel1, -2, -1, -2).addGap(0, 0, 32767)));
    }

    /* JADX INFO: Access modifiers changed from: private */
    public void JCHNegraCentralActionPerformed(ActionEvent evt) {
        if (this.JCHNegraCentral.isSelected()) {
            this.JCBNegra.setEnabled(true);
        } else {
            this.JCBNegra.setEnabled(false);
            this.JCBNegra.setSelectedItem(" ");
        }
    }
}
