package Historia;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.border.Border;

/* JADX INFO: loaded from: GenomaP.jar:Historia/JPOft_OjoExa1.class */
public class JPOft_OjoExa1 extends JPanel {
    public ButtonGroup Hiperemia;
    public ButtonGroup Inferior;
    public JCheckBox JCHAspectoNormal;
    public JCheckBox JCHBlefaro;
    public JCheckBox JCHDermato;
    public JCheckBox JCHDistriq;
    public JCheckBox JCHEctropion;
    public JCheckBox JCHEntropion;
    public JCheckBox JCHGeneral;
    public JCheckBox JCHNasal;
    public JCheckBox JCHNormal;
    public JCheckBox JCHNormocro;
    public JCheckBox JCHPTosis;
    public JCheckBox JCHPlaca;
    public JCheckBox JCHQuemosis;
    public JCheckBox JCHRFTarsal;
    public JCheckBox JCHRPapilar;
    public JCheckBox JCHTemp;
    public JCheckBox JCHTrisq;
    public JTextField JLBalance;
    public JTextField JLCC;
    public JTextField JLCilindro;
    public JTextField JLEje;
    public JTextField JLEsfera;
    public JTextField JLK1;
    public JTextField JLK2;
    public JTextField JLLA;
    public JTextField JLLIO;
    public JTextField JLMEO;
    public JTextField JLSC;
    public JRadioButton JRB1Nas;
    public JRadioButton JRB1Plus;
    public JRadioButton JRB1Tmp;
    public JRadioButton JRB2Nas;
    public JRadioButton JRB2Plus;
    public JRadioButton JRB2Tmp;
    public JRadioButton JRB3Nas;
    public JRadioButton JRB3Plus;
    public JRadioButton JRB3Tmp;
    public JRadioButton JRB4Nas;
    public JRadioButton JRB4Tmp;
    public JRadioButton JRB5Nas;
    public JRadioButton JRB5Tmp;
    public JRadioButton JRBAmarillo;
    public JRadioButton JRBBlanco;
    public JRadioButton JRBInflamatoria1;
    public JRadioButton JRBInflamatoria2;
    public JRadioButton JRBNOInflamatoria1;
    public JRadioButton JRBNOInflamatoria2;
    public JRadioButton JRBVerde;
    public JTextField JTFOtros;
    public JTextField JTFOtrosConj;
    public ButtonGroup Nasal;
    public ButtonGroup Secrecion;
    public ButtonGroup Superior;
    public ButtonGroup Temporal;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JPanel jPanel5;
    private JPanel jPanel6;
    private JPanel jPanel7;
    private JPanel jPanel8;

    public JPOft_OjoExa1(String xNombre) {
        initComponents();
        setBorder(BorderFactory.createTitledBorder((Border) null, xNombre, 0, 0, new Font("Arial", 1, 14), Color.red));
    }

    private void initComponents() {
        this.Superior = new ButtonGroup();
        this.Inferior = new ButtonGroup();
        this.Hiperemia = new ButtonGroup();
        this.Nasal = new ButtonGroup();
        this.Temporal = new ButtonGroup();
        this.Secrecion = new ButtonGroup();
        this.jPanel1 = new JPanel();
        this.jLabel1 = new JLabel();
        this.JLSC = new JTextField();
        this.JLCC = new JTextField();
        this.JLEsfera = new JTextField();
        this.JLCilindro = new JTextField();
        this.JLEje = new JTextField();
        this.jLabel2 = new JLabel();
        this.JLK1 = new JTextField();
        this.JLK2 = new JTextField();
        this.jLabel3 = new JLabel();
        this.JLLIO = new JTextField();
        this.JLLA = new JTextField();
        this.JLBalance = new JTextField();
        this.JLMEO = new JTextField();
        this.jPanel2 = new JPanel();
        this.JCHAspectoNormal = new JCheckBox();
        this.JCHEctropion = new JCheckBox();
        this.JCHEntropion = new JCheckBox();
        this.jPanel3 = new JPanel();
        this.jLabel4 = new JLabel();
        this.JRBInflamatoria1 = new JRadioButton();
        this.JRBNOInflamatoria1 = new JRadioButton();
        this.JRBInflamatoria2 = new JRadioButton();
        this.JRBNOInflamatoria2 = new JRadioButton();
        this.jLabel5 = new JLabel();
        this.JCHPTosis = new JCheckBox();
        this.JCHBlefaro = new JCheckBox();
        this.JCHDermato = new JCheckBox();
        this.jPanel4 = new JPanel();
        this.JCHNormal = new JCheckBox();
        this.JCHTrisq = new JCheckBox();
        this.JCHDistriq = new JCheckBox();
        this.JTFOtros = new JTextField();
        this.jPanel5 = new JPanel();
        this.JCHNormocro = new JCheckBox();
        this.JCHPlaca = new JCheckBox();
        this.jLabel6 = new JLabel();
        this.JRB1Plus = new JRadioButton();
        this.JRB2Plus = new JRadioButton();
        this.JRB3Plus = new JRadioButton();
        this.jPanel6 = new JPanel();
        this.jLabel7 = new JLabel();
        this.JRB1Nas = new JRadioButton();
        this.JRB2Nas = new JRadioButton();
        this.jLabel8 = new JLabel();
        this.JRB3Nas = new JRadioButton();
        this.JRB4Nas = new JRadioButton();
        this.JRB5Nas = new JRadioButton();
        this.JRB1Tmp = new JRadioButton();
        this.JRB2Tmp = new JRadioButton();
        this.JRB3Tmp = new JRadioButton();
        this.JRB4Tmp = new JRadioButton();
        this.JRB5Tmp = new JRadioButton();
        this.jPanel7 = new JPanel();
        this.JCHNasal = new JCheckBox();
        this.JCHTemp = new JCheckBox();
        this.JCHGeneral = new JCheckBox();
        this.JCHRPapilar = new JCheckBox();
        this.JCHRFTarsal = new JCheckBox();
        this.JCHQuemosis = new JCheckBox();
        this.jPanel8 = new JPanel();
        this.JRBBlanco = new JRadioButton();
        this.JRBAmarillo = new JRadioButton();
        this.JRBVerde = new JRadioButton();
        this.JTFOtrosConj = new JTextField();
        setPreferredSize(new Dimension(387, 630));
        this.jPanel1.setBorder(BorderFactory.createTitledBorder(""));
        this.jLabel1.setFont(new Font("Arial", 1, 12));
        this.jLabel1.setText("AGUDEZA VISUAL:");
        this.JLSC.setFont(new Font("Arial", 1, 11));
        this.JLSC.setBorder(BorderFactory.createTitledBorder((Border) null, "S/C", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.JLCC.setFont(new Font("Arial", 1, 11));
        this.JLCC.setBorder(BorderFactory.createTitledBorder((Border) null, "C/C", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.JLEsfera.setFont(new Font("Arial", 1, 11));
        this.JLEsfera.setBorder(BorderFactory.createTitledBorder((Border) null, "Esfera", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.JLCilindro.setFont(new Font("Arial", 1, 11));
        this.JLCilindro.setBorder(BorderFactory.createTitledBorder((Border) null, "Cilindro", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.JLEje.setFont(new Font("Arial", 1, 11));
        this.JLEje.setBorder(BorderFactory.createTitledBorder((Border) null, "Eje", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.jLabel2.setFont(new Font("Arial", 1, 12));
        this.jLabel2.setText("KETOMETRIA:");
        this.JLK1.setFont(new Font("Arial", 1, 11));
        this.JLK1.setBorder(BorderFactory.createTitledBorder((Border) null, "K1", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.JLK2.setFont(new Font("Arial", 1, 11));
        this.JLK2.setBorder(BorderFactory.createTitledBorder((Border) null, "K2", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.JLK2.addActionListener(new ActionListener() { // from class: Historia.JPOft_OjoExa1.1
            public void actionPerformed(ActionEvent evt) {
                JPOft_OjoExa1.this.JLK2ActionPerformed(evt);
            }
        });
        this.jLabel3.setFont(new Font("Arial", 1, 12));
        this.jLabel3.setText("BIOMETRÍA:");
        this.JLLIO.setFont(new Font("Arial", 1, 11));
        this.JLLIO.setBorder(BorderFactory.createTitledBorder((Border) null, "LIO", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.JLLA.setFont(new Font("Arial", 1, 11));
        this.JLLA.setBorder(BorderFactory.createTitledBorder((Border) null, "LA", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.JLBalance.setFont(new Font("Arial", 1, 11));
        this.JLBalance.setBorder(BorderFactory.createTitledBorder((Border) null, "Balance", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.JLMEO.setFont(new Font("Arial", 1, 11));
        this.JLMEO.setBorder(BorderFactory.createTitledBorder((Border) null, "MEO", 0, 0, new Font("Arial", 1, 12), Color.blue));
        GroupLayout jPanel1Layout = new GroupLayout(this.jPanel1);
        this.jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addGap(6, 6, 6).addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false).addGroup(jPanel1Layout.createSequentialGroup().addComponent(this.JLEsfera, -2, 81, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JLCilindro, -2, 81, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JLEje, -2, 81, -2)).addGroup(jPanel1Layout.createSequentialGroup().addComponent(this.jLabel1).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JLSC, -2, 60, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JLCC, -2, 60, -2)).addGroup(jPanel1Layout.createSequentialGroup().addComponent(this.JLBalance, -2, 124, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JLMEO)).addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.jLabel2).addComponent(this.jLabel3)).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addComponent(this.JLLIO, -2, 60, -2).addGap(6, 6, 6).addComponent(this.JLLA, -2, 60, -2)).addGroup(jPanel1Layout.createSequentialGroup().addComponent(this.JLK1, -2, 60, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JLK2, -2, 60, -2))))).addContainerGap(-1, 32767)));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addGap(1, 1, 1).addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jLabel1).addComponent(this.JLSC, -2, 35, -2).addComponent(this.JLCC, -2, 35, -2)).addGap(1, 1, 1).addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.JLEsfera, -2, 35, -2).addComponent(this.JLCilindro, -2, 35, -2).addComponent(this.JLEje, -2, 35, -2)).addGap(1, 1, 1).addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.JLK1, -2, 35, -2).addComponent(this.JLK2, -2, 35, -2).addComponent(this.jLabel2)).addGap(1, 1, 1).addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jLabel3).addComponent(this.JLLIO, -2, 35, -2).addComponent(this.JLLA, -2, 35, -2)).addGap(1, 1, 1).addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.JLMEO, -2, 35, -2).addComponent(this.JLBalance, -2, 0, 32767)).addGap(1, 1, 1)));
        this.jPanel2.setBorder(BorderFactory.createTitledBorder((Border) null, "Parpados", 0, 0, new Font("Arial", 1, 12), Color.red));
        this.JCHAspectoNormal.setFont(new Font("Arial", 1, 11));
        this.JCHAspectoNormal.setText("Aspecto Normal");
        this.JCHAspectoNormal.setPreferredSize(new Dimension(113, 15));
        this.JCHEctropion.setFont(new Font("Arial", 1, 11));
        this.JCHEctropion.setText("Ectropion");
        this.JCHEctropion.setPreferredSize((Dimension) null);
        this.JCHEntropion.setFont(new Font("Arial", 1, 11));
        this.JCHEntropion.setText("Entropion");
        this.JCHEntropion.setPreferredSize((Dimension) null);
        this.jPanel3.setBorder(BorderFactory.createTitledBorder((Border) null, "Masa", 0, 0, new Font("Arial", 1, 12), Color.red));
        this.jLabel4.setFont(new Font("Arial", 1, 11));
        this.jLabel4.setText("Superior:");
        this.Superior.add(this.JRBInflamatoria1);
        this.JRBInflamatoria1.setFont(new Font("Arial", 1, 11));
        this.JRBInflamatoria1.setText("Inflamatoria");
        this.JRBInflamatoria1.setName("1");
        this.Superior.add(this.JRBNOInflamatoria1);
        this.JRBNOInflamatoria1.setFont(new Font("Arial", 1, 11));
        this.JRBNOInflamatoria1.setText("No Inflamatoria");
        this.JRBNOInflamatoria1.setName("2");
        this.Inferior.add(this.JRBInflamatoria2);
        this.JRBInflamatoria2.setFont(new Font("Arial", 1, 11));
        this.JRBInflamatoria2.setText("Inflamatoria");
        this.JRBInflamatoria2.setName("1");
        this.Inferior.add(this.JRBNOInflamatoria2);
        this.JRBNOInflamatoria2.setFont(new Font("Arial", 1, 11));
        this.JRBNOInflamatoria2.setText("No Inflamatoria");
        this.JRBNOInflamatoria2.setName("2");
        this.jLabel5.setFont(new Font("Arial", 1, 11));
        this.jLabel5.setText("Inferior:");
        GroupLayout jPanel3Layout = new GroupLayout(this.jPanel3);
        this.jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel3Layout.createSequentialGroup().addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.jLabel4).addComponent(this.jLabel5)).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel3Layout.createSequentialGroup().addComponent(this.JRBInflamatoria1).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.JRBNOInflamatoria1)).addGroup(jPanel3Layout.createSequentialGroup().addComponent(this.JRBInflamatoria2).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.JRBNOInflamatoria2))).addContainerGap(16, 32767)));
        jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel3Layout.createSequentialGroup().addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.JRBInflamatoria1, -2, 15, -2).addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jLabel4).addComponent(this.JRBNOInflamatoria1, -2, 15, -2))).addGap(2, 2, 2).addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jLabel5).addComponent(this.JRBInflamatoria2, -2, 15, -2).addComponent(this.JRBNOInflamatoria2, -2, 15, -2))));
        this.JCHPTosis.setFont(new Font("Arial", 1, 11));
        this.JCHPTosis.setText("PTosis");
        this.JCHBlefaro.setFont(new Font("Arial", 1, 11));
        this.JCHBlefaro.setText("Blefarochalasis");
        this.JCHDermato.setFont(new Font("Arial", 1, 11));
        this.JCHDermato.setText("Dermatochalasis");
        this.jPanel4.setBorder(BorderFactory.createTitledBorder((Border) null, "Pestañas", 0, 0, new Font("Arial", 1, 12), Color.red));
        this.JCHNormal.setFont(new Font("Arial", 1, 11));
        this.JCHNormal.setText("Normal");
        this.JCHTrisq.setFont(new Font("Arial", 1, 11));
        this.JCHTrisq.setText("Triquiasis");
        this.JCHDistriq.setFont(new Font("Arial", 1, 11));
        this.JCHDistriq.setText("Distriquiasis");
        GroupLayout jPanel4Layout = new GroupLayout(this.jPanel4);
        this.jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel4Layout.createSequentialGroup().addContainerGap().addComponent(this.JCHNormal).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.JCHTrisq).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.JCHDistriq).addContainerGap(26, 32767)));
        jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.JCHNormal, -2, 15, -2).addComponent(this.JCHTrisq, -2, 15, -2).addComponent(this.JCHDistriq, -2, 15, -2)));
        this.JTFOtros.setFont(new Font("Arial", 1, 12));
        this.JTFOtros.setBorder(BorderFactory.createTitledBorder((Border) null, "Otros", 0, 0, new Font("Arial", 1, 12), Color.blue));
        GroupLayout jPanel2Layout = new GroupLayout(this.jPanel2);
        this.jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addComponent(this.JCHPTosis).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.JCHBlefaro).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.JCHDermato).addGap(0, 0, 32767)).addGroup(jPanel2Layout.createSequentialGroup().addGap(3, 3, 3).addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false).addComponent(this.jPanel3, -1, -1, 32767).addGroup(jPanel2Layout.createSequentialGroup().addComponent(this.JCHAspectoNormal, -2, -1, -2).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.JCHEctropion, -2, 79, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JCHEntropion, -2, -1, -2))).addComponent(this.jPanel4, -2, -1, -2).addComponent(this.JTFOtros, -2, 344, -2)).addContainerGap(-1, 32767)));
        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.JCHEntropion, -2, 15, -2).addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.JCHAspectoNormal, -2, -1, -2).addComponent(this.JCHEctropion, -2, 15, -2))).addGap(1, 1, 1).addComponent(this.jPanel3, -2, -1, -2).addGap(1, 1, 1).addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.JCHPTosis, -2, 15, -2).addComponent(this.JCHBlefaro, -2, 15, -2).addComponent(this.JCHDermato, -2, 15, -2)).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jPanel4, -2, -1, -2).addGap(1, 1, 1).addComponent(this.JTFOtros).addGap(1, 1, 1)));
        this.jPanel5.setBorder(BorderFactory.createTitledBorder((Border) null, "Conjuntiva", 0, 0, new Font("Arial", 1, 12), Color.red));
        this.JCHNormocro.setFont(new Font("Arial", 1, 11));
        this.JCHNormocro.setText("Normocronica");
        this.JCHPlaca.setFont(new Font("Arial", 1, 11));
        this.JCHPlaca.setText("Placa");
        this.jLabel6.setFont(new Font("Arial", 1, 11));
        this.jLabel6.setText("Hiperemia:");
        this.Hiperemia.add(this.JRB1Plus);
        this.JRB1Plus.setFont(new Font("Arial", 1, 12));
        this.JRB1Plus.setText("+");
        this.JRB1Plus.setName("1");
        this.Hiperemia.add(this.JRB2Plus);
        this.JRB2Plus.setFont(new Font("Arial", 1, 12));
        this.JRB2Plus.setText("++");
        this.JRB2Plus.setName("2");
        this.Hiperemia.add(this.JRB3Plus);
        this.JRB3Plus.setFont(new Font("Arial", 1, 12));
        this.JRB3Plus.setText("+++");
        this.JRB3Plus.setName("3");
        this.jPanel6.setBorder(BorderFactory.createTitledBorder((Border) null, "Espesamiento Conjuntival", 0, 0, new Font("Arial", 1, 12), Color.red));
        this.jLabel7.setFont(new Font("Arial", 1, 11));
        this.jLabel7.setText("Nasal:");
        this.Nasal.add(this.JRB1Nas);
        this.JRB1Nas.setFont(new Font("Arial", 1, 11));
        this.JRB1Nas.setText("I");
        this.JRB1Nas.setName("1");
        this.Nasal.add(this.JRB2Nas);
        this.JRB2Nas.setFont(new Font("Arial", 1, 11));
        this.JRB2Nas.setText("II");
        this.JRB2Nas.setName("2");
        this.jLabel8.setFont(new Font("Arial", 1, 11));
        this.jLabel8.setText("Temporal:");
        this.Nasal.add(this.JRB3Nas);
        this.JRB3Nas.setFont(new Font("Arial", 1, 11));
        this.JRB3Nas.setText("III");
        this.JRB3Nas.setName("3");
        this.Nasal.add(this.JRB4Nas);
        this.JRB4Nas.setFont(new Font("Arial", 1, 11));
        this.JRB4Nas.setText("IV");
        this.JRB4Nas.setName("4");
        this.Nasal.add(this.JRB5Nas);
        this.JRB5Nas.setFont(new Font("Arial", 1, 11));
        this.JRB5Nas.setText("V");
        this.JRB5Nas.setName("5");
        this.Temporal.add(this.JRB1Tmp);
        this.JRB1Tmp.setFont(new Font("Arial", 1, 11));
        this.JRB1Tmp.setText("I");
        this.JRB1Tmp.setName("1");
        this.Temporal.add(this.JRB2Tmp);
        this.JRB2Tmp.setFont(new Font("Arial", 1, 11));
        this.JRB2Tmp.setText("II");
        this.JRB2Tmp.setName("2");
        this.Temporal.add(this.JRB3Tmp);
        this.JRB3Tmp.setFont(new Font("Arial", 1, 11));
        this.JRB3Tmp.setText("III");
        this.JRB3Tmp.setName("3");
        this.Temporal.add(this.JRB4Tmp);
        this.JRB4Tmp.setFont(new Font("Arial", 1, 11));
        this.JRB4Tmp.setText("IV");
        this.JRB4Tmp.setName("4");
        this.Temporal.add(this.JRB5Tmp);
        this.JRB5Tmp.setFont(new Font("Arial", 1, 11));
        this.JRB5Tmp.setText("V");
        this.JRB5Tmp.setName("5");
        GroupLayout jPanel6Layout = new GroupLayout(this.jPanel6);
        this.jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel6Layout.createSequentialGroup().addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.jLabel7).addComponent(this.jLabel8)).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel6Layout.createSequentialGroup().addComponent(this.JRB1Nas).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.JRB2Nas).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JRB3Nas).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JRB4Nas).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JRB5Nas)).addGroup(jPanel6Layout.createSequentialGroup().addComponent(this.JRB1Tmp).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.JRB2Tmp).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JRB3Tmp).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JRB4Tmp).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JRB5Tmp))).addContainerGap(-1, 32767)));
        jPanel6Layout.setVerticalGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel6Layout.createSequentialGroup().addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jLabel7).addComponent(this.JRB1Nas, -2, 15, -2).addComponent(this.JRB2Nas, -2, 15, -2).addComponent(this.JRB3Nas, -2, 15, -2).addComponent(this.JRB4Nas, -2, 15, -2).addComponent(this.JRB5Nas, -2, 15, -2)).addGap(0, 0, 0).addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.JRB1Tmp, -2, 15, -2).addComponent(this.JRB2Tmp, -2, 15, -2).addComponent(this.JRB3Tmp, -2, 15, -2).addComponent(this.JRB4Tmp, -2, 15, -2).addComponent(this.JRB5Tmp, -2, 15, -2)).addComponent(this.jLabel8))));
        this.jPanel7.setBorder(BorderFactory.createTitledBorder((Border) null, "Hemorragia", 0, 0, new Font("Arial", 1, 12), Color.red));
        this.JCHNasal.setFont(new Font("Arial", 1, 11));
        this.JCHNasal.setText("Nasal");
        this.JCHTemp.setFont(new Font("Arial", 1, 11));
        this.JCHTemp.setText("Temporal");
        this.JCHGeneral.setFont(new Font("Arial", 1, 11));
        this.JCHGeneral.setText("Generalizada");
        GroupLayout jPanel7Layout = new GroupLayout(this.jPanel7);
        this.jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel7Layout.createSequentialGroup().addGap(3, 3, 3).addComponent(this.JCHNasal).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.JCHTemp).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.JCHGeneral).addContainerGap(-1, 32767)));
        jPanel7Layout.setVerticalGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.JCHNasal, -2, 15, -2).addComponent(this.JCHTemp, -2, 15, -2).addComponent(this.JCHGeneral, -2, 15, -2)));
        this.JCHRPapilar.setFont(new Font("Arial", 1, 11));
        this.JCHRPapilar.setText("Reacción papilar");
        this.JCHRFTarsal.setFont(new Font("Arial", 1, 11));
        this.JCHRFTarsal.setText("Reacción Folicular Tarsal");
        this.JCHQuemosis.setFont(new Font("Arial", 1, 11));
        this.JCHQuemosis.setText("Quemosis");
        this.jPanel8.setBorder(BorderFactory.createTitledBorder((Border) null, "Secreción Conjuntival", 0, 0, new Font("Arial", 1, 12), Color.red));
        this.Secrecion.add(this.JRBBlanco);
        this.JRBBlanco.setFont(new Font("Arial", 1, 11));
        this.JRBBlanco.setText("Blanco");
        this.JRBBlanco.setName("1");
        this.Secrecion.add(this.JRBAmarillo);
        this.JRBAmarillo.setFont(new Font("Arial", 1, 11));
        this.JRBAmarillo.setText("Amarillo");
        this.JRBAmarillo.setName("2");
        this.Secrecion.add(this.JRBVerde);
        this.JRBVerde.setFont(new Font("Arial", 1, 11));
        this.JRBVerde.setText("Verde");
        this.JRBVerde.setName("3");
        GroupLayout jPanel8Layout = new GroupLayout(this.jPanel8);
        this.jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel8Layout.createSequentialGroup().addGap(3, 3, 3).addComponent(this.JRBBlanco).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.JRBAmarillo).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JRBVerde).addContainerGap(142, 32767)));
        jPanel8Layout.setVerticalGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel8Layout.createSequentialGroup().addGap(1, 1, 1).addGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.JRBBlanco, -2, 15, -2).addComponent(this.JRBAmarillo, -2, 15, -2).addComponent(this.JRBVerde, -2, 15, -2)).addGap(1, 1, 1)));
        this.JTFOtrosConj.setFont(new Font("Arial", 1, 12));
        this.JTFOtrosConj.setBorder(BorderFactory.createTitledBorder((Border) null, "Otros", 0, 0, new Font("Arial", 1, 12), Color.blue));
        GroupLayout jPanel5Layout = new GroupLayout(this.jPanel5);
        this.jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel5Layout.createSequentialGroup().addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel5Layout.createSequentialGroup().addComponent(this.JCHRPapilar).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.JCHRFTarsal).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.JCHQuemosis)).addComponent(this.jPanel8, -2, -1, -2)).addContainerGap(12, 32767)).addGroup(jPanel5Layout.createSequentialGroup().addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false).addGroup(GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup().addGap(4, 4, 4).addComponent(this.JCHNormocro).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JCHPlaca).addGap(8, 8, 8).addComponent(this.jLabel6).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JRB1Plus).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JRB2Plus).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JRB3Plus)).addComponent(this.jPanel6, GroupLayout.Alignment.LEADING, -1, -1, 32767).addComponent(this.jPanel7, GroupLayout.Alignment.LEADING, -1, -1, 32767)).addComponent(this.JTFOtrosConj, -2, 350, -2)).addGap(0, 0, 32767)));
        jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel5Layout.createSequentialGroup().addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jLabel6).addComponent(this.JRB1Plus, -2, 15, -2).addComponent(this.JRB2Plus, -2, 15, -2).addComponent(this.JRB3Plus, -2, 15, -2)).addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.JCHNormocro, -2, 15, -2).addComponent(this.JCHPlaca, -2, 15, -2))).addGap(3, 3, 3).addComponent(this.jPanel6, -2, -1, -2).addGap(3, 3, 3).addComponent(this.jPanel7, -2, -1, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.JCHRPapilar, -2, 15, -2).addComponent(this.JCHRFTarsal, -2, 15, -2).addComponent(this.JCHQuemosis, -2, 15, -2)).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jPanel8, -2, -1, -2).addGap(1, 1, 1).addComponent(this.JTFOtrosConj)));
        GroupLayout layout = new GroupLayout(this);
        setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING).addComponent(this.jPanel1, GroupLayout.Alignment.LEADING, -1, -1, 32767).addComponent(this.jPanel2, GroupLayout.Alignment.LEADING, -1, -1, 32767).addComponent(this.jPanel5, -1, -1, 32767)).addGap(0, 0, 0)));
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(3, 3, 3).addComponent(this.jPanel1, -2, -1, -2).addGap(1, 1, 1).addComponent(this.jPanel2, -2, -1, -2).addGap(1, 1, 1).addComponent(this.jPanel5, -2, -1, -2).addGap(3, 3, 3)));
    }

    /* JADX INFO: Access modifiers changed from: private */
    public void JLK2ActionPerformed(ActionEvent evt) {
    }
}
