package Historia;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.border.Border;

/* JADX INFO: loaded from: GenomaP.jar:Historia/JPOft_OjoExa3.class */
public class JPOft_OjoExa3 extends JPanel {
    public ButtonGroup Excavacion;
    public JCheckBox JCHCicatriz;
    public JCheckBox JCHClaro;
    public JCheckBox JCHDeposito;
    public JCheckBox JCHDisforme;
    public JCheckBox JCHFoco;
    public JCheckBox JCHMemEpi;
    public JCheckBox JCHNeovascular;
    public JCheckBox JCHPigmetacion;
    public JCheckBox JCHSana;
    public JCheckBox JCHTurbio;
    public JRadioButton JRBEx1;
    public JRadioButton JRBEx10;
    public JRadioButton JRBEx2;
    public JRadioButton JRBEx3;
    public JRadioButton JRBEx4;
    public JRadioButton JRBEx5;
    public JRadioButton JRBEx6;
    public JRadioButton JRBEx7;
    public JRadioButton JRBEx8;
    public JRadioButton JRBEx9;
    public JRadioButton JRBHemPlus1;
    public JRadioButton JRBHemPlus2;
    public JRadioButton JRBHemPlus3;
    public JRadioButton JRBHemPlus4;
    public JRadioButton JRBInfPlus1;
    public JRadioButton JRBInfPlus2;
    public JRadioButton JRBInfPlus3;
    public JRadioButton JRBInfPlus4;
    public JRadioButton JRBRetAplicada;
    public JRadioButton JRBRetDesp;
    public JRadioButton JRBRetInexp;
    public JRadioButton JRBVaSanos;
    public JRadioButton JRBVaTortuosos;
    public JTextArea JTAObservaciones;
    public JTextArea JTAPeriferia;
    public JTextField JTFPapilas;
    public ButtonGroup Retina;
    public ButtonGroup THemorragico;
    public ButtonGroup TInflamatorio;
    public ButtonGroup Vasos;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;

    public JPOft_OjoExa3(String xNombre) {
        initComponents();
        setBorder(BorderFactory.createTitledBorder((Border) null, xNombre, 0, 0, new Font("Arial", 1, 14), Color.red));
    }

    private void initComponents() {
        this.TInflamatorio = new ButtonGroup();
        this.THemorragico = new ButtonGroup();
        this.Excavacion = new ButtonGroup();
        this.Vasos = new ButtonGroup();
        this.Retina = new ButtonGroup();
        this.jPanel1 = new JPanel();
        this.JCHClaro = new JCheckBox();
        this.JCHTurbio = new JCheckBox();
        this.JCHDeposito = new JCheckBox();
        this.jLabel6 = new JLabel();
        this.JRBInfPlus1 = new JRadioButton();
        this.JRBInfPlus2 = new JRadioButton();
        this.JRBInfPlus3 = new JRadioButton();
        this.JRBInfPlus4 = new JRadioButton();
        this.jLabel7 = new JLabel();
        this.JRBHemPlus1 = new JRadioButton();
        this.JRBHemPlus2 = new JRadioButton();
        this.JRBHemPlus3 = new JRadioButton();
        this.JRBHemPlus4 = new JRadioButton();
        this.JTFPapilas = new JTextField();
        this.jLabel8 = new JLabel();
        this.JRBEx1 = new JRadioButton();
        this.JRBEx2 = new JRadioButton();
        this.JRBEx3 = new JRadioButton();
        this.JRBEx4 = new JRadioButton();
        this.JRBEx5 = new JRadioButton();
        this.JRBEx6 = new JRadioButton();
        this.JRBEx7 = new JRadioButton();
        this.JRBEx8 = new JRadioButton();
        this.JRBEx9 = new JRadioButton();
        this.JRBEx10 = new JRadioButton();
        this.jLabel9 = new JLabel();
        this.JRBVaSanos = new JRadioButton();
        this.JRBVaTortuosos = new JRadioButton();
        this.jPanel2 = new JPanel();
        this.JRBRetAplicada = new JRadioButton();
        this.JRBRetDesp = new JRadioButton();
        this.JRBRetInexp = new JRadioButton();
        this.jPanel3 = new JPanel();
        this.JCHMemEpi = new JCheckBox();
        this.JCHDisforme = new JCheckBox();
        this.JCHSana = new JCheckBox();
        this.JCHPigmetacion = new JCheckBox();
        this.JCHNeovascular = new JCheckBox();
        this.JCHCicatriz = new JCheckBox();
        this.JCHFoco = new JCheckBox();
        this.jScrollPane1 = new JScrollPane();
        this.JTAPeriferia = new JTextArea();
        this.jScrollPane2 = new JScrollPane();
        this.JTAObservaciones = new JTextArea();
        setPreferredSize(new Dimension(387, 630));
        this.jPanel1.setBorder(BorderFactory.createTitledBorder((Border) null, "Vitreo", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.JCHClaro.setFont(new Font("Arial", 1, 11));
        this.JCHClaro.setText("Claro");
        this.JCHClaro.setPreferredSize(new Dimension(113, 15));
        this.JCHTurbio.setFont(new Font("Arial", 1, 11));
        this.JCHTurbio.setText("Turbio");
        this.JCHTurbio.setPreferredSize(new Dimension(113, 15));
        this.JCHDeposito.setFont(new Font("Arial", 1, 11));
        this.JCHDeposito.setText("Depósito Virrefrigente");
        this.JCHDeposito.setPreferredSize(new Dimension(113, 15));
        this.jLabel6.setFont(new Font("Arial", 1, 11));
        this.jLabel6.setText("Tyndall Inflamatorio:");
        this.TInflamatorio.add(this.JRBInfPlus1);
        this.JRBInfPlus1.setFont(new Font("Arial", 1, 11));
        this.JRBInfPlus1.setText("+");
        this.JRBInfPlus1.setName("1");
        this.TInflamatorio.add(this.JRBInfPlus2);
        this.JRBInfPlus2.setFont(new Font("Arial", 1, 11));
        this.JRBInfPlus2.setText("++");
        this.JRBInfPlus2.setName("2");
        this.TInflamatorio.add(this.JRBInfPlus3);
        this.JRBInfPlus3.setFont(new Font("Arial", 1, 11));
        this.JRBInfPlus3.setText("+++");
        this.JRBInfPlus3.setName("3");
        this.TInflamatorio.add(this.JRBInfPlus4);
        this.JRBInfPlus4.setFont(new Font("Arial", 1, 11));
        this.JRBInfPlus4.setText("++++");
        this.JRBInfPlus4.setName("4");
        this.jLabel7.setFont(new Font("Arial", 1, 11));
        this.jLabel7.setText("Tyndall Hemorrágico:");
        this.THemorragico.add(this.JRBHemPlus1);
        this.JRBHemPlus1.setFont(new Font("Arial", 1, 11));
        this.JRBHemPlus1.setText("+");
        this.JRBHemPlus1.setName("1");
        this.THemorragico.add(this.JRBHemPlus2);
        this.JRBHemPlus2.setFont(new Font("Arial", 1, 11));
        this.JRBHemPlus2.setText("++");
        this.JRBHemPlus2.setName("2");
        this.THemorragico.add(this.JRBHemPlus3);
        this.JRBHemPlus3.setFont(new Font("Arial", 1, 11));
        this.JRBHemPlus3.setText("+++");
        this.JRBHemPlus3.setName("3");
        this.THemorragico.add(this.JRBHemPlus4);
        this.JRBHemPlus4.setFont(new Font("Arial", 1, 11));
        this.JRBHemPlus4.setText("++++");
        this.JRBHemPlus4.setName("4");
        GroupLayout jPanel1Layout = new GroupLayout(this.jPanel1);
        this.jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addComponent(this.JCHClaro, -2, 68, -2).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.JCHTurbio, -2, 70, -2).addGap(10, 10, 10).addComponent(this.JCHDeposito, -2, 153, -2)).addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.jLabel7).addComponent(this.jLabel6)).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addComponent(this.JRBInfPlus1).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JRBInfPlus2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JRBInfPlus3).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.JRBInfPlus4)).addGroup(jPanel1Layout.createSequentialGroup().addComponent(this.JRBHemPlus1).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JRBHemPlus2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JRBHemPlus3).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.JRBHemPlus4))))).addContainerGap(63, 32767)));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.JCHClaro, -2, -1, -2).addComponent(this.JCHTurbio, -2, -1, -2).addComponent(this.JCHDeposito, -2, -1, -2)).addGap(3, 3, 3).addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.JRBInfPlus1, -2, 15, -2).addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jLabel6).addComponent(this.JRBInfPlus2, -2, 15, -2).addComponent(this.JRBInfPlus3, -2, 15, -2).addComponent(this.JRBInfPlus4, -2, 15, -2))).addGap(3, 3, 3).addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.JRBHemPlus1, -2, 15, -2).addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jLabel7).addComponent(this.JRBHemPlus2, -2, 15, -2).addComponent(this.JRBHemPlus3, -2, 15, -2).addComponent(this.JRBHemPlus4, -2, 15, -2))).addGap(3, 3, 3)));
        this.JTFPapilas.setFont(new Font("Arial", 1, 12));
        this.JTFPapilas.setBorder(BorderFactory.createTitledBorder((Border) null, "Papilas", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.jLabel8.setFont(new Font("Arial", 1, 11));
        this.jLabel8.setText("Excavación:");
        this.Excavacion.add(this.JRBEx1);
        this.JRBEx1.setFont(new Font("Arial", 1, 11));
        this.JRBEx1.setText("1");
        this.JRBEx1.setToolTipText("0,1");
        this.JRBEx1.setName("1");
        this.Excavacion.add(this.JRBEx2);
        this.JRBEx2.setFont(new Font("Arial", 1, 11));
        this.JRBEx2.setText("2");
        this.JRBEx2.setName("2");
        this.Excavacion.add(this.JRBEx3);
        this.JRBEx3.setFont(new Font("Arial", 1, 11));
        this.JRBEx3.setText("3");
        this.JRBEx3.setToolTipText("0,3");
        this.JRBEx3.setName("3");
        this.Excavacion.add(this.JRBEx4);
        this.JRBEx4.setFont(new Font("Arial", 1, 11));
        this.JRBEx4.setText("4");
        this.JRBEx4.setToolTipText("0,4");
        this.JRBEx4.setName("4");
        this.Excavacion.add(this.JRBEx5);
        this.JRBEx5.setFont(new Font("Arial", 1, 11));
        this.JRBEx5.setText("5");
        this.JRBEx5.setToolTipText("0,5");
        this.JRBEx5.setName("5");
        this.Excavacion.add(this.JRBEx6);
        this.JRBEx6.setFont(new Font("Arial", 1, 11));
        this.JRBEx6.setText("6");
        this.JRBEx6.setToolTipText("0,6");
        this.JRBEx6.setName("6");
        this.Excavacion.add(this.JRBEx7);
        this.JRBEx7.setFont(new Font("Arial", 1, 11));
        this.JRBEx7.setText("7");
        this.JRBEx7.setToolTipText("0,7");
        this.JRBEx7.setName("7");
        this.Excavacion.add(this.JRBEx8);
        this.JRBEx8.setFont(new Font("Arial", 1, 11));
        this.JRBEx8.setText("8");
        this.JRBEx8.setToolTipText("0,8");
        this.JRBEx8.setName("8");
        this.Excavacion.add(this.JRBEx9);
        this.JRBEx9.setFont(new Font("Arial", 1, 11));
        this.JRBEx9.setText("9");
        this.JRBEx9.setToolTipText("0,9");
        this.JRBEx9.setName("9");
        this.Excavacion.add(this.JRBEx10);
        this.JRBEx10.setFont(new Font("Arial", 1, 11));
        this.JRBEx10.setText("10");
        this.JRBEx10.setToolTipText("1");
        this.JRBEx10.setName("10");
        this.jLabel9.setFont(new Font("Arial", 1, 11));
        this.jLabel9.setText("Vasos:");
        this.Vasos.add(this.JRBVaSanos);
        this.JRBVaSanos.setFont(new Font("Arial", 1, 11));
        this.JRBVaSanos.setText("Sanos");
        this.JRBVaSanos.setName("1");
        this.Vasos.add(this.JRBVaTortuosos);
        this.JRBVaTortuosos.setFont(new Font("Arial", 1, 11));
        this.JRBVaTortuosos.setText("Tortuosos");
        this.JRBVaTortuosos.setName("2");
        this.jPanel2.setBorder(BorderFactory.createTitledBorder((Border) null, "Polo Posterior", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.Retina.add(this.JRBRetAplicada);
        this.JRBRetAplicada.setFont(new Font("Arial", 1, 11));
        this.JRBRetAplicada.setText("Retina aplicada");
        this.JRBRetAplicada.setName("1");
        this.Retina.add(this.JRBRetDesp);
        this.JRBRetDesp.setFont(new Font("Arial", 1, 11));
        this.JRBRetDesp.setText("Retina Desprendida");
        this.JRBRetDesp.setName("2");
        this.Retina.add(this.JRBRetInexp);
        this.JRBRetInexp.setFont(new Font("Arial", 1, 11));
        this.JRBRetInexp.setText("Retina Inexplorable");
        this.JRBRetInexp.setName("3");
        GroupLayout jPanel2Layout = new GroupLayout(this.jPanel2);
        this.jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.JRBRetAplicada).addComponent(this.JRBRetDesp).addComponent(this.JRBRetInexp)).addContainerGap(-1, 32767)));
        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addComponent(this.JRBRetAplicada, -2, 15, -2).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.JRBRetDesp, -2, 15, -2).addGap(2, 2, 2).addComponent(this.JRBRetInexp, -2, 15, -2)));
        this.jPanel3.setBorder(BorderFactory.createTitledBorder((Border) null, "Macula", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.JCHMemEpi.setFont(new Font("Arial", 1, 11));
        this.JCHMemEpi.setText("Membrana Epiretinal");
        this.JCHMemEpi.setPreferredSize(new Dimension(113, 15));
        this.JCHDisforme.setFont(new Font("Arial", 1, 11));
        this.JCHDisforme.setText("Cicatriz Disforme");
        this.JCHDisforme.setPreferredSize(new Dimension(113, 15));
        this.JCHSana.setFont(new Font("Arial", 1, 11));
        this.JCHSana.setText("Sana");
        this.JCHSana.setPreferredSize(new Dimension(113, 15));
        this.JCHPigmetacion.setFont(new Font("Arial", 1, 11));
        this.JCHPigmetacion.setText("Cambios Pigmentación");
        this.JCHPigmetacion.setPreferredSize(new Dimension(113, 15));
        this.JCHNeovascular.setFont(new Font("Arial", 1, 11));
        this.JCHNeovascular.setText("Memb. Neovascular");
        this.JCHNeovascular.setPreferredSize(new Dimension(110, 15));
        this.JCHCicatriz.setFont(new Font("Arial", 1, 11));
        this.JCHCicatriz.setText("Cicatriz");
        this.JCHCicatriz.setPreferredSize(new Dimension(113, 15));
        GroupLayout jPanel3Layout = new GroupLayout(this.jPanel3);
        this.jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.TRAILING).addGroup(GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup().addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.JCHMemEpi, -2, 143, -2).addComponent(this.JCHPigmetacion, -2, 156, -2)).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.JCHDisforme, -2, 121, -2).addComponent(this.JCHNeovascular, -2, 135, -2)).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel3Layout.createSequentialGroup().addComponent(this.JCHSana, -2, 65, -2).addGap(0, 9, 32767)).addComponent(this.JCHCicatriz, -2, 1, 32767)).addGap(3, 3, 3)));
        jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel3Layout.createSequentialGroup().addGap(0, 0, 0).addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.JCHMemEpi, -2, -1, -2).addComponent(this.JCHDisforme, -2, -1, -2).addComponent(this.JCHSana, -2, -1, -2)).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.JCHPigmetacion, -2, -1, -2).addComponent(this.JCHNeovascular, -2, -1, -2).addComponent(this.JCHCicatriz, -2, -1, -2))));
        this.JCHFoco.setFont(new Font("Arial", 1, 11));
        this.JCHFoco.setText("Foco de Coroidorretinitis");
        this.JCHFoco.setPreferredSize(new Dimension(113, 15));
        this.JTAPeriferia.setColumns(1);
        this.JTAPeriferia.setFont(new Font("Arial", 1, 12));
        this.JTAPeriferia.setLineWrap(true);
        this.JTAPeriferia.setRows(1);
        this.JTAPeriferia.setBorder(BorderFactory.createTitledBorder((Border) null, "PERIFERIA", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.jScrollPane1.setViewportView(this.JTAPeriferia);
        this.JTAObservaciones.setColumns(1);
        this.JTAObservaciones.setFont(new Font("Arial", 1, 12));
        this.JTAObservaciones.setLineWrap(true);
        this.JTAObservaciones.setRows(1);
        this.JTAObservaciones.setBorder(BorderFactory.createTitledBorder((Border) null, "Observación", 0, 0, new Font("Arial", 1, 12), Color.blue));
        this.jScrollPane2.setViewportView(this.JTAObservaciones);
        GroupLayout layout = new GroupLayout(this);
        setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addComponent(this.jLabel8).addGap(0, 0, 0).addComponent(this.JRBEx1).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JRBEx2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JRBEx3).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.JRBEx4).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JRBEx5).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JRBEx6).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JRBEx7).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JRBEx8).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JRBEx9).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JRBEx10)).addGroup(layout.createSequentialGroup().addComponent(this.jLabel9).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.JRBVaSanos).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JRBVaTortuosos)).addComponent(this.jPanel2, -2, -1, -2).addComponent(this.JTFPapilas, -2, 378, -2).addComponent(this.jPanel1, -2, -1, -2)).addGap(0, 0, 32767)).addGroup(layout.createSequentialGroup().addContainerGap().addComponent(this.JCHFoco, -2, 177, -2).addContainerGap(-1, 32767)).addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addComponent(this.jPanel3, -1, -1, 32767).addGap(3, 3, 3)).addGroup(layout.createSequentialGroup().addComponent(this.jScrollPane1).addContainerGap()).addGroup(layout.createSequentialGroup().addComponent(this.jScrollPane2).addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addComponent(this.jPanel1, -2, -1, -2).addGap(3, 3, 3).addComponent(this.JTFPapilas, -2, -1, -2).addGap(3, 3, 3).addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.JRBEx1, -2, 15, -2).addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jLabel8).addComponent(this.JRBEx2, -2, 15, -2).addComponent(this.JRBEx3, -2, 15, -2).addComponent(this.JRBEx4, -2, 15, -2).addComponent(this.JRBEx5, -2, 15, -2).addComponent(this.JRBEx6, -2, 15, -2).addComponent(this.JRBEx7, -2, 15, -2).addComponent(this.JRBEx8, -2, 15, -2).addComponent(this.JRBEx9, -2, 15, -2).addComponent(this.JRBEx10, -2, 15, -2))).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.JRBVaSanos, -2, 15, -2).addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(this.jLabel9).addComponent(this.JRBVaTortuosos, -2, 15, -2))).addGap(5, 5, 5).addComponent(this.jPanel2, -2, -1, -2).addGap(3, 3, 3).addComponent(this.jPanel3, -2, -1, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.JCHFoco, -2, -1, -2).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.jScrollPane1, -2, 62, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.jScrollPane2, -2, 110, -2).addContainerGap()));
    }
}
