package General;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Frame;
import java.awt.LayoutManager;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;

/* JADX INFO: loaded from: GenomaP.jar:General/Acercade.class */
public class Acercade extends JDialog {
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel jLabel13;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JPanel jPanel1;
    private JPanel jPanel3;
    private JSeparator jSeparator1;
    private JSeparator jSeparator2;
    private JSeparator jSeparator3;
    private JSeparator jSeparator4;

    public Acercade(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocation(200, 200);
    }

    private void initComponents() {
        this.jPanel1 = new JPanel();
        this.jLabel1 = new JLabel();
        this.jPanel3 = new JPanel();
        this.jLabel4 = new JLabel();
        this.jLabel6 = new JLabel();
        this.jLabel7 = new JLabel();
        this.jLabel8 = new JLabel();
        this.jLabel9 = new JLabel();
        this.jLabel10 = new JLabel();
        this.jLabel5 = new JLabel();
        this.jLabel11 = new JLabel();
        this.jLabel12 = new JLabel();
        this.jSeparator1 = new JSeparator();
        this.jSeparator2 = new JSeparator();
        this.jLabel2 = new JLabel();
        this.jLabel3 = new JLabel();
        this.jSeparator3 = new JSeparator();
        this.jSeparator4 = new JSeparator();
        this.jLabel13 = new JLabel();
        setDefaultCloseOperation(2);
        setTitle("G@noma Soft  -  Desarrollo de Software a la Medida");
        setBackground(new Color(102, 102, 255));
        setMinimumSize(new Dimension(450, 365));
        setModal(true);
        setName("Acercade");
        setResizable(false);
        this.jPanel1.setBackground(new Color(204, 255, 255));
        this.jPanel1.setBorder(BorderFactory.createEtchedBorder());
        this.jPanel1.setLayout((LayoutManager) null);
        this.jLabel1.setIcon(new ImageIcon(getClass().getResource("/Imagenes/LogoPymeSoft.png")));
        this.jPanel1.add(this.jLabel1);
        this.jLabel1.setBounds(20, 20, 120, 80);
        this.jPanel3.setBorder(BorderFactory.createEtchedBorder());
        this.jPanel3.setOpaque(false);
        this.jPanel3.setLayout((LayoutManager) null);
        this.jLabel4.setFont(new Font("Tahoma", 1, 11));
        this.jLabel4.setForeground(new Color(0, 102, 102));
        this.jLabel4.setHorizontalAlignment(2);
        this.jLabel4.setText("Diseño de Bases de Datos :");
        this.jPanel3.add(this.jLabel4);
        this.jLabel4.setBounds(20, 90, 150, 20);
        this.jLabel6.setBackground(new Color(0, 0, 102));
        this.jLabel6.setFont(new Font("Tahoma", 1, 11));
        this.jLabel6.setForeground(new Color(0, 255, 204));
        this.jLabel6.setHorizontalAlignment(0);
        this.jLabel6.setText("Grupo de Desarrollo");
        this.jLabel6.setOpaque(true);
        this.jPanel3.add(this.jLabel6);
        this.jLabel6.setBounds(10, 10, 390, 20);
        this.jLabel7.setFont(new Font("Berlin Sans FB Demi", 0, 12));
        this.jLabel7.setForeground(new Color(0, 0, 102));
        this.jLabel7.setHorizontalAlignment(2);
        this.jLabel7.setText("Ing. William José Serpa López");
        this.jPanel3.add(this.jLabel7);
        this.jLabel7.setBounds(190, 90, 160, 20);
        this.jLabel8.setFont(new Font("Tahoma", 1, 11));
        this.jLabel8.setForeground(new Color(0, 102, 102));
        this.jLabel8.setHorizontalAlignment(2);
        this.jLabel8.setText("Desarrollo de Software :");
        this.jPanel3.add(this.jLabel8);
        this.jLabel8.setBounds(20, 40, 140, 20);
        this.jLabel9.setFont(new Font("Berlin Sans FB Demi", 0, 12));
        this.jLabel9.setForeground(new Color(0, 0, 102));
        this.jLabel9.setHorizontalAlignment(2);
        this.jLabel9.setText("Ing. Luis Alfonso Ayala Izasa");
        this.jPanel3.add(this.jLabel9);
        this.jLabel9.setBounds(190, 40, 160, 20);
        this.jLabel10.setFont(new Font("Berlin Sans FB Demi", 0, 12));
        this.jLabel10.setForeground(new Color(0, 0, 102));
        this.jLabel10.setHorizontalAlignment(2);
        this.jLabel10.setText("José David Padilla Cárdenas");
        this.jPanel3.add(this.jLabel10);
        this.jLabel10.setBounds(190, 60, 170, 20);
        this.jPanel1.add(this.jPanel3);
        this.jPanel3.setBounds(20, 160, 410, 130);
        this.jLabel5.setFont(new Font("Amienne", 1, 48));
        this.jLabel5.setForeground(new Color(153, 0, 0));
        this.jLabel5.setHorizontalAlignment(0);
        this.jLabel5.setText("ManGo");
        this.jPanel1.add(this.jLabel5);
        this.jLabel5.setBounds(170, 60, 250, 35);
        this.jLabel11.setFont(new Font("Amienne", 0, 48));
        this.jLabel11.setForeground(new Color(0, 102, 102));
        this.jLabel11.setText("G@noma Soft");
        this.jPanel1.add(this.jLabel11);
        this.jLabel11.setBounds(190, 100, 210, 60);
        this.jLabel12.setFont(new Font("Amienne", 1, 48));
        this.jLabel12.setForeground(new Color(0, 0, 102));
        this.jLabel12.setHorizontalAlignment(0);
        this.jLabel12.setText("Proyecto");
        this.jPanel1.add(this.jLabel12);
        this.jLabel12.setBounds(170, 30, 250, 35);
        this.jPanel1.add(this.jSeparator1);
        this.jSeparator1.setBounds(170, 20, 250, 10);
        this.jPanel1.add(this.jSeparator2);
        this.jSeparator2.setBounds(20, 350, 410, 10);
        this.jLabel2.setForeground(new Color(102, 0, 204));
        this.jLabel2.setHorizontalAlignment(0);
        this.jLabel2.setText("Cel : 317-4389497,  313-6594561, 301-4770136");
        this.jPanel1.add(this.jLabel2);
        this.jLabel2.setBounds(20, 330, 410, 20);
        this.jLabel3.setForeground(new Color(102, 0, 204));
        this.jLabel3.setHorizontalAlignment(0);
        this.jLabel3.setText("http://www.pymesoft.com.co    E-Mail pymesoft.gmail.com");
        this.jPanel1.add(this.jLabel3);
        this.jLabel3.setBounds(20, 310, 410, 20);
        this.jPanel1.add(this.jSeparator3);
        this.jSeparator3.setBounds(170, 100, 250, 10);
        this.jPanel1.add(this.jSeparator4);
        this.jSeparator4.setBounds(20, 300, 410, 10);
        this.jLabel13.setIcon(new ImageIcon(getClass().getResource("/Imagenes/Mango.png")));
        this.jPanel1.add(this.jLabel13);
        this.jLabel13.setBounds(370, 40, 44, 42);
        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.jPanel1, -1, 450, 32767));
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.jPanel1, -1, 365, 32767));
        pack();
    }
}
